import {test,expect} from '@playwright/test';
test('structured value intake preserves zero, locks duplicate entries and separates currencies',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/src/lib/useOperationalRows.ts*',r=>r.fulfill({contentType:'application/javascript',body:`import React from '/node_modules/.vite/deps/react.js';window.valueRows=[];export function useOperationalRows(){const [rows,set]=React.useState([]);return {rows,notice:'',refresh:async()=>set([...window.valueRows])}}`}));
 await page.route('**/src/lib/pilotSupabase.ts*',r=>r.fulfill({contentType:'application/javascript',body:`export const pilotSupabase={from(){return {async insert(v){window.valueRows.push({...v,title:v.artwork_id,recorded_at:new Date().toISOString()});return {error:null}}}}};`}));
 await page.route('**/src/main.tsx*',r=>r.fulfill({contentType:'application/javascript',body:`import React from '/node_modules/.vite/deps/react.js';import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';import {ArtworkValues} from '/src/components/ArtworkValues.tsx';import '/src/index.css';ReactDOM.createRoot(document.getElementById('root')).render(React.createElement('main',{dir:'rtl'},React.createElement(ArtworkValues,{artworks:[{id:'a',source:{title:'Work A'}},{id:'b',source:{title:'Work B'}}]})));window.dispatchEvent(new Event('sadu:ready'));`}));
 await page.goto('/');await page.getByRole('combobox',{name:/^Artwork/}).selectOption('a');await page.getByLabel(/^Amount/).fill('0');await page.getByRole('button',{name:/Record declared/}).click();await expect(page.getByText(/a · 0.00 USD/)).toBeVisible();await expect(page.getByRole('option',{name:'Work A'})).toHaveCount(0);
 await page.getByRole('combobox',{name:/^Artwork/}).selectOption('b');await page.getByLabel(/^Amount/).fill('10.001');await expect(page.getByRole('button',{name:/Record declared/})).toBeDisabled();await page.getByLabel(/^Amount/).fill('10.25');await page.getByRole('combobox',{name:/^Currency/}).selectOption('AED');await page.getByRole('button',{name:/Record declared/}).click();await expect(page.getByText(/Total.*AED:DECLARED_SALE_VALUE: 10.25/)).toBeVisible();await expect(page.getByText(/Total.*USD:DECLARED_SALE_VALUE: 0.00/)).toBeVisible();expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
