import {test,expect} from '@playwright/test';
for(const logistics of [false,true])test(logistics?'closure assignment requires provisioned IDs and dates':'vendor sees assigned freight and closure alert',async({page},info)=>{
 await page.route('**/src/lib/useOperationalRows.ts*',r=>r.fulfill({contentType:'application/javascript',body:`export function useOperationalRows(table){return {rows:window.data[table]||[],notice:'',live:false,refresh:async()=>{}}}`}));
 await page.route('**/src/lib/pilotSupabase.ts*',r=>r.fulfill({contentType:'application/javascript',body:`export const pilotSupabase={auth:{onAuthStateChange(){return {data:{subscription:{unsubscribe(){}}}};}},from(){return {async insert(value){window.saved=value;return {error:null};}};}};`}));
 await page.route('**/src/main.tsx*',r=>r.fulfill({contentType:'application/javascript',body:`import React from '/node_modules/.vite/deps/react.js';import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';import {FreightClosureLedger} from '/src/components/FreightClosureLedger.tsx';import '/src/index.css';window.data={sadu_freight_assignments:${logistics?'[]':`[{consignment_id:'test',details_due:'2026-07-20',closure_start:'2026-07-25',reopens_on:'2026-09-02',facility_timezone:'Europe/Paris'}]`},sadu_freight_alerts:[{consignment_id:'test',status:'OPEN',created_at:'2026-07-20T08:00:00Z'}],sadu_consignments:[{id:'test',artwork_id:'artwork',origin:'THIRD_PARTY_GALLERY',contact_name:'Gallery',status:'CONSIGNMENT_DATA_RECEIVED',details:{length_cm:100,width_cm:80,height_cm:40,weight_kg:84,insurance_value:5000,currency:'EUR',country:'France',city:'Paris',district:'Test',street:'Test',building:'Gallery',hours:'8AM to noon',phone:'+33123456789',map_url:'https://maps.google.com/'}}]};ReactDOM.createRoot(document.getElementById('root')).render(React.createElement('main',{dir:'rtl'},React.createElement(FreightClosureLedger,{logistics:${logistics},vendor:${!logistics}})));window.dispatchEvent(new Event('sadu:ready'));`}));
 await page.goto('/');
 if(logistics){const save=page.getByRole('button',{name:/Record closure/});await expect(save).toBeDisabled();await page.getByLabel('Gallery consignment').selectOption('test');await page.getByLabel('Approved vendor account ID').fill('88888888-8888-4888-8888-888888888888');await page.getByLabel('Assigned curator account ID').fill('99999999-9999-4999-8999-999999999999');await page.getByLabel('Facility closes on').fill('2026-07-25');await page.getByLabel('Facility reopens on').fill('2026-07-24');await expect(save).toBeDisabled();await page.getByLabel('Facility reopens on').fill('2026-09-02');await save.click();await expect(page.getByRole('status')).toContainText('recorded');}
 else{await expect(page.getByText(/HIGH PRIORITY/)).toBeVisible();await expect(page.getByText('2026-07-20',{exact:true})).toBeVisible();await expect(page.getByText('5000 EUR')).toBeVisible();await expect(page.getByRole('textbox')).toHaveCount(0);await expect(page.getByText(/not a verified valuation/)).toBeVisible();}
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('freight.png'),fullPage:true});
});
