import {test,expect} from '@playwright/test';
test('guest uploads validate, resume without duplicate intake and reach sortable PR queue',async({page},info)=>{
 await page.route('**/src/lib/useOperationalRows.ts*',r=>r.fulfill({contentType:'application/javascript',body:'export function useOperationalRows(){return {rows:[],notice:"",refresh:async()=>{}}}'}));
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/src/lib/pilotSupabase.ts*',route=>route.fulfill({contentType:'application/javascript',body:`
 const db=[];const plans=[];const stored=new Map();let failPhoto=true;window.guestRows=db;
 const contracts=[{id:'c',artist_name:'Sample Guest'},{id:'d',artist_name:'Waiting Guest'}];
 const queue=()=>db.map(r=>({...r,artist_name:'Sample Guest',contract_status:'ARTIST_APPROVED',passport_uploaded:stored.has(r.artist_id+'/guest-intake/'+r.id+'/passport.pdf'),photo_uploaded:stored.has(r.artist_id+'/guest-intake/'+r.id+'/photo.png'),companion_uploaded:false,national_id_required:r.identity.nationality==='IQ',national_id_uploaded:stored.has(r.artist_id+'/guest-intake/'+r.id+'/national-id.pdf')}));
 export const pilotSupabase={auth:{getUser:async()=>({data:{user:{id:'owner'}}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})},rpc:async(name,args)=>{if(name==='sadu_finalize_guest'){db.find(r=>r.id===args.p_id).finalized_at=new Date().toISOString();return {data:new Date().toISOString(),error:null}}return {data:contracts,error:null}},from(table){return {select(){return this},single(){return this},maybeSingle(){return Promise.resolve({data:null,error:null})},eq(){return this},in(){return this},order(){return this},then(resolve){resolve({data:table==='bilateral_contracts'?contracts:table==='sadu_guest_document_policy'?{version:'test',national_id_countries:['IQ','PK','AF'],reference:'PR test'}:table==='sadu_guest_deadline_policy'?{lead_days:30}:table==='sadu_guest_reminder_outbox'?[]:table==='sadu_guest_travel_plans'?plans:queue(),error:null})},async insert(r){(table==='sadu_guest_travel_plans'?plans:db).push({...r,created_at:new Date().toISOString()});return {error:null}}}},storage:{from(){return {async list(folder){return {data:[...stored].filter(([path])=>path.startsWith(folder+'/')).map(([path,size])=>({name:path.split('/').pop(),metadata:{size}}))}},async upload(path,file){if(path.endsWith('photo.png')&&failPhoto){failPhoto=false;return {error:{message:'offline'}}}stored.set(path,file.size);return {error:null}},async createSignedUrl(){return {data:{signedUrl:location.origin+'/private-test'}}}}}}};
 `}));
 await page.route('**/src/main.tsx*',route=>route.fulfill({contentType:'application/javascript',body:`import React from '/node_modules/.vite/deps/react.js';import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';import {GuestTravel} from '/src/components/GuestTravel.tsx';import '/src/index.css';const h=React.createElement;function App(){const [review,set]=React.useState(false);return h('main',{style:{padding:16}},h('button',{onClick:()=>set(!review)},'Switch PR'),h(GuestTravel,{review,key:String(review)}));}ReactDOM.createRoot(document.getElementById('root')).render(h(App));window.dispatchEvent(new Event('sadu:ready'));`}));
 await page.goto('/');await page.getByRole('combobox',{name:/Agreement/}).selectOption('c');await page.getByLabel(/^Arrival/).fill('2026-10-06');await page.getByLabel(/^Departure \//).fill('2026-10-11');await page.getByRole('button',{name:/Save travel dates/}).click();await expect(page.getByRole('status')).toContainText('Travel dates saved');await expect(page.getByRole('button',{name:/Submit to PR/})).toBeDisabled();
 await page.getByRole('combobox',{name:/Airport preference/}).selectOption('SHJ');await page.getByRole('combobox',{name:/Departure airport/}).selectOption('DXB');
 for(const [label,value] of [['Passport number','SAMPLE'],['Passport expiry','2030-01-01'],['Date of birth','1990-01-01'],['Place of birth','Sample'],['Email','sample@example.test'],['Home/mobile phone','000']])await page.getByLabel(new RegExp('^'+label.replace('/','\\/'))).fill(value);
 await page.getByRole('combobox',{name:/^Current nationality/}).selectOption('IQ');
 await expect(page.getByLabel(/^National ID/)).toBeVisible();
 await page.getByLabel(/^Passport expiry/).fill('2027-04-05');await expect(page.getByRole('alert')).toContainText('2027-04-06');await expect(page.getByRole('button',{name:/Submit to PR/})).toBeDisabled();await page.getByLabel(/^Passport expiry/).fill('2027-04-06');
 await page.getByLabel(/^National ID/).setInputFiles({name:'id.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.7 test ID')});
 const portrait=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=1200;return c.toDataURL('image/png').split(',')[1]});
 await page.getByLabel(/Personal photo/).setInputFiles({name:'portrait.png',mimeType:'image/png',buffer:Buffer.from(portrait,'base64')});
 await page.getByLabel(/^Passport \//).setInputFiles({name:'wrong.pdf',mimeType:'application/pdf',buffer:Buffer.from('bad')});await page.getByRole('button',{name:/Submit to PR/}).click();await expect(page.getByRole('status')).toContainText('Invalid format');
 await page.getByLabel(/^Passport \//).setInputFiles({name:'passport.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.7 sample')});await page.getByRole('button',{name:/Submit to PR/}).click();await expect(page.getByRole('status')).toContainText('interrupted');await expect(page.getByLabel(/^Arrival/)).toBeDisabled();await page.getByRole('button',{name:'Retry uploads'}).click();await expect(page.getByRole('status')).toContainText('awaiting PR inspection');expect(await page.evaluate(()=>(window as any).guestRows.length)).toBe(1);
 await page.getByRole('button',{name:'Switch PR'}).click();await expect(page.getByText('All declared files present — not PR clearance')).toBeVisible();await expect(page.getByText('Waiting Guest',{exact:true})).toBeVisible();await page.getByRole('combobox',{name:/Sort/}).selectOption('missing');await page.getByLabel(/Search guests/).fill('Sample');await expect(page.getByText('Waiting Guest',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Passport PDF',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'National ID PDF',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('guest-pr.png'),fullPage:true});expect(errors).toEqual([]);
});

