import { test, expect, type Page } from '@playwright/test';

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => { localStorage.setItem('sadu_lang', 'en'); localStorage.setItem('sadu_experience_mode', 'platform'); });
});
const role = (page: Page, name: string) => page.getByRole('navigation', { name: 'Demonstration roles' }).getByRole('button', { name, exact: true }).click();
async function register(page: Page) {
  await page.goto('/join');
  await page.getByRole('button', { name: 'Fill sample profile (replaces current profile text)' }).click();
  await page.getByRole('button', { name: /Review registration/ }).click();
  await page.getByRole('checkbox', { name: /I reviewed these fictional details/ }).check();
  await page.getByRole('button', { name: 'Register sample profile', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Profile received. Coordinator review is next.' })).toBeVisible();
}

test('registration → roster review → programme → proposal → selection → linked custody → executive totals', async ({ page }, testInfo) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await register(page);
  await page.getByRole('button', { name: 'View demo roster', exact: true }).click();
  const artist = page.locator('article.roster-person').filter({ hasText: 'DEMO-ART-001' });
  await expect(artist.getByRole('checkbox')).toBeDisabled();
  await artist.getByRole('button', { name: 'Switch to sample coordinator' }).click();
  await artist.getByRole('button', { name: 'Record simulated coordinator review' }).click();
  await expect(artist).toContainText('Verified · simulated');
  await page.getByRole('button', { name: 'Back to artist registration' }).click();
  await expect(page.getByRole('heading', { name: 'Sample profile review recorded.' })).toBeVisible();
  await page.getByRole('button', { name: 'View demo roster', exact: true }).click();
  await page.getByLabel('Programme title · English', { exact: true }).fill('E2E Paper Programme');
  await page.getByLabel('Programme title · Arabic', { exact: true }).fill('برنامج الورق التجريبي');
  await artist.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Create sample programme draft' }).click();
  await page.getByRole('button', { name: 'Open programme proposals' }).click();
  await expect(page.getByRole('combobox', { name: 'Choose a fictional programme' })).toHaveValue(/^DEMO-PROGRAMME-/);
  await page.getByRole('button', { name: 'Load sample proposal (replaces this programme only)' }).click();
  await page.getByRole('button', { name: /Review and submit/ }).click();
  await page.getByRole('checkbox', { name: /I reviewed this sample proposal/ }).check();
  await page.getByRole('button', { name: 'Submit sample proposal', exact: true }).click();
  await expect(page.getByText('Sample proposal received; coordinator check is next.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Open coordinator review' }).click();
  await page.locator('details.intake-review-item summary').click();
  await page.getByRole('checkbox', { name: /I checked this version for completeness/ }).check();
  await page.getByRole('button', { name: 'Record completeness check' }).click();
  await expect(page.getByRole('button', { name: 'Simulate selection & create delivery' })).toHaveCount(0);
  await role(page, 'Logistics');
  await expect(page.getByTestId('linked-totals')).toContainText('0 / 0');
  await role(page, 'Selection simulation');
  await page.locator('details.intake-review-item summary').click();
  await page.getByRole('checkbox', { name: /I reviewed this version for a simulated selection/ }).check();
  await page.getByRole('button', { name: 'Simulate selection & create delivery' }).click();
  await expect(page.getByRole('button', { name: 'Simulate selection & create delivery' })).toHaveCount(0);
  await role(page, 'Logistics');
  const delivery = page.getByTestId('proposal-delivery');
  await expect(delivery).toHaveCount(1); await expect(delivery).toContainText('E2E Paper Programme');
  await expect(delivery).toContainText('Awaiting arrival');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  const id = (await delivery.locator('bdi').first().innerText()).trim();
  await delivery.getByLabel('Expected asset identity').fill(id);
  await delivery.getByRole('checkbox').check();
  await delivery.getByRole('button', { name: 'Record linked arrival' }).click();
  await role(page, 'Technical');
  await delivery.getByRole('button', { name: 'Record linked condition evidence' }).click();
  await role(page, 'Directorate');
  await expect(page.getByTestId('linked-totals')).toContainText('0 / 1');
  await expect(page.getByRole('button', { name: 'Review linked handover', exact: true })).toHaveCount(0);
  await role(page, 'Exhibition manager');
  await delivery.getByRole('button', { name: 'Review linked handover', exact: true }).click();
  const dossier = page.getByRole('dialog', { name: 'Review linked handover', exact: true });
  const accept = dossier.getByRole('button', { name: 'Record linked handover acknowledgement' });
  await expect(accept).toBeDisabled();
  await dossier.getByRole('checkbox').check(); await accept.click();
  await expect(delivery).toContainText('Handover acknowledged');
  await role(page, 'Chairman');
  await expect(page.getByTestId('linked-totals')).toContainText('1 / 1');
  await expect(page.getByTestId('linked-totals')).toContainText('Pending: 0');
  await role(page, 'Artist intake');
  await expect(page.getByText('Selection simulated; linked delivery created.', { exact: false })).toContainText('Handover acknowledged');
  await role(page, 'Chairman');
  await page.getByRole('button', { name: 'العربية', exact: true }).click();
  await expect(page.locator('.living-record')).toHaveAttribute('dir', 'rtl');
  await expect(page.getByTestId('linked-totals')).toContainText('١ / ١');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('linked-summary-ar.png'), fullPage: true });
  expect(errors).toEqual([]);
});

test('loading one sample keeps the artist and another programme draft; registration receipt survives navigation', async ({ page }) => {
  await register(page);
  await page.getByRole('button', { name: 'View demo roster', exact: true }).click();
  await page.getByRole('button', { name: 'Back to artist registration' }).click();
  await expect(page.getByRole('heading', { name: 'Profile received. Coordinator review is next.' })).toBeVisible();
  await page.getByRole('button', { name: 'Explore sample programme proposals' }).click();
  await page.getByLabel('Display name · English', { exact: true }).fill('Keep my artist name');
  const programmes = page.getByRole('combobox', { name: 'Choose a fictional programme' });
  await programmes.selectOption('DEMO-CALL-01');
  await page.getByLabel(/^Concept · English/).fill('Keep programme one draft');
  await programmes.selectOption('DEMO-CALL-02');
  await page.getByRole('button', { name: 'Load sample proposal (replaces this programme only)' }).click();
  await expect(programmes).toHaveValue('DEMO-CALL-02');
  await expect(page.getByLabel('Proposal title · English', { exact: true })).toHaveValue('Layers of Memory');
  await programmes.selectOption('DEMO-CALL-01');
  await expect(page.getByLabel(/^Concept · English/)).toHaveValue('Keep programme one draft');
  await page.locator('.intake-steps').getByRole('button', { name: /Profile/ }).click();
  await expect(page.getByLabel('Display name · English', { exact: true })).toHaveValue('Keep my artist name');
});

test('editorial checks survive navigation; desktop programme scope is respected', async ({ page }, testInfo) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Other sample workspaces', exact: true }).click();
  await page.getByRole('button', { name: 'Mohammed Ibrahim Al Qaseer', exact: true }).click();
  await page.getByRole('button', { name: 'Editorial & Translation Bureau', exact: true }).click();
  await page.getByRole('button', { name: 'Enter sample workspace', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Editorial, Translation & Catalogue Desk' })).toBeVisible();
  await expect(page.getByText('20 words', { exact: true })).toBeVisible();
  await expect(page.getByText('22 كلمة', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Record Sample Editorial Check', exact: true }).first().click();
  await page.getByRole('button', { name: /Specialist Operations/ }).first().click();
  await expect(page.getByText('Sample Editorial Check Recorded', { exact: true })).toBeVisible();
  if (testInfo.project.name === 'mobile') return;
  await page.getByRole('button', { name: /Scope:.*Lines of Ink/ }).click();
  await page.getByRole('button', { name: 'Salt and Palm: Architectural & Material Resonances', exact: true }).click();
  await expect(page.getByText('No editorial sample records for the selected programme.', { exact: true })).toBeVisible();
  await expect(page.getByText('45%', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: /Scope:.*Salt and Palm/ }).click();
  await page.getByRole('button', { name: 'Lines of Ink: Contemporary Diwani & Kufic Forms', exact: true }).click();
  await expect(page.getByText('Sample Editorial Check Recorded', { exact: true })).toBeVisible();
  await expect(page.getByText('82%', { exact: true })).toBeVisible();
});
