import {test,expect} from '@playwright/test';
test('title intake and physical arrival require complete evidence',async({page},info)=>{
 await page.route('**/src/lib/useOperationalRows.ts*',r=>r.fulfill({contentType:'application/javascript',body:`export function useOperationalRows(){return {rows:[],notice:'',live:false,refresh:async()=>{}}}` }));
 await page.route('**/src/lib/pilotSupabase.ts*',r=>r.fulfill({contentType:'application/javascript',body:`export const pilotSupabase={auth:{onAuthStateChange(){return {data:{subscription:{unsubscribe(){}}}};}},from(table){return {async insert(payload){window.saved={table,payload};return {error:null};}};}};`}));
 await page.route('**/src/main.tsx*',r=>r.fulfill({contentType:'application/javascript',body:`import React from '/node_modules/.vite/deps/react.js';import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';import {ExhibitionTitleGate} from '/src/components/ExhibitionTitleGate.tsx';import {ArrivalRecorder,ArrivalFeed} from '/src/components/ArrivalFeed.tsx';import '/src/index.css';ReactDOM.createRoot(document.getElementById('root')).render(React.createElement('main',{dir:'rtl'},React.createElement(ExhibitionTitleGate,{scenarioId:'scenario'}),React.createElement(ArrivalRecorder,{bookingId:'booking'}),React.createElement(ArrivalFeed)));window.dispatchEvent(new Event('sadu:ready'));`}));
 await page.goto('/');const submit=page.getByRole('button',{name:'Submit title for review'});await expect(submit).toBeDisabled();await page.getByLabel('Exhibition title Arabic').fill('ميزان');await expect(submit).toBeDisabled();await page.getByLabel('Exhibition title English').fill('Balance');await submit.click();await expect(page.getByText('Title submitted for curatorial review.')).toBeVisible();
 const arrival=page.getByRole('button',{name:/Record physical arrival/});await expect(arrival).toBeDisabled();await page.getByLabel('Actual receiving facility').fill('Sharjah Art Museum');await expect(arrival).toBeDisabled();await page.getByRole('checkbox').check();await arrival.click();await expect(page.getByText('Arrival recorded in the shared feed. Condition inspection remains separate.')).toBeVisible();await expect(arrival).toBeDisabled();
 expect(await page.evaluate(()=>(window as any).saved)).toEqual({table:'sadu_arrival_receipts',payload:{booking_id:'booking',facility:'Sharjah Art Museum',all_crates_received:true}});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('materials-receiving.png'),fullPage:true});
});
