import {test,expect} from '@playwright/test';
test('publication readiness withdraws on amendment and PR-approved windows appear without private data',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/src/lib/pilotSupabase.ts*',r=>r.fulfill({contentType:'application/javascript',body:`
 let approved=false;export const pilotSupabase={auth:{onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})},rpc:async()=>({data:approved?[{contract_id:'c',artist_name:'Sample Guest',arrival:'2026-10-06',departure:'2026-10-11',arrival_airport:'SHJ',departure_airport:'DXB',approved_at:'2026-09-29T10:00:00Z'}]:[],error:null}),from(){return {select(){return this},eq(){return this},maybeSingle:async()=>({data:null}),insert(){approved=true;return this},single:async()=>({data:{approved_at:'2026-09-29T10:00:00Z'},error:null})}}};`}));
 await page.route('**/src/main.tsx*',r=>r.fulfill({contentType:'application/javascript',body:`
 import React from '/node_modules/.vite/deps/react.js';import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';import {SessionDraftProvider,useSessionDraft} from '/src/context/SessionDrafts.tsx';import {AssetStateDashboard} from '/src/components/AssetStateDashboard.tsx';import {OperationalGuestCalendar,GuestItineraryApproval} from '/src/components/OperationalGuestCalendar.tsx';import '/src/index.css';const h=React.createElement;
 function App(){const [rows,set]=useSessionDraft('artwork-rosters:v1',{});const [key,refresh]=React.useState(0);return h('main',{dir:'rtl',style:{padding:16}},h('button',{onClick:()=>set({a:{artistId:'a',status:'LOCKED_PENDING_REVIEW',items:[],events:[],history:[{revision:1,items:[],at:'2026-09-28T00:00:00Z'}],publications:[{revision:1,at:'2026-09-29T00:00:00Z'}]}})},'Seed approved publication'),h('button',{onClick:()=>set({...rows,a:{...rows.a,status:'AMENDMENT_REQUESTED'}})},'Request amendment'),h(AssetStateDashboard,{artists:[{id:'a',artistName:'Sample Artist'}]}),h(GuestItineraryApproval,{intakeId:'test'}),h('button',{onClick:()=>refresh(key+1)},'Refresh calendar'),h(OperationalGuestCalendar,{key}));}ReactDOM.createRoot(document.getElementById('root')).render(h(SessionDraftProvider,null,h(App)));window.dispatchEvent(new Event('sadu:ready'));`}));
 await page.goto('/');await expect(page.getByText(/Awaiting complete label submission/)).toBeVisible();
 await page.getByRole('button',{name:'Seed approved publication'}).click();await expect(page.getByText(/LABELS_READY_FOR_PRINT/)).toBeVisible();
 await page.getByRole('button',{name:'Request amendment'}).click();await expect(page.getByText(/LABELS_READY_FOR_PRINT/)).toHaveCount(0);await expect(page.getByText(/print readiness withdrawn/)).toBeVisible();
 await expect(page.getByRole('button',{name:/Record itinerary approval/})).toBeDisabled();await page.getByLabel(/Reviewed ticket reference/).fill('Private-reference');await page.getByRole('checkbox').check();await page.getByRole('button',{name:/Record itinerary approval/}).click();await expect(page.getByText(/PR approval recorded:/)).toBeVisible();
 await page.getByRole('button',{name:'Refresh calendar'}).click();await expect(page.getByText('Sample Guest',{exact:true})).toBeVisible();await expect(page.getByText(/2026-10-06 \(SHJ\)/)).toBeVisible();await expect(page.getByText('Private-reference',{exact:true})).toHaveCount(0);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);await page.screenshot({path:info.outputPath('operational.png'),fullPage:true});
});
