import {test,expect} from '@playwright/test';
test('venue rules block hall welding and personnel manifest reaches only matching museum view',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/src/main.tsx*',route=>route.fulfill({contentType:'application/javascript',body:`
 import React from '/node_modules/.vite/deps/react.js';import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';import {SessionDraftProvider,useSessionDraft} from '/src/context/SessionDrafts.tsx';import {TechnicalRequestLedger} from '/src/components/TechnicalRequestLedger.tsx';import {FabricationLedger} from '/src/components/DeliverableRouting.tsx';import {GovernanceDesk} from '/src/components/VenueGovernance.tsx';import '/src/index.css';const h=React.createElement;
 function App(){const [desk,setDesk]=React.useState('technical');const [,setClaims]=useSessionDraft('spatial-claims:biennial-2026',[]);React.useEffect(()=>setClaims([{artistId:'a',spaceId:'sam-hall-1',venueId:'SHARJAH_ART_MUSEUM',curator:'Sharjah Art Museum — Venue Curator'}]),[]);return h('main',{style:{padding:16}},...['technical','coordinator','venue'].map(v=>h('button',{onClick:()=>setDesk(v),key:v},v)),desk==='technical'?h(TechnicalRequestLedger,{artistId:'a',artistName:'Sample artist',isAr:false}):desk==='coordinator'?h(FabricationLedger,{artistId:'a',actor:'COORDINATOR',isAr:false}):h(GovernanceDesk,{role:'TECHNICAL',pending:[],dossiers:[{id:'a',artistName:'Sample artist',status:'APPROVED',medium:'Ink'}]}));}
 ReactDOM.createRoot(document.getElementById('root')).render(h(SessionDraftProvider,null,h(App)));window.dispatchEvent(new Event('sadu:ready'));
 `}));
 await page.goto('/');await page.getByRole('combobox',{name:/Work activity/}).selectOption('WELDING');await page.getByLabel(/Assigned technical personnel/).fill('Sample Technician');await expect(page.getByRole('alert')).toContainText('Rule 5');await expect(page.getByRole('button',{name:'Record both routes'})).toBeDisabled();
 await page.getByRole('combobox',{name:/Work location/}).selectOption('OUTSIDE_HALL');await page.getByRole('button',{name:'Record both routes'}).click();await expect(page.getByRole('button',{name:'Request already recorded'})).toBeDisabled();
 await page.getByRole('button',{name:'coordinator',exact:true}).click();await page.getByRole('combobox',{name:/Request track/}).selectOption('fabrication');await page.getByLabel('Fabricated Item',{exact:true}).fill('Sample frame');await page.getByLabel('Assigned Vendor/Technician',{exact:true}).fill('Sample Workshop');await page.getByLabel(/Assigned personnel/).fill('Sample Carpenter');await expect(page.getByRole('button',{name:'Record fabrication order'})).toBeDisabled();await expect(page.getByRole('alert')).toContainText('Rule 5');await page.getByRole('combobox',{name:/Work location/}).selectOption('OUTSIDE_HALL');await page.getByRole('button',{name:'Record fabrication order'}).click();
 await page.getByRole('button',{name:'venue',exact:true}).click();await page.locator('summary').click();await expect(page.getByRole('listitem').filter({hasText:'Sample Carpenter'})).toBeVisible();await expect(page.getByRole('listitem').filter({hasText:'Sample Technician'})).toBeVisible();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Generate Worker Manifest PDF'}).click();await (await download).saveAs(info.outputPath('worker-manifest.pdf'));
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('manifest.png'),fullPage:true});await page.getByRole('combobox',{name:/Venue authority/}).selectOption('HOUSE_OF_WISDOM');await expect(page.getByRole('button',{name:'Generate Worker Manifest PDF'})).toHaveCount(0);expect(errors).toEqual([]);
});
