import {test,expect} from '@playwright/test';
test('PR refusal confirmation is gated and artist sees a held notice without an email claim',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/src/lib/useOperationalRows.ts*',r=>r.fulfill({contentType:'application/javascript',body:`import React from '/node_modules/.vite/deps/react.js';window.notices=[];export function useOperationalRows(table){const [rows,set]=React.useState(table==='sadu_visa_notice_templates'?[{version:'draft',body_ar:'مسودة للمراجعة',body_en:'Draft for review',approved_at:null}]:window.notices);return {rows,notice:'',refresh:async()=>set([...window.notices])};}`}));
 await page.route('**/src/lib/pilotSupabase.ts*',r=>r.fulfill({contentType:'application/javascript',body:`export const pilotSupabase={auth:{onAuthStateChange(){return {data:{subscription:{unsubscribe(){}}}};}},async rpc(){window.calls=(window.calls||0)+1;window.notices=[{contract_id:'c',visa_status:'REJECTED_BY_AUTHORITY',delivery_status:'TEMPLATE_APPROVAL_REQUIRED',recorded_at:'2026-09-29T10:00:00Z',body_ar:null,body_en:null}];return {data:'2026-09-29T10:00:00Z',error:null};}};`}));
 await page.route('**/src/main.tsx*',r=>r.fulfill({contentType:'application/javascript',body:`import React from '/node_modules/.vite/deps/react.js';import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';import {VisaAuthorityPanel} from '/src/components/VisaAuthorityPanel.tsx';import '/src/index.css';function App(){const [pr,set]=React.useState(true);return React.createElement('main',{style:{padding:16}},React.createElement('button',{onClick:()=>set(false)},'Artist view'),React.createElement(VisaAuthorityPanel,{key:String(pr),review:pr,guests:[{id:'i',contract_id:'c',artist_name:'Sample Guest',finalized_at:'2026-09-29'}]}));}ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(App));window.dispatchEvent(new Event('sadu:ready'));`}));
 await page.goto('/');const button=page.getByRole('button',{name:/Record REJECTED/});await expect(button).toBeDisabled();await page.getByRole('combobox').selectOption('i');await page.getByLabel(/^Authority decision reference/).fill('AUTH-123');await expect(button).toBeDisabled();await page.getByRole('checkbox').check();await button.click();await expect(page.getByText(/Official notification awaiting/)).toBeVisible();await expect(button).toBeDisabled();expect(await page.evaluate(()=>(window as any).calls)).toBe(1);
 await page.getByRole('button',{name:'Artist view'}).click();await expect(page.getByRole('button',{name:/Record REJECTED/})).toHaveCount(0);await expect(page.getByText(/Official notification awaiting/)).toBeVisible();await expect(page.getByText('AUTH-123')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('visa-notice.png'),fullPage:true});expect(errors).toEqual([]);
});
