import { archivalRecordService } from '../server/archival-record.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { createConnectedPilot, PILOT_ARTWORK } from '../server/connected-pilot.mjs';

test('one connected HTTP journey verifies permissions, documents, return, payments and restart recovery',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'sadu-connected-'));const started=performance.now();const milestones=[];let rejected=0;
 const options={directory,gate:(_q,_r,next)=>next(),simulatedLocation:true,now:()=>new Date('2026-10-05T10:00:00Z')};let runtime=await createConnectedPilot(options);let server;
 const listen=async()=>{server=runtime.app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));return `http://127.0.0.1:${server.address().port}`;};let origin=await listen();let cookie='';
 const call=async(path,body,method='POST')=>fetch(origin+path,{...(body?{method,body:JSON.stringify(body)}:{}),headers:{Cookie:cookie,Origin:origin,'Content-Type':'application/json'}});
 const json=async(path,body,method)=>{const r=await call(path,body,method);const result=await r.json();assert.equal(r.status,200,JSON.stringify(result));return result;};
 const login=async role=>{const r=await call('/api/review/session',{accountId:`pilot-${role}`});assert.equal(r.status,200);cookie=r.headers.get('set-cookie').split(';')[0];};
 const dossier=()=>json('/api/review/pilot');
 const action=async(name,extra={})=>{const view=await dossier();return json('/api/review/pilot/action',{version:view.version,action:name,checked:true,...extra});};
 const cmd=async()=>({artworkId:PILOT_ARTWORK,versionHash:(await dossier()).revision.versionHash});
 const stamp=name=>milestones.push({name,elapsedMs:Math.round(performance.now()-started)});
 const image=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4XmN49vDSfwAI4wOZS6NgQwAAAABJRU5ErkJggg==','base64');
 try{
  assert.equal((await call('/api/review/pilot')).status,401);rejected++;
  await login('Artist');
  const metadata={artworkId:PILOT_ARTWORK,expectedRevisionId:null,artistName:{en:'Noura Al Mazrouei',ar:'نورة المزروعي'},title:{en:'Kufic Horizon',ar:'أفق كوفي'},heritage:{applicability:'NOT_APPLICABLE',reason:'Synthetic contemporary artwork outside the heritage programme.'},concept_text:'Calligraphy and architecture explore bronze, memory and space.',width_cm:120,height_cm:180,year:2026,conservation_reqs:{max_lux:50,target_temp_c:20,target_humidity_pct:40},technicalRequirements:[{item:'Projector',quantity:1,external:true}]};
  const upload=body=>fetch(origin+'/api/review/ecosystem/submission',{method:'POST',headers:{Cookie:cookie,Origin:origin,'Content-Type':'application/octet-stream','x-sadu-metadata':encodeURIComponent(JSON.stringify(body))},body:image});
  assert.equal((await upload({...metadata,title:{en:'Missing Arabic'}})).status,422);rejected++;
  assert.equal((await upload(metadata)).status,200);stamp('Submission');
  const first=await dossier();assert.equal(first.revision.media.file_hash,createHash('sha256').update(image).digest('hex'));
  const savedImage=Buffer.from(await(await call('/api/review/pilot/media')).arrayBuffer());assert.deepEqual(savedImage,image);
  assert.equal((await call('/api/review/ecosystem/publish',await cmd())).status,403);rejected++;
  await login('Editorial');await json('/api/review/ecosystem/editorial',{...await cmd(),description:{en:metadata.concept_text,ar:'عمل تجريبي يجمع الخط والعمارة.'}});stamp('Editorial');
  await login('General_Exhibition_Coordinator');
  let view=await dossier();assert.equal((await call('/api/review/spatial',{version:view.version,action:'save_layout',placements:[{artwork_id:PILOT_ARTWORK,x_cm:550,y_cm:0}]})).status,409);rejected++;
  await json('/api/review/spatial',{version:view.version,action:'save_layout',placements:[{artwork_id:PILOT_ARTWORK,x_cm:20,y_cm:20}]});
  await json('/api/review/ecosystem/ready',await cmd());await action('agreement');stamp('Layout and agreement');
  await login('Artist');await action('accept');
  await login('PR');await action('pr');await login('Technical');await action('technical');
  await login('Museum_Operations');await json('/api/review/ecosystem/venue-clearance',await cmd());
  await login('Director');await json('/api/review/ecosystem/publish',await cmd());stamp('Director publication');assert.equal((await call('/api/review/ecosystem/archive-close',await cmd())).status,409);
  const label=Buffer.from(await(await call('/api/review/pilot/label.pdf')).arrayBuffer());assert.equal(label.subarray(0,5).toString(),'%PDF-');
  const blockedManifest=await call('/api/review/pilot/manifest.pdf');assert.equal(blockedManifest.status,409);const manifest=Buffer.from(await blockedManifest.arrayBuffer());assert.match(manifest.toString(),/pre-dispatch/);
  const twinUrl=new URL((await dossier()).twins[0].uri);const twin=await fetch(origin+twinUrl.pathname,{headers:{Cookie:cookie,Accept:'application/ld+json'}});assert.equal((await twin.json())['sadu:fileHash'],first.revision.media.file_hash);
  await login('Logistics');assert.equal((await call('/api/review/pilot/simulated-arrival',await cmd())).status,409);
  await login('Artist');
  await login('Logistics');
  const collectionPath='/api/review/pilot/collection/'+PILOT_ARTWORK;
  const collectionAction=async(action,extra={})=>json(collectionPath,{version:(await json(collectionPath)).version,action,...extra});
  await collectionAction('SAVE',{details:{address:'Synthetic studio 1',city:'Paris',country:'France',contact:'Test collection desk',sourceRef:'SYNTHETIC-SOURCE',timezone:'Europe/Paris',availability:{start:'2026-10-01',end:'2026-10-31'},closures:[],conflict:false}});
  await collectionAction('ACCEPT');
  await collectionAction('CONFIRM',{checked:true});await collectionAction('PLAN',{pickupDate:'2026-10-05'});
  await collectionAction('PACK',{value:'Synthetic crate',packingOwner:'Test packer',amount:0,requiresTechnical:true});
  await login('Technical');await collectionAction('TECHNICAL',{value:'TEST-TECH'});
  await login('Finance');await collectionAction('COST',{value:'TEST-COST'});
  await login('Logistics');await collectionAction('EVIDENCE',{value:'TEST-PACKING'});
  const opsPath='/api/review/pilot/operations/'+PILOT_ARTWORK;
  const packingFile=await fetch(origin+opsPath+'/evidence',{method:'POST',headers:{Cookie:cookie,Origin:origin,'Content-Type':'application/octet-stream','x-sadu-metadata':encodeURIComponent(JSON.stringify({version:(await dossier()).version,operationId:'journey-packing-upload',kind:'PACKING',name:'packing.png',source:'TEST-PACKING',sender:'Synthetic packer'}))},body:image});
  assert.equal(packingFile.status,200);const uploadedPacking=await packingFile.json();
  await json(opsPath,{version:(await dossier()).version,operationId:'journey-packing-review',action:'VERIFY_PACKING',evidenceId:uploadedPacking.evidenceId,checked:true});
  await login('Artist');
  const dispatchMeta={version:(await dossier()).version,versionHash:(await cmd()).versionHash,damaged:false,notes:'Synthetic pre-dispatch review: no damage declared.',logistics:{origin:'Fictional studio',destination:'Fictional museum loading dock',carrier:'TEST-BOOKING',handling:'Upright; padded crate',gross_weight_kg:100}};
  const dispatchUpload=await fetch(origin+'/api/review/pilot/pre-dispatch',{method:'POST',headers:{Cookie:cookie,Origin:origin,'Content-Type':'application/octet-stream','x-sadu-metadata':encodeURIComponent(JSON.stringify(dispatchMeta))},body:image});assert.equal(dispatchUpload.status,200);assert.equal(runtime.repository.read().dispatchReports.at(-1).logistics.origin,'Synthetic studio 1, Paris, France');
  assert.equal((await call('/api/review/pilot/manifest.pdf')).status,409);
  await login('General_Exhibition_Coordinator');let dispatchDossier=await dossier();
  await json('/api/review/pilot/pre-dispatch/review',{version:dispatchDossier.version,versionHash:dispatchDossier.revision.versionHash,reportId:dispatchDossier.dispatch.report.id,action:'CLEAR',reason:'Reviewed fictional photograph and declaration.'});
  const readyManifest=await call('/api/review/pilot/manifest.pdf');assert.equal(readyManifest.status,200);const manifestPdf=Buffer.from(await readyManifest.arrayBuffer());assert.equal(manifestPdf.subarray(0,5).toString(),'%PDF-');await writeFile(join(directory,'reviewed-draft-manifest.pdf'),manifestPdf);
  await login('Finance');assert.equal((await call('/api/review/pilot/action',{version:(await dossier()).version,action:'pay',tranche:2})).status,409);rejected++;
  await action('pay',{tranche:0});
  await login('Logistics');assert.equal((await call('/api/review/ecosystem/arrival',await cmd(),'PATCH')).status,409);rejected++;
  await json('/api/review/pilot/simulated-arrival',await cmd());const conditionUpload=await fetch(origin+'/api/review/ecosystem/condition',{method:'POST',headers:{Cookie:cookie,Origin:origin,'Content-Type':'application/octet-stream','x-sadu-metadata':encodeURIComponent(JSON.stringify({...await cmd(),x_pct:25,y_pct:45,description:'Fictional surface mark, reconciled before return.'}))},body:image});assert.equal(conditionUpload.status,200);
  await action('condition-clear');stamp('Synthetic receipt and condition');
  await login('Finance');await action('pay',{tranche:1});
  await login('Logistics');await action('return');await login('Finance');await action('pay',{tranche:2});stamp('Safe return and completion');
  let done=await dossier();assert.equal(done.artwork.physicalStatus,'RETURN_FREIGHT_CLEARED');assert.equal(done.payments.reduce((n,p)=>n+p.amountMinor,0),4500000);
  const staleVersion=done.version-1;assert.equal((await call('/api/review/pilot/action',{version:staleVersion,action:'pay',tranche:2})).status,409);rejected++;
  const archivePath=`/api/review/ecosystem/archive/${PILOT_ARTWORK}.pdf`;
  assert.equal((await call(archivePath)).status,403);
  await login('General_Exhibition_Coordinator');assert.equal((await call(archivePath)).status,409);
  assert.equal((await call('/api/review/ecosystem/archive-close',await cmd())).status,403);
  const actor={id:'pilot-Director',role:'Director',exhibitionId:'connected-pilot'};
  const beforeFailure=runtime.repository.read();
  const boundary=archivalRecordService({repository:runtime.repository,readObject:id=>readFile(join(directory,'objects',id))});
  assert.throws(()=>boundary.download({...actor,exhibitionId:'other'},PILOT_ARTWORK),/restricted/);
  const failing=archivalRecordService({repository:runtime.repository,readObject:id=>readFile(join(directory,'objects',id)),generate:()=>{throw new Error('PDF failure');}});
  await assert.rejects(failing.close(actor,await cmd()),/PDF failure/);assert.deepEqual(runtime.repository.read(),beforeFailure);
  await login('Director');await json('/api/review/ecosystem/archive-close',await cmd());
  const firstArchive=runtime.repository.read().archivalRecords[0];
  await json('/api/review/ecosystem/archive-close',await cmd());assert.equal(runtime.repository.read().archivalRecords.length,1);
  const archiveResponse=await call(archivePath);assert.equal(archiveResponse.status,200);
  const archivalPdf=Buffer.from(await archiveResponse.arrayBuffer());assert.equal(createHash('sha256').update(archivalPdf).digest('hex'),archiveResponse.headers.get('x-content-sha256'));
  await writeFile(join(directory,'master-archive.pdf'),archivalPdf);
  await login('General_Exhibition_Coordinator');assert.equal((await call(archivePath)).status,200);
  assert.equal((await call('/api/review/ecosystem/ready',await cmd())).status,409);
  await login('Finance');assert.equal((await call(archivePath)).status,403);
  assert.equal((await call('/api/review/pilot/action',{version:(await dossier()).version,action:'pr',checked:true})).status,409);
  done=await dossier();assert.equal(done.artwork.lifecycleStatus,'ARCHIVED_CLOSED');
  const stateBefore=await readFile(join(directory,'state.json'),'utf8');
  await new Promise(resolve=>server.close(resolve));runtime=await createConnectedPilot(options);origin=await listen();cookie='';await login('Finance');
  const recovered=await dossier();assert.deepEqual(recovered.payments,done.payments);assert.equal(recovered.decisions.length,done.decisions.length);assert.equal(await readFile(join(directory,'state.json'),'utf8'),stateBefore);stamp('Restart recovery');await login('Director');assert.deepEqual(Buffer.from(await(await call(archivePath)).arrayBuffer()),archivalPdf);assert.equal(runtime.repository.read().archivalRecords[0].snapshotHash,firstArchive.snapshotHash);
  const corrupt=structuredClone(runtime.repository.read());corrupt.archivalRecords[0].pdfBase64=Buffer.from('tampered').toString('base64');
  assert.throws(()=>archivalRecordService({repository:{read:()=>corrupt}}).download(actor,PILOT_ARTWORK),/integrity/);
  const evidence={date:'2026-09-30',directory,fictional:true,syntheticLocation:true,milestones,blockedNegativeCases:rejected,paymentsMinor:4500000,decisionCount:done.decisions.length,missingInputCasesExercised:2,externalDispatches:0,manualFollowupsObservedInScript:0,staffTimeSavings:'Not measured; no operational baseline',totalMs:Math.round(performance.now()-started)};
  await writeFile(join(directory,'pilot-evidence.json'),JSON.stringify(evidence,null,2));await writeFile(join(directory,'label.pdf'),label);await writeFile(join(directory,'manifest-gate.json'),manifest);
  console.log('PILOT_EVIDENCE '+JSON.stringify(evidence));
 }finally{if(server?.listening)await new Promise(resolve=>server.close(resolve));}
});
