import test from 'node:test';
import assert from 'node:assert/strict';
import { loadCheckpoint, saveCheckpoint } from '../src/lib/demoCheckpoint';
import { packingTransition, packingStage, collectionReadiness } from '../src/logistics/collectionRules.mjs';
import { createPublishingRecord, reducePublishingRecord as reduce, PRINT_ROUTE_ID } from '../src/data/publishingRecord';
const at='2026-10-03T12:00:00Z';
test('reported defect holds immediately; wrong or stale stop acknowledgment cannot release it',()=>{
  let s=createPublishingRecord();
  s=reduce(s,{type:'ATTACH_PRINT_PROOF',actor:'COORDINATOR',at});
  s=reduce(s,{type:'ROUTE_PRINT_PROOF',actor:'PUBLISHING_MANAGER',at,version:1,editorialChecked:true,rightsChecked:true,route:PRINT_ROUTE_ID});
  s=reduce(s,{type:'DECIDE_PRINT_PROOF',actor:'CHAIRMAN',at,version:1,outcome:'release',acknowledged:true});
  s=reduce(s,{type:'RECORD_PRINT_DISPATCH',actor:'PUBLISHING_MANAGER',at,version:1});
  s=reduce(s,{type:'ACKNOWLEDGE_PRINT_PROOF',actor:'PUBLISHING_MANAGER',at,version:1,reference:'DEMO-ACK'});
  const held=reduce(s,{type:'REQUEST_PRINT_CORRECTION',actor:'COORDINATOR',at,version:1,reason:'Wrong title',stopReference:''});
  assert.equal(held.correction?.reason,'Wrong title');
  assert.equal(reduce(held,{type:'START_PRINT',actor:'PUBLISHING_MANAGER',at,version:1}),held);
  assert.equal(reduce(held,{type:'ATTACH_PRINT_PROOF',actor:'COORDINATOR',at}),held);
  for(const action of [{actor:'COORDINATOR',version:1,reference:'stop'}, {actor:'PUBLISHING_MANAGER',version:2,reference:'stop'}, {actor:'PUBLISHING_MANAGER',version:1,reference:''}] as const) assert.equal(reduce(held,{type:'CONFIRM_PRINT_STOP',at,...action}),held);
  const stopped=reduce(held,{type:'CONFIRM_PRINT_STOP',actor:'PUBLISHING_MANAGER',at,version:1,reference:'DEMO-STOP'});
  const next=reduce(stopped,{type:'ATTACH_PRINT_PROOF',actor:'COORDINATOR',at});
  assert.equal(next.version,2);assert.equal(next.decision,null);assert.equal(next.previous[0].correction?.stopActor,'PUBLISHING_MANAGER');
});
test('shared packing policy fails closed for legacy plans, zero costs and changed plans',()=>{
  const base={details:true,conflict:false,confirmed:true,planned:true,accepted:true};
  assert.equal(collectionReadiness({...base,accepted:false,packing:null}).state,'ACCEPTANCE_REQUIRED');
  let p=packingTransition(null,{type:'PACK',value:'Custom crate, subject to specialist review',packingOwner:'Demo packer',amount:0,requiresTechnical:true},'Logistics');
  assert.equal(packingStage(p),'technical-review');
  assert.throws(()=>packingTransition(p,{type:'COST',value:'cost'},'Finance'));
  assert.throws(()=>packingTransition(p,{type:'TECHNICAL',value:'tech'},'Logistics'));
  p=packingTransition(p,{type:'TECHNICAL',value:'DEMO-TECH'},'Technical');
  p=packingTransition(p,{type:'COST',value:'DEMO-ZERO-COST'},'Finance');
  assert.equal(collectionReadiness({...base,packing:p}).state,'PACKING_EVIDENCE_REQUIRED');
  p=packingTransition(p,{type:'EVIDENCE',value:'DEMO-PHOTO'},'Logistics');
  assert.equal(collectionReadiness({...base,packing:p}).state,'READY_FOR_COLLECTION');
  assert.equal(packingTransition(p,{type:'REOPEN',value:'Crate changed'},'Logistics'),null);
  assert.equal(packingStage({costReference:'old',evidence:'old'}),'technical-review');
  assert.throws(()=>packingTransition(null,{type:'PACK',value:'Crate',packingOwner:'Packer',amount:0,requiresTechnical:false},'Logistics'));
});
test('synthetic checkpoints survive remount, isolate keys, retain corrupt data and report write failures',()=>{
  const values=new Map<string,string>(); const storage={getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>{values.set(k,v);}};
  const initial=()=>({step:0});const valid=(v:any)=>Number.isInteger(v?.step);
  assert.equal(saveCheckpoint(storage,'collection',{step:4}),'');
  assert.equal(loadCheckpoint(storage,'collection',initial,valid).value.step,4);
  assert.equal(loadCheckpoint(storage,'print',initial,valid).value.step,0);
  storage.setItem('bad','{bad');assert.match(loadCheckpoint(storage,'bad',initial,valid).warning,/could not be restored/);assert.equal(storage.getItem('bad'),'{bad');
  assert.match(saveCheckpoint({getItem:storage.getItem,setItem:()=>{throw Error('quota');}},'collection',{step:5}),/could not be saved/);
  assert.equal(loadCheckpoint(storage,'collection',initial,valid).value.step,4);
  saveCheckpoint(storage,'collection',initial());assert.equal(loadCheckpoint(storage,'collection',initial,valid).value.step,0);
});
