import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {openEcosystemRepository} from '../server/unified-ecosystem.mjs';
import {createPilotInvitations,validateInvitationSubmission} from '../server/pilot-invitations.mjs';
const hash=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
async function fixture(){
  const snapshot={proposals:[{en:'Balance',ar:'ميزان'}],selected:0,essay:{introduction:{en:'A reviewed essay',ar:'مقال معتمد'}}};
  const template={en:'Dear [Artist_Name], [Exhibition_Theme], [Assigned_Venue], [Logistics_Deadlines], [Target_Discipline].',ar:'دعوة [Artist_Name]، [Exhibition_Theme]، [Assigned_Venue]، [Logistics_Deadlines]، [Target_Discipline].',reviews:['Editorial','Finance'],version:1,policyReference:'SYNTHETIC'};
  template.hash=hash(template);
  const seed={format:1,version:0,decisions:[],artworks:[{id:'a',artistActorId:'artist',exhibitionId:'e'}],themePublications:[{id:'theme-1',snapshot,hash:hash(snapshot)}],artistCare:{template,settings:{deadline:new Date(Date.now()+86400000*30).toISOString(),commissionAllowed:false}},spatialLedger:{artworks:[{id:'a',name:'Nehad (tentative)',state:'APPROVED',galleryId:'g',assignmentVersion:1}],venues:[{id:'v',active:true}],galleries:[{id:'g',venueId:'v',active:true,name:'Gallery A'}],curation:{phase:'ENDORSED',snapshots:[{id:'roster',state:'ENDORSED',rows:[{revision:{artistId:'a'},slot:{galleryId:'g',assignedTo:'sub'}}]}]}}};
  const file=join(await mkdtemp(join(tmpdir(),'sadu-invite-')),'state.json');
  const repo=await openEcosystemRepository(file,seed),service=createPilotInvitations(repo);
  const actor=(role,id=role)=>({role,id,exhibitionId:'e'});
  const act=(role,action,data={},id)=>service.mutate(actor(role,id),{version:repo.read().version,action,...data});
  const prepare=async()=>{await act('General_Exhibition_Coordinator','SET_BRIEF',{discipline:'VIDEO_DIGITAL',routes:['EXISTING_WORK']});await act('Exhibition_Coordinator','PREVIEW',{welcome:'Welcome to the fictional exhibition.'},'sub');};
  return {repo,service,actor,act,prepare,file};
}
test('invitation snapshots use approved text; links are hashed, owned and single-use',async()=>{
  const f=await fixture();await f.prepare();
  const view=f.service.read(f.actor('Artist','artist'));
  assert.match(view.invitation.en,/Balance/);assert.match(view.invitation.ar,/ميزان/);
  assert.match(view.invitation.en,/Video \/ digital media/);
  const issued=await f.act('Exhibition_Coordinator','ISSUE_LOCAL_LINK',{},'sub');
  assert.equal(issued.delivery,'LOCAL_ONLY_NOT_SENT');
  assert.ok(!JSON.stringify(f.repo.read()).includes(issued.token));
  await assert.rejects(f.act('Artist','REDEEM',{token:issued.token,invitationId:issued.invitationId},'other'),/denied/);
  await f.act('Artist','REDEEM',{token:issued.token,invitationId:issued.invitationId},'artist');
  await assert.rejects(f.act('Artist','REDEEM',{token:issued.token,invitationId:issued.invitationId},'artist'),/already used/);
  await f.act('Artist','DECLARE_IDENTITY',{legalName:'Murat Kurt',displayNameEn:'Murat Kurt',displayNameAr:'مراد قورت'},'artist');
  assert.equal(f.repo.read().spatialLedger.artworks[0].name,'Nehad (tentative)');
  assert.equal(f.service.read(f.actor('Director')).identity.status,'SELF_DECLARED');
  assert.equal(f.service.read(f.actor('Director')).identity.legalName,undefined);
  await f.act('PR','VERIFY_IDENTITY',{evidenceReference:'Synthetic reviewed identity reference'});
  await f.act('Artist','CHOOSE_ROUTE',{route:'EXISTING_WORK'},'artist');
  assert.equal(f.repo.read().artistIdentityDeclarations.length,2);
  assert.ok(!JSON.stringify(f.repo.read().decisions).includes('Murat'));
  assert.deepEqual((await openEcosystemRepository(f.file)).read(),f.repo.read());
});
test('mandates, delivery dependencies and submission fields are server controlled',async()=>{
  const f=await fixture();
  await assert.rejects(f.act('Exhibition_Coordinator','SET_BRIEF',{discipline:'VIDEO_DIGITAL',routes:['EXISTING_WORK']},'sub'),/denied/);
  await assert.rejects(f.act('General_Exhibition_Coordinator','SET_BRIEF',{discipline:'SCULPTURE',routes:['COMMISSION']}),/does not authorize/);
  await f.prepare();
  const issued=await f.act('General_Exhibition_Coordinator','ISSUE_LOCAL_LINK');
  await f.act('Artist','REDEEM',{token:issued.token,invitationId:issued.invitationId},'artist');
  await assert.rejects(f.act('Artist','CHOOSE_ROUTE',{route:'EXISTING_WORK'},'artist'),/Declare/);
  await f.act('Artist','DECLARE_IDENTITY',{legalName:'Murat',displayNameEn:'Murat',displayNameAr:'مراد'},'artist');
  await assert.rejects(f.act('Artist','CHOOSE_ROUTE',{route:'COMMISSION'},'artist'),/not permitted/);
  await f.act('Artist','CHOOSE_ROUTE',{route:'EXISTING_WORK'},'artist');
  const body={targetDiscipline:'VIDEO_DIGITAL',participationRoute:'EXISTING_WORK',artistName:{en:'Murat',ar:'مراد'},screenWidthCm:100,screenHeightCm:60,avRequirements:'Projector, media player',existingWorkWeightKg:10,packing:'Protected transport case'};
  assert.doesNotThrow(()=>validateInvitationSubmission(f.repo.read(),f.actor('Artist','artist'),body));
  assert.throws(()=>validateInvitationSubmission(f.repo.read(),f.actor('Artist','artist'),{...body,targetDiscipline:'SCULPTURE'}),/discipline/);
  assert.throws(()=>validateInvitationSubmission(f.repo.read(),f.actor('Artist','artist'),{...body,screenWidthCm:0}),/screen/);
  await f.repo.transaction(s=>{s.spatialLedger.galleries[0].active=false;});
  assert.equal(f.service.read(f.actor('Artist','artist')).invitation.current,false);
  assert.throws(()=>validateInvitationSubmission(f.repo.read(),f.actor('Artist','artist'),body),/current invitation/);
});
test('stale commands, expired tokens and tampered templates fail closed',async()=>{
  const f=await fixture();await f.prepare();
  await assert.rejects(f.service.mutate(f.actor('General_Exhibition_Coordinator'),{version:0,action:'ISSUE_LOCAL_LINK'}),/changed/);
  const issued=await f.act('General_Exhibition_Coordinator','ISSUE_LOCAL_LINK');
  await f.repo.transaction(s=>{s.portalInvitations[0].expiresAt='2000-01-01T00:00:00Z';});
  await assert.rejects(f.act('Artist','REDEEM',{token:issued.token,invitationId:issued.invitationId},'artist'),/expired/);
  await f.repo.transaction(s=>{s.artistCare.template.en='Changed without approval';});
  await assert.rejects(f.act('General_Exhibition_Coordinator','ISSUE_LOCAL_LINK'),/dependencies changed/);
});
test('commission intake validates itemized budgets and concurrent redemption has one winner',async()=>{
  const f=await fixture();
  await f.repo.transaction(s=>{s.artistCare.settings.commissionAllowed=true;});
  await f.act('General_Exhibition_Coordinator','SET_BRIEF',{discipline:'SCULPTURE',routes:['COMMISSION']});
  await f.act('General_Exhibition_Coordinator','PREVIEW',{welcome:'A proposed commission within the approved brief.'});
  const issued=await f.act('General_Exhibition_Coordinator','ISSUE_LOCAL_LINK');
  const command={version:f.repo.read().version,action:'REDEEM',token:issued.token,invitationId:issued.invitationId};
  const results=await Promise.allSettled([f.service.mutate(f.actor('Artist','artist'),command),f.service.mutate(f.actor('Artist','artist'),command)]);
  assert.equal(results.filter(x=>x.status==='fulfilled').length,1);
  await f.act('Artist','DECLARE_IDENTITY',{legalName:'Murat',displayNameEn:'Murat',displayNameAr:'مراد'},'artist');
  await f.act('Artist','CHOOSE_ROUTE',{route:'COMMISSION'},'artist');
  const body={targetDiscipline:'SCULPTURE',participationRoute:'COMMISSION',artistName:{en:'Murat',ar:'مراد'},productionBudgetLines:[{description:'Materials',amountMinor:10000}]};
  assert.doesNotThrow(()=>validateInvitationSubmission(f.repo.read(),f.actor('Artist','artist'),body));
  assert.throws(()=>validateInvitationSubmission(f.repo.read(),f.actor('Artist','artist'),{...body,productionBudgetLines:[]}),/itemized/);
  await f.repo.transaction(s=>{s.artistCare.settings.commissionAllowed=false;});
  assert.equal(f.service.read(f.actor('Artist','artist')).invitation.current,false);
});
