import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createConnectedPilot, PILOT_ARTWORK } from '../server/connected-pilot.mjs';
import { openEcosystemRepository } from '../server/unified-ecosystem.mjs';
import { createCollectionService, requireCollectionReady } from '../server/pilot-collection.mjs';

test('collection HTTP workflow: closure blocks, source confirmation, scoped backup, stale edits and recovery',async()=>{
  const directory=await mkdtemp(join(tmpdir(),'sadu-collection-'));
  const runtime=await createConnectedPilot({directory,gate:(_q,_r,next)=>next()});
  const server=runtime.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
  const origin=`http://127.0.0.1:${server.address().port}`,path='/api/review/pilot/collection/'+PILOT_ARTWORK;let cookie='';
  const call=(url,body)=>fetch(origin+url,{method:body?'POST':'GET',headers:{Cookie:cookie,Origin:origin,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
  const login=async id=>{const r=await call('/api/review/session',{accountId:'pilot-'+id});assert.equal(r.status,200);cookie=r.headers.get('set-cookie').split(';')[0];};
  const read=async()=>{const r=await call(path);assert.equal(r.status,200);return r.json();};
  const mutate=async(action,extra={},expected=200)=>{const v=await read();const command={version:v.version,action,...extra};if(expected===200&&['SAVE','PLAN','REOPEN'].includes(action)){const p=await call(path+'/impact',command);assert.equal(p.status,200);const impact=await p.json();if(impact.required)command.impactToken=impact.token;}const r=await call(path,command);const b=await r.json();assert.equal(r.status,expected,JSON.stringify(b));return b;};
  const acceptRenewal=async(key,owner)=>{
    const previousCookie=cookie;await login('General_Exhibition_Coordinator');
    const op='/api/review/pilot/operations/'+PILOT_ARTWORK;
    const view=await(await call(op)).json(),task=view.renewals.filter(c=>!c.supersededAt).flatMap(c=>c.tasks).find(t=>t.key===key);
    let r=await call(op,{action:'ASSIGN_RENEWAL',version:view.version,operationId:crypto.randomUUID(),taskId:task.id,ownerId:'pilot-'+owner,dueAt:new Date(Date.now()+86400000).toISOString(),reason:'Test renewal handoff'});assert.equal(r.status,200,await r.text());
    cookie=previousCookie;const next=await(await call(op)).json();r=await call(op,{action:'ACCEPT_RENEWAL',version:next.version,operationId:crypto.randomUUID(),taskId:task.id});assert.equal(r.status,200,await r.text());
  };
  const details={address:'Synthetic gallery collection store',city:'Paris',country:'France',contact:'Synthetic gallery desk',sourceRef:'TEST-EMAIL-01',timezone:'Europe/Paris',availability:{start:'2026-07-01',end:'2026-09-15'},closures:[{start:'2026-07-25',end:'2026-09-02'}],conflict:false};
  try {
    assert.equal((await call(path)).status,401);
    await login('Artist');assert.equal((await call(path)).status,403);
    await login('Logistics');
    assert.match((await read()).blocker,/physical collection/);
    await mutate('PLAN',{pickupDate:'2026-07-24'},409);
    await mutate('SAVE',{details:{...details,address:''}},422);
    await mutate('SAVE',{details:{...details,availability:{start:'2026-02-30',end:'2026-09-15'}}},422);
    await mutate('SAVE',{details:{...details,timezone:'Unknown/Place'}},422);
    await mutate('SAVE',{details:{...details,conflict:true}});
    await mutate('CONFIRM',{checked:true},409);
    await mutate('SAVE',{details});await mutate('ACCEPT');await mutate('PLAN',{pickupDate:'2026-07-24'},409);
    await acceptRenewal('source','Logistics');await mutate('CONFIRM',{checked:true});await acceptRenewal('pickup','Logistics');
    const confirmed=runtime.repository.read();
    for(const pickupDate of ['2026-07-25','2026-08-10','2026-09-02'])await mutate('PLAN',{pickupDate},409);
    assert.deepEqual(runtime.repository.read(),confirmed,'Failed plans must not change history or confirmations');
    await mutate('PLAN',{pickupDate:'2026-09-16'},422);
    await mutate('PLAN',{pickupDate:'2026-07-24'});
    assert.equal((await read()).ready,false);
    await acceptRenewal('plan','Logistics');await mutate('PACK',{value:'Crate',packingOwner:'Synthetic packer',amount:0,requiresTechnical:false,technicalReason:'Standard packing reviewed against the recorded rider.'});
    await login('Finance');await acceptRenewal('cost','Finance');await mutate('COST',{value:'TEST-COST'});
    await login('Logistics');await acceptRenewal('packing','Logistics');await mutate('EVIDENCE',{value:'TEST-PACKED'});
    assert.equal((await read()).ready,true);
    assert.equal(requireCollectionReady(runtime.repository.read(),PILOT_ARTWORK).country,'France');
    const staleVersion=(await read()).version;
    await mutate('SAVE',{details:{...details,address:'Revised synthetic collection store'}});
    assert.equal((await read()).record.confirmation,null);assert.equal((await read()).record.plan,null);
    assert.throws(()=>requireCollectionReady(runtime.repository.read(),PILOT_ARTWORK),{status:409});
    assert.equal((await call(path,{version:staleVersion,action:'CONFIRM',checked:true})).status,409);
    await login('Logistics-Backup');await mutate('CONFIRM',{checked:true},403);
    const backupQueue=await(await call('/api/review/pilot')).json();assert.ok(!backupQueue.nextActions.some(t=>t.href==='#collection-plan'));
    await login('General_Exhibition_Coordinator');
    await mutate('ASSIGN',{primaryId:'pilot-Logistics',backupId:'pilot-Finance',activeId:'pilot-Finance',reason:'Invalid role'},422);
    await mutate('ASSIGN',{primaryId:'pilot-Logistics',backupId:'pilot-Logistics-Backup',activeId:'pilot-Logistics-Backup',reason:'Primary officer absent; local rehearsal handover.'});
    await mutate('CONFIRM',{checked:true},403);
    await login('Logistics');await mutate('CONFIRM',{checked:true},403);
    await login('Logistics-Backup');
    const queue=await(await call('/api/review/pilot')).json();assert.ok(queue.nextActions.some(t=>t.href==='#collection-plan'&&t.ownerId==='pilot-Logistics-Backup'));
    await mutate('CONFIRM',{checked:true},409);await mutate('ACCEPT');
    await acceptRenewal('source','Logistics-Backup');await mutate('CONFIRM',{checked:true});await acceptRenewal('pickup','Logistics-Backup');await mutate('PLAN',{pickupDate:'2026-09-03'});
    await acceptRenewal('plan','Logistics-Backup');await mutate('PACK',{value:'Revised crate',packingOwner:'Synthetic packer',amount:50,requiresTechnical:true});
    await login('Technical');await acceptRenewal('technical','Technical');await mutate('TECHNICAL',{value:'TEST-TECH'});
    await login('Finance');await acceptRenewal('cost','Finance');await mutate('COST',{value:'TEST-COST-2'});
    await login('Logistics-Backup');await acceptRenewal('packing','Logistics-Backup');await mutate('EVIDENCE',{value:'TEST-PACKED-2'});
    const state=runtime.repository.read();
    assert.deepEqual(state.payments,[]);assert.equal(state.artworks[0].physicalStatus,'Pending_Shipment');
    assert.equal(state.collectionHandovers[0].enteredBy,'pilot-General_Exhibition_Coordinator');
    assert.doesNotMatch(JSON.stringify(state.decisions),/Synthetic gallery|Revised synthetic|TEST-EMAIL/);
    assert.ok([403,409].includes((await call('/api/review/pilot/action',{version:state.version,action:'pay',tranche:0})).status));
    assert.deepEqual(runtime.repository.read().payments,[]);
    assert.equal((await call('/api/review/pilot/collection/not-an-artwork')).status,403);
    const reopened=await openEcosystemRepository(join(directory,'state.json'));
    assert.deepEqual(reopened.read(),runtime.repository.read());
    assert.equal(requireCollectionReady(reopened.read(),PILOT_ARTWORK).plan.state,'PLANNED_ONLY');
  } finally {await new Promise(r=>server.close(r));}
});

test('collection changes are per artwork, atomic under concurrent updates, and frozen after custody',async()=>{
  const seed={format:1,version:0,artworks:['a','b'].map(id=>({id,exhibitionId:'x',physicalStatus:'Pending_Shipment'})),decisions:[]};
  const repository=await openEcosystemRepository(join(await mkdtemp(join(tmpdir(),'sadu-collection-race-')),'state.json'),seed);
  const actor={id:'pilot-Logistics',role:'Logistics',exhibitionId:'x'};
  const service=createCollectionService(repository,[actor]);
  const command={artworkId:'a',version:0,action:'SAVE',details:{address:'A',city:'Paris',country:'France',contact:'Desk',sourceRef:'TEST',timezone:'Europe/Paris',availability:{start:'2026-10-01',end:'2026-10-20'},closures:[],conflict:false}};
  const results=await Promise.allSettled([service.mutate(actor,command),service.mutate(actor,command)]);
  assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
  assert.equal(service.read(actor,'b').record,null);
  await repository.transaction(s=>{s.artworks[0].physicalStatus='On_Site_Sharjah';});
  await assert.rejects(service.mutate(actor,{...command,version:repository.read().version}),{status:409});
});
