import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { ACCOUNTS, ROLES, initialReview as emptyReview, projectReview, transitionReview, openReviewStore } from '../server/review-store.mjs';
import { createRehearsalApp } from '../server/rehearsal-server.mjs';

const [artist, coordinator, director] = ACCOUNTS;
const label = { artistName: 'Fictional Artist', width_cm: 80, height_cm: 120, year: 2026 };
const initialReview = () => { const state = emptyReview(); state.revisions[0].content.label = { ...label }; return state; };
const command = (state, action, extra = {}) => ({ action, version: state.version, revision: state.revisions.at(-1).number, ...extra });
const act = (state, actor, action, extra = {}) => transitionReview(state, actor, command(state, action, extra));
const error = code => e => e.status === code;
test('new local accounts omit HIP and enforce role and assignment boundaries', () => {
  assert.deepEqual(ROLES, ['Artist', 'General_Exhibition_Coordinator', 'Director']);
  const state = initialReview();
  assert.throws(() => act(state, director, 'submit'), error(403));
  assert.throws(() => act(state, { ...artist, artistId: 'someone-else' }, 'submit'), error(403));
  assert.throws(() => projectReview(state, { ...coordinator, exhibitionId: 'another-show' }), error(403));
  assert.throws(() => projectReview(state, { ...coordinator, role: 'HIP' }), error(403));
  assert.equal(projectReview(state, director).revisions.length, 0);
});
test('critique creates an editable new revision, preserves submitted text and routes alerts', () => {
  let state = act(initialReview(), artist, 'submit');
  assert.equal(projectReview(state, coordinator).alerts.filter(a => !a.resolved).length, 1);
  assert.throws(() => act(state, coordinator, 'request_revision', { note: ' ' }), error(422));
  const original = structuredClone(state.revisions[0].content);
  state = act(state, coordinator, 'request_revision', { note: 'Explain the mounting concept.' });
  assert.equal(state.revisions.length, 2);
  assert.equal(state.revisions[1].number, 2);
  assert.equal(projectReview(state, artist).alerts[0].message, 'Explain the mounting concept.');
  state = act(state, artist, 'save', { content: { title: 'Revised bronze', concept: 'A revised concept with mounting notes.', label } });
  assert.deepEqual(state.revisions[0].content, original);
  assert.equal(projectReview(state, director).revisions.length, 0);
  state = act(state, artist, 'submit');
  assert.equal(projectReview(state, artist).alerts.filter(a => !a.resolved).length, 0);
  assert.equal(state.revisions[1].status, 'Coordinator_Review');
});
test('only current coordinator review reaches Director; only Director queues the exact frozen public snapshot', () => {
  let state = act(initialReview(), artist, 'submit');
  assert.throws(() => act(state, director, 'publish', { note: 'Skip coordinator' }), error(409));
  assert.equal(projectReview(state, director).revisions.length, 0);
  state = act(state, coordinator, 'ready', { note: 'Fictional record reviewed.' });
  assert.equal(projectReview(state, director).revisions.length, 1);
  assert.throws(() => act(state, coordinator, 'publish', { note: 'Wrong role' }), error(403));
  assert.throws(() => act(state, artist, 'save', { content: { title: 'Changed', concept: 'Changed' } }), error(409));
  const before = structuredClone(state);
  state = act(state, director, 'publish', { note: 'Approved for the fictional queue.' });
  assert.equal(state.outbox.length, 1);
  assert.equal(state.outbox[0].syncStatus, 'Pending_Sync');
  assert.equal(state.outbox[0].delivery, 'Paused');
  assert.deepEqual(Object.keys(state.outbox[0].payload).sort(), ['artistId','concept','revision','title']);
  assert.equal(state.outbox[0].payload.concept, before.revisions[0].content.concept);
  assert.equal(state.outbox[0].approvalId, state.events.at(-1).id);
  assert.throws(() => transitionReview(state, director, command(before, 'publish', { note: 'Retry' })), error(409));
  assert.throws(() => act(state, director, 'publish', { note: 'Duplicate' }), error(409));
});
test('stale commands and browser role fields cannot bypass server checks', () => {
  const state = initialReview(); const submitted = act(state, artist, 'submit');
  assert.throws(() => transitionReview(submitted, coordinator, command(state, 'ready', { note: 'Stale' })), error(409));
  assert.throws(() => act(submitted, artist, 'ready', { role: 'General_Exhibition_Coordinator', actorId: coordinator.id, note: 'Forged' }), error(403));
  assert.throws(() => act(submitted, coordinator, 'ready', { note: '' }), error(422));
});
test('durable store survives reopen and serializes competing approvals', async () => {
  const folder = await mkdtemp(join(tmpdir(), 'sadu-review-test-')); const file = join(folder, 'state.json');
  const store = await openReviewStore(file);
  let record = store.read(artist);
  await store.act(artist, { action: 'save', version: record.version, revision: 1, content: { ...record.revisions[0].content, label } });
  record = store.read(artist);
  await store.act(artist, { action: 'submit', version: record.version, revision: 1 });
  record = store.read(coordinator);
  await store.act(coordinator, { action: 'ready', version: record.version, revision: 1, note: 'Reviewed.' });
  record = store.read(director);
  const publish = { action: 'publish', version: record.version, revision: 1, note: 'Approved.' };
  const results = await Promise.allSettled([store.act(director, publish), store.act(director, publish)]);
  assert.equal(results.filter(r => r.status === 'fulfilled').length, 1);
  const reopened = await openReviewStore(file);
  assert.equal(reopened.read(director).outbox.length, 1);
  const saved = JSON.parse(await readFile(file, 'utf8'));
  assert.equal(saved.revisions[0].status, 'Publication_Approved');
  assert.equal(saved.events.at(-1).actorId, director.id);
});
test('HTTP sessions reject absent identity, cross-origin writes, HIP and forged roles', async t => {
  const folder = await mkdtemp(join(tmpdir(), 'sadu-review-http-'));
  const app = await createRehearsalApp({ prelaunchGate: (_req, _res, next) => next(),  file: join(folder, 'state.json'), staticRoot: folder });
  const server = await new Promise(resolve => { const s = app.listen(0, '127.0.0.1', () => resolve(s)); });
  t.after(() => new Promise(resolve => server.close(resolve)));
  const origin = `http://127.0.0.1:${server.address().port}`;
  const request = (path, body, cookie, source = origin) => fetch(`${origin}/api/review/${path}`, { headers: { 'Content-Type': 'application/json', Origin: source, ...(cookie ? { Cookie: cookie } : {}) }, ...(body ? { method: 'POST', body: JSON.stringify(body) } : {}) });
  assert.equal((await request('record')).status, 401);
  assert.equal((await request('session', { accountId: artist.id }, null, 'https://untrusted.example')).status, 403);
  assert.equal((await request('session', { accountId: 'HIP' })).status, 403);
  let response = await request('session', { accountId: artist.id });
  assert.equal(response.status, 200);
  const cookie = response.headers.get('set-cookie').split(';')[0];
  assert.match(response.headers.get('set-cookie'), /HttpOnly/);
  response = await request('action', { action: 'submit', version: 0, revision: 1 }, cookie);
  assert.equal(response.status, 200);
  response = await request('action', { action: 'ready', version: 1, revision: 1, actorId: coordinator.id, role: coordinator.role, note: 'Forged' }, cookie);
  assert.equal(response.status, 403);
  const session = await request('session', { accountId: director.id });
  const directorCookie = session.headers.get('set-cookie').split(';')[0];
  const view = await (await request('record', null, directorCookie)).json();
  assert.equal(view.revisions.length, 0);
});

test('Director projection identifies historical approval and resolves superseded review alerts', () => {
 let state=act(initialReview(),artist,'submit');
 state=act(state,coordinator,'ready',{note:'Ready for review'});
 assert.equal(projectReview(state,director).alerts.filter(a=>!a.resolved).length,1);
 state=act(state,coordinator,'request_revision',{note:'Correct the submitted details'});
 assert.equal(projectReview(state,director).alerts.filter(a=>!a.resolved).length,0);
 state=act(state,artist,'submit');state=act(state,coordinator,'ready',{note:'Ready again'});
 state=act(state,director,'publish',{note:'Approved'});state=act(state,coordinator,'amend',{note:'New revision needed'});
 const view=projectReview(state,director);
 assert.equal(view.currentRevision,3);assert.equal(view.revisions.find(r=>r.number===view.currentRevision),undefined);
 assert.equal(view.revisions[0].number,2);assert.equal(view.revisions[0].status,'Publication_Approved');
});
