import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Readable, Writable } from 'node:stream';
import { emptyEcosystem, openEcosystemRepository, createEcosystemControllers } from '../server/unified-ecosystem.mjs';
const actor = role => ({ id: role, role, exhibitionId: 'expo' });
async function fixture() {
  const seed = emptyEcosystem();
  seed.artworks.push({ id: 'art', exhibitionId: 'expo', artistActorId: 'Artist', physicalStatus: 'In_Transit' });
  seed.walls.push({ id: 'wall', exhibitionId: 'expo', max_width_cm: 500, max_height_cm: 300 });
  seed.dictionary.push({ id: 'term', exhibitionId: 'expo', english: 'calligraphy', arabic: 'خط', version: 1, approvedBy: 'editor', approvedAt: '2026-01-01' });
  const file = join(await mkdtemp(join(tmpdir(), 'sadu-unified-')), 'state.json');
  const repository = await openEcosystemRepository(file, seed);
  const storage = { openStaging: async () => ({ objectId: 'private-object', stream: new Writable({ write(_c,_e,done) { done(); } }) }) };
  return { repository, file, controller: createEcosystemControllers({ repository, storage, dockPolicy: { latitude: 0, longitude: 0, radiusMetres: 200 }, endpointOrigin: 'http://127.0.0.1:3013' }) };
}
const submission = { artworkId: 'art', expectedRevisionId: null, artistName: { en: 'Sample Artist', ar: 'فنان' }, title: { en: 'Calligraphy Study', ar: 'دراسة' }, heritage:{applicability:'NOT_APPLICABLE',reason:'Synthetic contemporary artwork outside the heritage programme.'},concept_text: 'Calligraphy and architecture explore bronze and space.', width_cm: 100, height_cm: 100, year: 2026, technicalRequirements: [{ item: 'Projector', quantity: 2, external: true }] };
test('complete intake → translation → placement/SLA → receiving → publication links one revision', async () => {
  const { controller: c, repository, file } = await fixture();
  const r = await c.submitArtwork(actor('Artist'), submission, Readable.from([Buffer.from('image bytes')]));
  assert.match(r.media.file_hash, /^[a-f0-9]{64}$/); assert.equal(r.Arabic_Terms[0].status, 'SUGGESTED');
  const e = await c.approveEditorial(actor('Editorial'), { artworkId: 'art', versionHash: r.versionHash, description: { en: 'Verified description', ar: 'وصف' } });
  const command = { artworkId: 'art', versionHash: e.versionHash };
  await assert.rejects(c.publish(actor('Director'), command), { status: 409 });
  const placed = await c.placeArtwork(actor('General_Exhibition_Coordinator'), { ...command, wallId: 'wall', x_cm: 10, y_cm: 10 });
  assert.equal(placed.allocationRequests[0].state, 'QUEUED_PAUSED');
  await c.placeArtwork(actor('General_Exhibition_Coordinator'), { ...command, wallId: 'wall', x_cm: 20, y_cm: 10 });
  assert.equal(repository.read().requests.length, 1);
  await assert.rejects(c.receiveCrate(actor('Logistics'), command), { status: 409 });
  await c.receiveCrate(actor('Logistics'), { ...command, location: { latitude: 0, longitude: 0, accuracy: 10, timestamp: Date.now() } });
  assert.doesNotMatch(JSON.stringify(repository.read().decisions), /latitude|longitude/);
  await c.readyForDirector(actor('General_Exhibition_Coordinator'), command);
  const output = await c.publish(actor('Director'), command);
  assert.equal(output.twin.document['sadu:fileHash'], r.media.file_hash);
  assert.equal(output.twin.document['@id'], output.twin.uri);
  const pdf = Buffer.from(output.label.pdfBase64, 'base64'); assert.match(pdf.toString('latin1'), /^%PDF/);
  assert.equal((await c.publish(actor('Director'), command)).twin.id, output.twin.id);
  assert.equal(c.getTwin(actor('Editorial'), output.twin.id)['@type'], 'VisualArtwork');
  assert.throws(() => c.getTwin({ ...actor('Director'), exhibitionId: 'other' }, output.twin.id), { status: 403 });
  assert.equal((await openEcosystemRepository(file)).read().twins.length, 1);
});
test('invalid geometry, stale versions and forged roles cannot mutate the pipeline', async () => {
  const { controller: c, repository } = await fixture();
  const r = await c.submitArtwork(actor('Artist'), submission, Readable.from([Buffer.from('bytes')]));
  const cmd = { artworkId: 'art', versionHash: r.versionHash, wallId: 'wall', x_cm: 450, y_cm: 0 };
  await assert.rejects(c.placeArtwork(actor('General_Exhibition_Coordinator'), cmd), { status: 409 });
  assert.equal(repository.read().requests.length, 0); assert.equal(repository.read().placements.length, 0);
  await assert.rejects(c.publish(actor('Artist'), cmd), { status: 403 });
  await assert.rejects(c.readyForDirector(actor('General_Exhibition_Coordinator'), { ...cmd, versionHash: 'stale' }), { status: 409 });
  await assert.rejects(c.submitArtwork(actor('Artist'), submission, Readable.from([Buffer.from('another')])), { status: 409 });
});
test('conservation clearance and image-bound condition records respect roles and revisions', async () => {
  const { controller:c, repository } = await fixture();
  await repository.transaction(s => { s.walls[0].climateCapability={lux:40,min_temp_c:18,max_temp_c:22,min_humidity_pct:35,max_humidity_pct:45}; });
  const r=await c.submitArtwork(actor('Artist'),{...submission,conservation_reqs:{max_lux:50,target_temp_c:20,target_humidity_pct:40}},Readable.from([Buffer.from('master')]));
  const e=await c.approveEditorial(actor('Editorial'),{artworkId:'art',versionHash:r.versionHash,description:{en:'Approved',ar:'معتمد'}});
  const cmd={artworkId:'art',versionHash:e.versionHash};
  await c.placeArtwork(actor('General_Exhibition_Coordinator'),{...cmd,wallId:'wall',x_cm:0,y_cm:0});
  await c.readyForDirector(actor('General_Exhibition_Coordinator'),cmd);
  await assert.rejects(c.publish(actor('Director'),cmd),{status:409});
  await assert.rejects(c.clearVenue(actor('Director'),cmd),{status:403});
  await c.clearVenue(actor('Museum_Operations'),cmd);
  const pin=await c.recordCondition(actor('Logistics'),{...cmd,x_pct:20,y_pct:80,description:'Sample scratch'},Readable.from([Buffer.from('damage photo')]));
  assert.equal(pin.referenceImageHash,r.media.file_hash);assert.equal(pin.revisionId,r.id);assert.match(pin.photo.file_hash,/^[a-f0-9]{64}$/);
  await c.publish(actor('Director'),cmd);
  assert.equal(c.museumView(actor('Director'),'art').pins.length,1);
  assert.doesNotMatch(JSON.stringify(repository.read().twins),/Sample scratch|damage photo/);
});

test('heritage registry, artist revisions and artwork assertions enforce scope and preserve evidence', async()=>{
 const {controller:c,repository}=await fixture();
 await assert.rejects(c.registerSocialActor(actor('Artist'),{artworkId:'art',kind:'Institution',name:{en:'Demo',ar:'تجريبي'}}),{status:403});
 const social=await c.registerSocialActor(actor('General_Exhibition_Coordinator'),{artworkId:'art',kind:'Institution',name:{en:'Synthetic craft school',ar:'مدرسة تجريبية'}});
 const heritage={applicability:'APPLICABLE',transmission_method:'FORMAL_TRAINING',safeguarding_measure:['DOCUMENTATION','CAPACITY_BUILDING'],material_provenance:'MIXED_MEDIA',social_actors:[social.id]};
 const profile=await c.recordArtistHeritage(actor('Artist'),{artworkId:'art',expectedRevisionId:null,heritage});
 await assert.rejects(c.recordArtistHeritage(actor('Artist'),{artworkId:'art',expectedRevisionId:null,heritage}),{status:409});
 const r=await c.submitArtwork(actor('Artist'),{...submission,heritage},Readable.from([Buffer.from('bytes')]));
 assert.equal(r.heritage.transmission_method,'FORMAL_TRAINING');
 assert.equal(repository.read().artistHeritageRevisions[0].versionHash,profile.versionHash);
 const output=c.assertion(actor('General_Exhibition_Coordinator'),'art');assert.equal(output.version_hash,r.versionHash);assert.equal(output.compliance_determination,'NOT_ASSESSED');
 assert.throws(()=>c.assertion(actor('Logistics'),'art'),{status:403});
 assert.ok(!JSON.stringify(repository.read().decisions).includes('Synthetic craft school'));
 await assert.rejects(c.submitArtwork(actor('Artist'),{...submission,expectedRevisionId:r.id,heritage:undefined},Readable.from([Buffer.from('bad')])),{status:422});
});
