import { prelaunchCopy } from '../src/i18n/prelaunch.mjs';

export const lockPage = `<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${prelaunchCopy.ar.title}</title>
<style>body{margin:0;min-block-size:100svh;display:grid;place-items:center;background:#F7F1E6;color:#111817;font:16px/1.6 system-ui}main{inline-size:min(360px,85vw);text-align:center;padding-block:24px}h1{letter-spacing:.1em}input,button{box-sizing:border-box;inline-size:100%;padding:14px;font:inherit;margin-block-start:12px;border:1px solid #111817;border-radius:4px;min-block-size:48px}button{background:#111817;color:#F7F1E6;cursor:pointer}button:disabled{opacity:.6}button:focus-visible,input:focus-visible{outline:3px solid #8b4513;outline-offset:3px}#language{inline-size:auto;background:transparent;color:#111817;margin-block:0 24px}label{display:block;text-align:start}#error{min-block-size:2em}small{display:block}</style>
<main><button id="language" type="button" lang="en">English</button><small data-copy="institution">${prelaunchCopy.ar.institution}</small><h1><span lang="ar">سدو</span> · <span lang="en">SADU</span></h1><p data-copy="introduction">${prelaunchCopy.ar.introduction}</p><form><label for="password" data-copy="password">${prelaunchCopy.ar.password}</label><input id="password" type="password" dir="ltr" autocomplete="current-password" required maxlength="256"><button type="submit" data-copy="submit">${prelaunchCopy.ar.submit}</button><p id="error" role="status" aria-live="polite"></p></form><small data-copy="disclaimer">${prelaunchCopy.ar.disclaimer}</small></main>
<script>
const copy=${JSON.stringify(prelaunchCopy)};let language='ar',errorKey='',busy=false;
const button=document.querySelector('button[type="submit"]'),languageButton=document.querySelector('#language');
function render(){const text=copy[language];document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';document.title=text.title;document.querySelectorAll('[data-copy]').forEach(el=>el.textContent=text[el.dataset.copy]);button.textContent=busy?text.checking:text.submit;languageButton.textContent=language==='ar'?'English':'العربية';languageButton.lang=language==='ar'?'en':'ar';document.querySelector('#error').textContent=errorKey?text[errorKey]:'';}
languageButton.addEventListener('click',()=>{language=language==='ar'?'en':'ar';render();});
document.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();busy=true;errorKey='';button.disabled=true;render();try{const r=await fetch('/api/prelaunch/unlock',{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(10000),body:JSON.stringify({password:document.querySelector('input').value})});if(r.ok){location.reload();return}errorKey=r.status===429?'rateLimit':r.status===503?'unconfigured':'unlockError';}catch{errorKey='connectionError';}document.querySelector('input').value='';busy=false;button.disabled=false;render();});
</script></html>`;
