-- Integration blueprint, isolated from the existing public prototype tables.
-- No browser grants; expose only through an authenticated server adapter after review.
begin;
create schema sadu_governance;
revoke all on schema sadu_governance from public,anon,authenticated;
create type sadu_governance.role as enum ('ADMIN','COORDINATOR','PR_OFFICER','LOGISTICS_OFFICER','EXTERNAL_VENDOR','ARTIST','EDITORIAL','DIRECTOR','FINANCE');
create table sadu_governance.programs(id uuid primary key default gen_random_uuid(),name text not null,starts_on date not null,ends_on date not null check(ends_on>=starts_on));
create table sadu_governance.memberships(program_id uuid references sadu_governance.programs,user_id uuid references auth.users,role sadu_governance.role not null,active boolean not null default true,primary key(program_id,user_id,role));
create table sadu_governance.artist_profiles(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references auth.users,legal_name text not null,biography jsonb not null default '{}',nationality_code text not null check(nationality_code ~ '^[A-Z]{2}$'),revision int not null default 1 check(revision>0));
create table sadu_governance.participations(id uuid primary key default gen_random_uuid(),program_id uuid not null references sadu_governance.programs,artist_id uuid not null references sadu_governance.artist_profiles,coordinator_id uuid not null references auth.users,approved_artwork_count int check(approved_artwork_count>0),status text not null default 'DRAFT' check(status in ('DRAFT','SUBMITTED','READY_FOR_PRINT','ARCHIVED')),arrival date,unique(program_id,artist_id));
-- Store private object references and encryption metadata, never plaintext identity data or keys.
create table sadu_governance.document_vault(id uuid primary key default gen_random_uuid(),artist_id uuid not null references sadu_governance.artist_profiles,kind text not null check(kind in ('PASSPORT','NATIONAL_ID')),private_object_key text not null unique,sha256 text not null check(sha256 ~ '^[a-f0-9]{64}$'),key_reference text not null,encryption_verified_at timestamptz,scan_status text not null default 'PENDING' check(scan_status in ('PENDING','CLEAN','REJECTED')),expires_on date,uploaded_at timestamptz not null default now());
create table sadu_governance.artworks(id uuid primary key default gen_random_uuid(),participation_id uuid not null references sadu_governance.participations,reference_id text not null unique,revision int not null default 1 check(revision>0),title jsonb not null,materials jsonb not null,concept jsonb not null,height_cm numeric not null check(height_cm>0),width_cm numeric not null check(width_cm>0),depth_cm numeric not null check(depth_cm>0),production_year int not null check(production_year between 1000 and 2100),insurance_value numeric(14,2) not null check(insurance_value>=0),insurance_currency text not null check(insurance_currency in ('AED','USD','EUR')),textual_elements jsonb not null default '{}',religious_text boolean not null default false,unique(id,revision));
create table sadu_governance.artwork_assets(id uuid primary key default gen_random_uuid(),artwork_id uuid not null,artwork_revision int not null,category text not null check(category in ('CATALOG_IMAGE','VIDEO_MASTER','TECHNICAL_RIDER','BLUEPRINT')),object_key text not null unique,sha256 text not null check(sha256 ~ '^[a-f0-9]{64}$'),byte_size bigint not null check(byte_size>0 and byte_size<=2147483648),mime_type text not null,width_px int,height_px int,storage_verified_at timestamptz,scan_status text not null default 'PENDING' check(scan_status in ('PENDING','CLEAN','REJECTED')),foreign key(artwork_id,artwork_revision) references sadu_governance.artworks(id,revision));
create table sadu_governance.editorial_approvals(id uuid primary key default gen_random_uuid(),artwork_id uuid not null,artwork_revision int not null,approved_by uuid not null references auth.users,approved_at timestamptz not null default now(),source_sha256 text not null check(source_sha256 ~ '^[a-f0-9]{64}$'),bilingual_snapshot jsonb not null,unique(artwork_id,artwork_revision),foreign key(artwork_id,artwork_revision) references sadu_governance.artworks(id,revision));
create table sadu_governance.contracts(id uuid primary key default gen_random_uuid(),participation_id uuid not null references sadu_governance.participations,revision int not null check(revision>0),snapshot jsonb not null,pdf_object_key text not null,pdf_sha256 text not null check(pdf_sha256 ~ '^[a-f0-9]{64}$'),sealed_at timestamptz not null default now(),supersedes_id uuid references sadu_governance.contracts,unique(participation_id,revision));
create table sadu_governance.signature_receipts(id uuid primary key default gen_random_uuid(),contract_id uuid not null references sadu_governance.contracts,provider text not null,provider_event_id text not null unique,signer_user_id uuid not null references auth.users,pdf_sha256 text not null,webhook_verified_at timestamptz not null,signed_at timestamptz not null);
create table sadu_governance.crates(id uuid primary key default gen_random_uuid(),artwork_id uuid not null references sadu_governance.artworks,length_cm numeric not null check(length_cm>0),width_cm numeric not null check(width_cm>0),height_cm numeric not null check(height_cm>0),weight_kg numeric not null check(weight_kg>0),pickup_address jsonb not null,pickup_contact jsonb not null,insurance_value numeric(14,2) not null check(insurance_value>=0),insurance_currency text not null check(insurance_currency in ('AED','USD','EUR')));
create table sadu_governance.shipping_tickets(id uuid primary key default gen_random_uuid(),crate_id uuid not null references sadu_governance.crates,vendor_user_id uuid references auth.users,logistics_user_id uuid not null references auth.users,status text not null default 'READY_FOR_SHIPPING' check(status in ('READY_FOR_SHIPPING','ACTIONED','IN_TRANSIT','RECEIVED','CANCELLED')),ready_at timestamptz not null default now(),actioned_at timestamptz,received_at timestamptz,check(status<>'RECEIVED' or received_at is not null));
create table sadu_governance.condition_reports(id uuid primary key default gen_random_uuid(),ticket_id uuid not null references sadu_governance.shipping_tickets,registrar_id uuid not null references auth.users,condition text not null check(condition in ('INTACT','DAMAGED')),photo_object_keys text[] not null default '{}',recorded_at timestamptz not null default now(),check(condition<>'DAMAGED' or cardinality(photo_object_keys)>0));
create table sadu_governance.immigration_policies(id uuid primary key default gen_random_uuid(),version text not null unique,approved_reference text not null,valid_from date not null,valid_until date not null check(valid_until>=valid_from),passport_months int not null default 6 check(passport_months between 1 and 24),national_id_countries text[] not null default '{}',activated_at timestamptz);
create table sadu_governance.visa_decisions(id uuid primary key default gen_random_uuid(),participation_id uuid not null references sadu_governance.participations,decision text not null check(decision in ('APPROVED_BY_AUTHORITY','REJECTED_BY_AUTHORITY')),authority_reference text not null,recorded_by uuid not null references auth.users,recorded_at timestamptz not null default now());
create table sadu_governance.message_templates(id uuid primary key default gen_random_uuid(),purpose text not null,language text not null,body text not null,legal_approval_reference text,approved_at timestamptz,unique(purpose,language));
create table sadu_governance.outbox(id uuid primary key default gen_random_uuid(),dedupe_key text not null unique,kind text not null check(kind in ('SHIPPING_SLA','RECEIVED_NOTICE','VISA_DECISION','CMS_PUBLICATION')),recipient_user_id uuid references auth.users,record_id uuid not null,template_id uuid references sadu_governance.message_templates,status text not null default 'PENDING' check(status in ('PENDING','SENT','CANCELLED','FAILED')),created_at timestamptz not null default now(),delivered_at timestamptz,check(status<>'SENT' or delivered_at is not null));
create index on sadu_governance.shipping_tickets(ready_at) where status='READY_FOR_SHIPPING';
create index on sadu_governance.artworks(participation_id);
create index on sadu_governance.artwork_assets(artwork_id,artwork_revision);
create index on sadu_governance.participations(coordinator_id);
create function sadu_governance.immutable_record() returns trigger language plpgsql set search_path='' as $$begin raise exception 'Immutable receipt: create an explicit new revision';end$$;
create trigger immutable_contract before update or delete on sadu_governance.contracts for each row execute function sadu_governance.immutable_record();
create trigger immutable_signature before update or delete on sadu_governance.signature_receipts for each row execute function sadu_governance.immutable_record();
create trigger immutable_editorial before update or delete on sadu_governance.editorial_approvals for each row execute function sadu_governance.immutable_record();
-- Deny all direct browser access until narrowly scoped server/RPC adapters are installed.
do $$declare r record;begin for r in select tablename from pg_tables where schemaname='sadu_governance' loop execute format('alter table sadu_governance.%I enable row level security',r.tablename);end loop;end$$;
revoke all on all tables in schema sadu_governance from public,anon,authenticated;
revoke all on all functions in schema sadu_governance from public,anon,authenticated;
commit;
