import { trackDemoAction } from '../lib/demoReplay';
import { useEffect, useState } from 'react';
type Props={role:string;artwork?:any;versionHash?:string;onChanged:()=>Promise<void>};
export default function AcquisitionPanel({role,artwork,versionHash,onChanged}:Props){
 const [envelope,setEnvelope]=useState<any>();const [price,setPrice]=useState('');const [reference,setReference]=useState('');const [buyer,setBuyer]=useState('SDC_OWNED');const [edition,setEdition]=useState('1');const [destination,setDestination]=useState('');const [confirmed,setConfirmed]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const loadEnvelope=async()=>{const r=await fetch('/api/review/signing-envelope',{cache:'no-store'});if(r.ok)setEnvelope(await r.json());else setEnvelope(undefined);};
 useEffect(()=>{if(role==='Artist')void loadEnvelope();},[role,artwork?.acquisition?.state]);
 const q=artwork?.acquisition;
 const execute=async(action:string,body:object)=>{setBusy(true);setError('');try{const r=await fetch('/api/review/acquisition/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);trackDemoAction(action,'completed');if(role==='Artist')await loadEnvelope();else await onChanged();}catch(e){trackDemoAction(action,'blocked');setError((e as Error).message);}finally{setBusy(false);}};
 const button='rounded border ps-4 pe-4 py-2 disabled:opacity-40';
 if(role==='Artist')return envelope?<section className="rounded-xl border bg-white p-5 space-y-3"><h2>Transfer of title — signing envelope</h2><p>This separate envelope contains only the proposed title document. Local simulation; no legal signature or payment.</p><a className="underline" href={`/api/review/signing-envelope/${envelope.artworkId}.pdf`}>Download Transfer of Title draft</a><p>{envelope.state}</p><label className="block"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I reviewed this document for the fictional test.</label><button className={button} disabled={busy||!confirmed||envelope.state!=='AWAITING_ARTIST_SIGNATURE'} onClick={()=>void execute('sign',{artworkId:envelope.artworkId,documentHash:envelope.documentHash,confirm:true})}>Simulate artist signature</button><p role="alert">{error}</p></section>:null;
 if(!artwork||!['Director','General_Exhibition_Coordinator','Logistics'].includes(role))return null;
 const closed=artwork.lifecycleStatus==='ARCHIVED_CLOSED';
 return <section className="rounded-xl border bg-white p-5 space-y-3"><h2>Permanent acquisition</h2><p>Ownership: {artwork.ownership_state??'TEMPORARY_LOAN'} · Accession: {artwork.accession_number??'Not accessioned'}</p><p>Fictional acquisition records only. Real signing and museum integrations remain paused.</p>
 {!q&&role==='Director'&&!closed&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();void execute('initiate',{artworkId:artwork.id,versionHash,buyer,purchaseMinor:Math.round(Number(price)*100),priceAgreementRef:reference});}}><label className="block">Buyer<select className="block border p-2" value={buyer} onChange={e=>setBuyer(e.target.value)}><option value="SDC_OWNED">Department of Culture</option><option value="SOVEREIGN_COLLECTION">Sovereign private collection</option></select></label><label className="block">Agreed purchase price (AED)<input className="block border p-2" type="number" required min="0.01" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label className="block">Price agreement evidence reference<input className="block border p-2" required maxLength={200} value={reference} onChange={e=>setReference(e.target.value)}/></label><button className={button} disabled={busy}>Initiate acquisition</button></form>}
 {q&&<><p>{q.state} · Return freight manifest: VOID</p>{q.destination&&<p>Recorded destination: {q.destination}</p>}{role!=='Logistics'&&<a className="underline block" href={`/api/review/acquisition/${artwork.id}/title.pdf`}>Transfer of Title draft</a>}
 {role==='Director'&&q.state==='SIMULATED_ARTIST_ACCEPTED'&&<><label>Edition number<input type="number" min="1" max="999" value={edition} onChange={e=>setEdition(e.target.value)}/></label><button className={button} disabled={busy} onClick={()=>void execute('approve',{artworkId:artwork.id,documentHash:q.documentHash,year:new Date().getFullYear(),edition:Number(edition)})}>Approve simulated acquisition &amp; accession</button></>}
 {['ACQUIRED_SIMULATED','TRANSFER_ROUTED'].includes(q.state)&&!closed&&<><label className="block">Permanent destination<select className="block border p-2" value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Select destination</option>{(q.buyer==='SOVEREIGN_COLLECTION'?['H.H. Sovereign Private Collection']:['SDC Main Storage','Sharjah Art Museum']).map(d=><option key={d}>{d}</option>)}</select></label><button className={button} disabled={busy||!destination} onClick={()=>void execute('route',{artworkId:artwork.id,documentHash:q.documentHash,destination})}>Generate permanent transfer manifest</button></>}
 {q.state==='TRANSFER_ROUTED'&&<a className="underline block" href={`/api/review/acquisition/${artwork.id}/manifest.pdf`}>Download Permanent Transfer Manifest</a>}</>}
 <p role="alert">{error}</p></section>;
}
