import { useEffect, useState } from 'react';
import { LayoutTemplate, Truck, MapPin } from 'lucide-react';
import type { CommissionState } from '../types';
import type { CommissionAction } from '../data/commissionScenario';
import { EMIRATES, domesticCountry, validLayout, validPickup } from '../data/artistExecution';
import { validCrate } from '../data/installationOperations';
import { damageHold } from '../data/conditionReporting';
const panel='my-5 space-y-4 rounded border border-[#D9CEBA] bg-[#F7F1E6] ps-5 pe-5 py-5 text-start';
const field='block w-full rounded border bg-white ps-3 pe-3 py-2';
function Download({file}:{file:File}){const [url,setUrl]=useState('');useEffect(()=>{const u=URL.createObjectURL(file);setUrl(u);return()=>URL.revokeObjectURL(u);},[file]);return <a className="break-all underline" download={file.name} href={url||undefined}>{file.name}</a>;}
export function ArtistExecutionBridge({state,actor,onAction}:{state:CommissionState;actor:'ARTIST'|'TECHNICAL'|'LOGISTICS';onAction?:(a:CommissionAction)=>void}){
 const [notice,setNotice]=useState('');
 const [draft,setDraft]=useState({emirate:'Sharjah',area:'',street:'',building:'',date:'',contact:'',phone:''});
 const c=state.contracts[0];if(!c)return null;
 const blocked=damageHold(state)||['ARCHIVED_CLOSED','EXECUTIVE_IMPOUND'].includes(state.installationStatus??'')||!['ARTIST_APPROVED','LOCKED'].includes(c.status);
 const layouts=(state.layoutBlueprints??[]).filter(r=>r.contractId===c.id),pickups=(state.domesticPickups??[]).filter(r=>r.contractId===c.id);
 const activePickup=pickups.some(r=>r.revision===state.agreementRevision);
 const domestic=state.administration?.contractId===c.id&&domesticCountry(state.administration.country);
 const canPickup=!blocked&&domestic&&validCrate(c.crate)&&!activePickup&&!state.logistics&&!state.acquisition;
 const valid=validCrate(c.crate)&&validPickup({...draft,id:'validation',contractId:c.id,crate:c.crate,revision:state.agreementRevision,status:'PENDING_COLLECTION',at:new Date().toISOString()});
 return <><section className={panel}><p className="text-xs">Session rehearsal only — files and tickets are not sent to external teams or carriers.</p>
 {actor!=='LOGISTICS'&&<><h2 className="flex items-center gap-2 text-xl font-semibold"><LayoutTemplate aria-hidden="true"/>مخطط العرض وتوزيع الأعمال / Spatial Layout &amp; Scenography</h2><p>{c.artistName} · Installation ticket: {c.id} · {c.proposedWorkTitle}</p>{actor==='ARTIST'&&<label className="block border-2 border-dashed ps-4 pe-4 py-4">Upload layout — PDF, PNG, JPEG · max 20 MB<input disabled={blocked} type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(!validLayout(file)){setNotice('Choose a PDF, PNG or JPEG up to 20 MB.');return;}onAction?.({type:'upload-layout',actor:'ARTIST',contractId:c.id,id:crypto.randomUUID(),file,at:new Date().toISOString()});setNotice('Layout routed to the Technical installation ledger.');}}/></label>}{!layouts.length&&<p>No artist layout submitted yet.</p>}{layouts.map((r,i)=><article key={r.id} className="border-s-4 border-[#8B261E] ps-3 py-2"><p>{r.revision!==state.agreementRevision?'Historical — prior agreement':i===layouts.length-1?'Pinned — latest artist instructions':'Superseded layout'} · Revision {r.revision} · {r.at}</p><Download file={r.file}/></article>)}</>}
 {actor!=='TECHNICAL'&&<><h2 className="flex items-center gap-2 text-xl font-semibold"><Truck aria-hidden="true"/>طلب استلام الأعمال محلياً / Request Domestic Artwork Collection</h2>{actor==='ARTIST'&&!domestic&&<p>Domestic pickup is available when the saved collection country is UAE. Set your collection country in Bank &amp; Collection Details; nationality is not used.</p>}{actor==='ARTIST'&&domestic&&<form onSubmit={e=>{e.preventDefault();if(!canPickup||!valid)return;onAction?.({type:'request-domestic-pickup',actor:'ARTIST',input:{...draft,id:crypto.randomUUID(),contractId:c.id,at:new Date().toISOString()}});setNotice('Pickup request sent to the Logistics queue.');}}><fieldset disabled={!canPickup} className="space-y-3"><label className="block">Emirate<select className={field} value={draft.emirate} onChange={e=>setDraft(p=>({...p,emirate:e.target.value}))}>{EMIRATES.map(v=><option key={v}>{v}</option>)}</select></label>{([['area','Area'],['street','Street'],['building','Villa / Building'],['date','Requested Pickup Date'],['contact','On-Site Contact Person'],['phone','Phone Number']] as const).map(([key,label])=><label className="block" key={key}>{label}<input required maxLength={key==='phone'?25:250} type={key==='date'?'date':key==='phone'?'tel':'text'} className={field} value={draft[key]} onChange={e=>setDraft(p=>({...p,[key]:e.target.value}))}/></label>)}<button disabled={!valid} className="rounded bg-[#8B261E] ps-4 pe-4 py-2 text-white disabled:opacity-50">Submit Collection Request</button></fieldset>{!validCrate(c.crate)&&<p>Awaiting approved Stage 6 crate dimensions and weight.</p>}</form>}{pickups.map(p=><article key={p.id} className="space-y-2 rounded border bg-white ps-4 pe-4 py-4"><h3 className="font-semibold">{p.revision===state.agreementRevision?p.status:'Historical — prior agreement'} · {c.artistName}</h3><p className="flex items-center gap-2"><MapPin aria-hidden="true"/>{p.emirate} · {p.area} · {p.street} · {p.building}</p><p>{p.date} · {p.contact} · {p.phone}</p><p>Crate count: 1 (single approved crate record) · {p.crate.reference}</p><p>{p.crate.lengthCm} × {p.crate.widthCm} × {p.crate.heightCm} cm · {p.crate.grossWeightKg} kg</p><p className="text-sm">Vehicle allocation pending Logistics review. Dimensions and packed weight must be checked against fleet capacity before dispatch.</p></article>)}</>}
 <p role="status">{notice}</p></section></>;
}
