import {useRef,useState} from 'react';
import {Landmark} from 'lucide-react';
import {pilotSupabase as client} from '../lib/pilotSupabase';
import {useOperationalRows} from '../lib/useOperationalRows';
import {amountMinor,type CatalogArtwork} from '../data/catalogFreight';
export type ArtworkValue={artwork_id:string;title:string;amount_minor:number;currency:'AED'|'USD'|'EUR';purpose:'DECLARED_SALE_VALUE'|'INSURANCE_VALUE';recorded_at:string};
export function ArtworkValues({artworks,locked=false,onSaved}:{artworks?:CatalogArtwork[];locked?:boolean;onSaved?:()=>void}){
 const queue=useOperationalRows<ArtworkValue>('sadu_artwork_values');const [id,setId]=useState(''),[amount,setAmount]=useState(''),[currency,setCurrency]=useState('USD'),[purpose,setPurpose]=useState('DECLARED_SALE_VALUE'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const running=useRef(false);
 const visible=queue.rows.filter(v=>!artworks||artworks.some(a=>a.id===v.artwork_id));const minor=amountMinor(amount);
 return <section className="space-y-3 rounded border bg-[#F7F1E6] ps-4 pe-4 py-4 text-start"><h3 className="flex gap-2 text-xl"><Landmark aria-hidden="true"/>Structured Artwork Values / قيم الأعمال الفنية</h3><p>Artist-declared values only; not an acquisition price approval, grant, or disbursement. Zero is valid when intentionally declared. Recorded values are immutable. / قيم مصرح بها وليست اعتماداً مالياً.</p>{artworks&&<form className="grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();if(!client||running.current||locked||minor===null||!artworks.some(a=>a.id===id)||queue.rows.some(v=>v.artwork_id===id))return;running.current=true;setBusy(true);try{const result=await client.from('sadu_artwork_values').insert({artwork_id:id,amount_minor:minor,currency,purpose});if(result.error)setMessage('Value could not be recorded. Check ownership, draft state and existing receipt.');else{setMessage('Declared value recorded.');setAmount('');setId('');await queue.refresh();onSaved?.();}}catch{setMessage('Connection failed. Refresh before retrying.');}finally{running.current=false;setBusy(false);}}}><fieldset disabled={busy||locked} className="contents"><label>Artwork / العمل<select className="block w-full border ps-2 pe-2 py-2" value={id} onChange={e=>setId(e.target.value)}><option value="">Select artwork</option>{artworks.filter(a=>!queue.rows.some(v=>v.artwork_id===a.id)).map(a=><option key={a.id} value={a.id}>{a.source.title}</option>)}</select></label><label>Amount / القيمة<input className="block w-full border ps-2 pe-2 py-2" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Currency / العملة<select className="block w-full border ps-2 pe-2 py-2" value={currency} onChange={e=>setCurrency(e.target.value)}>{['USD','AED','EUR'].map(c=><option key={c}>{c}</option>)}</select></label><label>Value purpose / نوع القيمة<select className="block w-full border ps-2 pe-2 py-2" value={purpose} onChange={e=>setPurpose(e.target.value)}><option value="DECLARED_SALE_VALUE">Declared sale value</option><option value="INSURANCE_VALUE">Insurance value</option></select></label><button disabled={!id||minor===null||busy||locked} className="rounded border ps-3 pe-3 py-2 disabled:opacity-50">Record declared value / تسجيل القيمة</button></fieldset></form>}<p role="status">{message||queue.notice}</p>{visible.map(v=><p key={v.artwork_id}>{v.title} · {(v.amount_minor/100).toFixed(2)} {v.currency} · {v.purpose}</p>)}{[...new Set(visible.map(v=>`${v.currency}:${v.purpose}`))].map(key=><p key={key}>Total / المجموع · {key}: {(visible.filter(v=>`${v.currency}:${v.purpose}`===key).reduce((n,v)=>n+Number(v.amount_minor),0)/100).toFixed(2)}</p>)}{!artworks&&<p>Only submitted artwork dossiers are visible to authenticated Finance. Totals are separated by currency and purpose.</p>}</section>;
}
