import { useEffect, useState } from 'react';
import { ImagePlus, Lock, Unlock, Languages } from 'lucide-react';
import { useSessionDraft } from '../context/SessionDrafts';
import { rosterTransition, validArtwork, type ArtworkRoster, type ArtworkLabel, type RosterAction } from '../data/artworkRoster';
const panel='my-5 space-y-4 rounded-xl border border-[#D9CEBA] bg-[#F7F1E6] ps-5 pe-5 py-5 text-start';
const field='block w-full rounded border bg-white ps-3 pe-3 py-2';
const button='rounded border border-[#8B261E] ps-4 pe-4 py-2 text-[#8B261E] disabled:opacity-50 disabled:cursor-not-allowed';
const key='artwork-rosters:v1';
function ImageDownload({file}:{file:File}){const [url,setUrl]=useState('');useEffect(()=>{const u=URL.createObjectURL(file);setUrl(u);return()=>URL.revokeObjectURL(u);},[file]);return <a className="break-all underline" href={url||undefined} download={file.name}>{file.name}</a>;}
export function ArtworkRosterBuilder({artistId,isAr}:{artistId:string;isAr:boolean}) {
 const [all,setAll]=useSessionDraft<Record<string,ArtworkRoster>>(key,{});
 const empty:ArtworkRoster={artistId,status:'DRAFT',items:[],history:[],events:[]};
 const roster=all[artistId]??empty,locked=roster.status!=='DRAFT';
 const update=(a:RosterAction)=>setAll(p=>({...p,[artistId]:rosterTransition(p[artistId]??empty,a,'ARTIST')}));
 const edit=(id:string,patch:Partial<ArtworkLabel>)=>setAll(p=>{const s=p[artistId]??empty;return {...p,[artistId]:rosterTransition(s,{type:'edit',items:s.items.map(i=>i.id===id?{...i,...patch}:i)},'ARTIST')};});
 const t=(ar:string,en:string)=>isAr?ar:en;
 return <section className={panel}><h2 className="flex items-center gap-2 text-xl font-semibold"><Languages aria-hidden="true"/>تفاصيل الأعمال الفنية / Artwork Roster &amp; Labels</h2><p className="text-sm">{t('ملفات تجريبية فقط — محفوظة في ذاكرة الجلسة. يلزم فحص الدقة من فريق التحرير.','Sample files only — held in session memory. Editorial must inspect image resolution.')} PNG / TIFF · 50 MB max per image.</p>
 <fieldset disabled={locked} className="space-y-4">{roster.items.map((item,index)=><fieldset key={item.id} className="space-y-3 rounded border bg-white ps-4 pe-4 py-4"><legend>{t('عمل','Artwork')} {index+1}</legend>{([['titleAr','عنوان العمل بالعربية'],['titleEn','Artwork Title in English'],['year','Year of Production / سنة الإنتاج'],['medium','Medium / الخامة'],['height','Height (cm) / الارتفاع'],['width','Width (cm) / العرض'],['depth','Depth (cm) / العمق']] as const).map(([name,label])=><label key={name} className="block">{label}<input required className={field} maxLength={name==='year'?4:250} value={item[name]} onChange={e=>edit(item.id,{[name]:e.target.value})}/></label>)}<label className="block border-2 border-dashed ps-3 pe-3 py-3"><ImagePlus aria-hidden="true"/>{t('صورة عالية الدقة — PNG أو TIFF','High-resolution image — PNG or TIFF')}<input type="file" accept=".png,.tif,.tiff,image/png,image/tiff" onChange={e=>edit(item.id,{image:e.target.files?.[0]})}/></label>{item.image&&<p>{item.image.name}</p>}{!validArtwork(item)&&<p className="text-sm text-red-800">{t('أكمل العنوانين والخامة والسنة والأبعاد الموجبة وأرفق صورة صالحة.','Provide Arabic and English titles, medium, valid year, positive dimensions and a valid image.')}</p>}<button className={button} onClick={()=>update({type:'edit',items:roster.items.filter(i=>i.id!==item.id)})}>{t('إزالة من المسودة','Remove from draft')}</button></fieldset>)}<button className={button} disabled={roster.items.length>=100} onClick={()=>update({type:'edit',items:[...roster.items,{id:crypto.randomUUID(),titleAr:'',titleEn:'',year:'',medium:'',height:'',width:'',depth:''}]})}>{t('إضافة عمل','Add Artwork')}</button></fieldset>
 {!locked&&<button className={button} disabled={!roster.items.length||!roster.items.every(validArtwork)} onClick={()=>update({type:'submit',at:new Date().toISOString()})}>{t('إرسال إلى الفريق التقييمي','Submit to Curatorial')}</button>}
 {locked&&<><p role="status" className="rounded bg-emerald-50 ps-4 pe-4 py-3"><Lock aria-hidden="true"/>Your catalog data has been securely routed to the Editorial &amp; Curatorial teams. It is currently locked for review.</p><p className="text-xs">In-session rehearsal routing only. {roster.status}</p><button className={button} disabled={roster.status==='AMENDMENT_REQUESTED'} onClick={()=>update({type:'request',at:new Date().toISOString()})}><Unlock aria-hidden="true"/>طلب تعديل / Request Amendment</button>{roster.status==='AMENDMENT_REQUESTED'&&<p role="status">{t('بانتظار إذن المنسق','Awaiting Coordinator permission')}</p>}</>}
 </section>;
}
export function ArtworkRosterQueue({isAr,assignedArtistIds,coordinatorId}:{isAr:boolean;assignedArtistIds?:string[];coordinatorId?:string}){
 const [all,setAll]=useSessionDraft<Record<string,ArtworkRoster>>(key,{});
 const rows=Object.values(all).filter(r=>r.history.length&&(!assignedArtistIds||assignedArtistIds.includes(r.artistId)));
 if(!rows.length)return null;
 return <section className={panel}><h2 className="text-xl font-semibold">{isAr?'سجل ملصقات الأعمال وطلبات التعديل':'Artwork Labels & Amendment Requests'}</h2>{rows.map(r=><article key={r.artistId} className="space-y-3 border-t pt-3"><h3>{r.artistId} · {r.status}</h3>{r.history.map(v=><details key={v.revision} open={v.revision===r.history.length}><summary>Revision {v.revision} · {v.at}</summary>{v.items.map(i=><div key={i.id} className="space-y-2 border-s-4 ps-3 py-2"><p>{i.titleAr} / {i.titleEn}</p><p>{i.year} · {i.medium} · {i.height} × {i.width} × {i.depth} cm</p>{i.image&&<ImageDownload file={i.image}/>}</div>)}</details>)}{coordinatorId&&assignedArtistIds?.includes(r.artistId)&&r.status==='AMENDMENT_REQUESTED'&&<button className={button} onClick={()=>setAll(p=>{const current=p[r.artistId];const next=rosterTransition(current,{type:'unlock',at:new Date().toISOString()},'COORDINATOR',assignedArtistIds.includes(r.artistId));if(next===current)return p;return {...p,[r.artistId]:{...next,events:next.events.map((e,i)=>i===next.events.length-1?{...e,actor:coordinatorId}:e)}};})}>{isAr?'السماح بالتعديل':'Authorize Amendment'}</button>}<ul className="text-xs">{r.events.map((e,i)=><li key={i}>{e.action} · {e.actor} · {e.at}</li>)}</ul></article>)}</section>;
}
