import {useState,useRef} from 'react';
import {Type,Languages,Download} from 'lucide-react';
import {pilotSupabase as client} from '../lib/pilotSupabase';
import {useOperationalRows} from '../lib/useOperationalRows';
import {validConcept,conceptWords,labelCSV,bilingualComplete,publicText,translationFields,type CatalogArtwork,type TextMetadata} from '../data/catalogFreight';
import type {SpatialZone,ScenarioMedia} from '../data/exhibitionScenario';
export const operationalPanel='space-y-3 rounded border border-[#D9CEBA] bg-[#F7F1E6] ps-4 pe-4 py-4 text-start';
export const operationalInput='block w-full rounded border bg-[#FFFDF7] ps-3 pe-3 py-2';
export const operationalButton='rounded bg-[#8B261E] text-white ps-4 pe-4 py-2 disabled:opacity-50 disabled:cursor-not-allowed';
export function CatalogMetadataBuilder({scenarioId,zones,media,locked,beforeSave,onSaved}:{scenarioId:string;zones:SpatialZone[];media:ScenarioMedia[];locked:boolean;beforeSave:()=>Promise<void>;onSaved:()=>void}){
 const queue=useOperationalRows<CatalogArtwork>('sadu_artwork_checklist',{column:'scenario_id',value:scenarioId});
 const [file,setFile]=useState('');
 const [zone,setZone]=useState(''),[source,setSource]=useState<TextMetadata>({title:'',title_ar:'',language:'en',medium:'',concept:'',bio:''});
 const [numbers,setNumbers]=useState({production_year:'',height_cm:'',width_cm:'',weight_kg:'',crate_count:'1'}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const valid=media.some(m=>m.category!=='BLUEPRINT'&&m.object_name===file&&m.zone_id===zone)&&!queue.rows.some(r=>r.media_object_name===file)&&zones.some(z=>z.id===zone)&&source.title.trim()&&source.medium.trim()&&validConcept(source.concept)&&Object.values(numbers).every(n=>n.trim()&&Number.isFinite(Number(n))&&Number(n)>0)&&Number.isInteger(Number(numbers.production_year))&&Number(numbers.production_year)<=2100&&Number.isInteger(Number(numbers.crate_count));
 async function submit(){if(!client||busy||locked||!valid)return;setBusy(true);try{await beforeSave();const result=await client.from('sadu_artwork_checklist').insert({scenario_id:scenarioId,zone_id:zone,media_object_name:file,source,...Object.fromEntries(Object.entries(numbers).map(([k,v])=>[k,Number(v)]))});if(result.error)throw result.error;setSource({title:'',title_ar:'',language:'en',medium:'',concept:'',bio:''});setMessage('Metadata locked and routed to Editorial. Dimensions are available to Logistics now.');await queue.refresh();onSaved();}catch{setMessage('Unable to submit. Check the zone count, required fields, permissions and database connection.');}finally{setBusy(false);}}
 return <section className={operationalPanel}><h3 className="flex gap-2 text-xl"><Type aria-hidden="true"/>Catalog & Label Metadata / بيانات بطاقات الأعمال</h3><TranslationPolicy/><p>One record per artwork. Original text is retained; Editorial supplies the missing Arabic/English public text. Each record is locked on submission.</p><fieldset disabled={locked||busy} className="grid gap-3 md:grid-cols-2"><label>Spatial zone<select className={operationalInput} value={zone} onChange={e=>setZone(e.target.value)}><option value="">Select zone</option>{zones.map(z=><option key={z.id} value={z.id}>{z.name} ({queue.rows.filter(r=>r.zone_id===z.id).length}/{z.artworkCount})</option>)}</select></label><label>Uploaded artwork file<select className={operationalInput} value={file} onChange={e=>setFile(e.target.value)}><option value="">Select uploaded file</option>{media.filter(m=>m.category!=='BLUEPRINT'&&m.zone_id===zone&&!queue.rows.some(r=>r.media_object_name===m.object_name)).map(m=><option key={m.object_name} value={m.object_name}>{m.file_name}</option>)}</select></label><label>Original language<select className={operationalInput} value={source.language} onChange={e=>setSource({...source,language:e.target.value})}><option value="en">English</option><option value="fr">Français</option><option value="ar">العربية</option></select></label>{([['title','Artwork title — original / عنوان العمل'],['title_ar','Arabic title draft — Editorial will verify / العنوان العربي'],['medium','Medium & Materials / الخامات'],['concept','Concept — maximum 50 words / نبذة العمل'],['bio','Artist biography — optional / السيرة']] as const).map(([key,label])=><label key={key}>{label}<textarea className={operationalInput} maxLength={2000} value={source[key]??''} onChange={e=>setSource({...source,[key]:e.target.value})}/></label>)}<p>{conceptWords(source.concept)} / 50 words</p>{([['production_year','Year of Production / سنة الإنتاج'],['height_cm','Height (cm) / الارتفاع'],['width_cm','Width (cm) / العرض'],['weight_kg','Packed weight (kg) / الوزن المغلف'],['crate_count','Crate count / عدد الصناديق']] as const).map(([key,label])=><label key={key}>{label}<input className={operationalInput} type="number" min="0.01" step={key==='production_year'||key==='crate_count'?'1':'any'} value={numbers[key]} onChange={e=>setNumbers({...numbers,[key]:e.target.value})}/></label>)}<button type="button" className={operationalButton} disabled={!valid||busy||locked} onClick={()=>void submit()}>Submit artwork metadata / إرسال البيانات</button></fieldset><p role="status">{message||queue.notice}</p><ul>{queue.rows.map(r=><li key={r.id}>{r.source.title} · {r.translation_status} · {r.width_cm} × {r.height_cm} cm{bilingualComplete(r)&&<details><summary>Approved public text / النص المعتمد</summary>{(['ar','en'] as const).map(lang=><section key={lang} lang={lang} dir={lang==='ar'?'rtl':'ltr'}>{translationFields.map(k=><p key={k}>{publicText(r,lang)?.[k]}</p>)}</section>)}</details>}</li>)}</ul></section>;
}
export function TranslationPolicy(){return <aside className="rounded border-s-4 border-[#8B261E] bg-[#FFFDF7] ps-3 pe-3 py-3"><h3>Translation SOP / سياسة الترجمة</h3><p>Public title, materials, concept and any supplied biography require Arabic and English. / العنوان والخامات والنبذة والسيرة المقدمة تتطلب العربية والإنجليزية.</p><p>Dimensions, weights and internal flight/logistics documents do not enter Editorial’s queue. / المقاسات والأوزان ووثائق السفر الداخلية خارج قائمة الترجمة.</p></aside>;}
export function TranslationCard({row,onSaved}:{row:CatalogArtwork;onSaved:()=>void}){
 const targets=(['ar','en'] as const).filter(lang=>lang!==row.source.language);
 const [texts,setTexts]=useState<Record<'ar'|'en',TextMetadata>>({ar:row.translation_ar??{title:row.source.title_ar??'',medium:'',concept:'',bio:''},en:row.translation_en??{title:'',medium:'',concept:'',bio:''}});
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');const running=useRef(false);
 const valid=targets.every(lang=>{const t=texts[lang];return t.title.trim()&&t.medium.trim()&&validConcept(t.concept)&&(!row.source.bio?.trim()||t.bio?.trim());});
 async function approve(){if(!client||running.current||!valid)return;running.current=true;setBusy(true);
  try{const result=await client.from('sadu_artwork_checklist').update({...Object.fromEntries(targets.map(lang=>['translation_'+lang,texts[lang]])),translation_status:'TRANSLATION_COMPLETED'}).eq('id',row.id).eq('translation_status',row.translation_status).select('id').single();if(result.error)setMessage('Approval failed or already recorded. Refresh the queue.');else onSaved();}
  catch{setMessage('Connection interrupted. Refresh before retrying approval.');}finally{running.current=false;setBusy(false);}
 }
 return <article className="rounded border ps-4 pe-4 py-4 space-y-3"><p>Artwork / العمل: {row.id} · Dossier scenario / ملف العرض: {row.scenario_id}</p><div className="grid gap-4 md:grid-cols-2"><section dir={row.source.language==='ar'?'rtl':'ltr'}><h3>Original · {row.source.language} / النص الأصلي</h3>{translationFields.map(k=><p key={k}>{row.source[k]}</p>)}</section>{targets.map(lang=><fieldset key={lang} dir={lang==='ar'?'rtl':'ltr'} disabled={busy||(row.translation_status==='TRANSLATION_COMPLETED'&&lang==='ar')}><legend>{lang==='ar'?'الصياغة العربية الرسمية':'Official English translation'}</legend>{translationFields.filter(k=>k!=='bio'||row.source.bio?.trim()).map(key=><label className="block" key={key}>{lang} · {{title:'Artwork title / عنوان العمل',medium:'Materials / الخامات',concept:'Concept — 50 words / نبذة العمل',bio:'Biography / السيرة'}[key]}<textarea className={operationalInput} maxLength={2000} value={texts[lang][key]??''} onChange={e=>setTexts({...texts,[lang]:{...texts[lang],[key]:e.target.value}})}/></label>)}</fieldset>)}</div><button className="rounded bg-green-800 text-white ps-4 pe-4 py-2 disabled:opacity-50 disabled:cursor-not-allowed" disabled={busy||!valid} onClick={()=>void approve()}>اعتماد الترجمة / Approve Translation</button><p role="status">{message}</p></article>;
}
export function ArtistMetadataQueue({translate=false,exportLabels=false}:{translate?:boolean;exportLabels?:boolean}){
 const queue=useOperationalRows<CatalogArtwork>('sadu_artwork_checklist');const visible=translate?queue.rows.filter(r=>!bilingualComplete(r)):queue.rows;
 return <section className={operationalPanel}><h2 className="flex gap-2 text-xl"><Languages aria-hidden="true"/>{translate?'ترجمة بيانات الفنانين / Artist Metadata Translation':'بيانات الأعمال والمقاسات / Artwork Metadata & Measurements'}</h2><TranslationPolicy/><p>{queue.live?'Live database updates connected.':'Live connection pending — refresh fallback every 15 seconds.'}</p><p role="status">{queue.notice}</p><button className="underline" onClick={()=>void queue.refresh()}>Refresh</button>{exportLabels&&<button className={`${operationalButton} flex gap-2`} disabled={!queue.rows.some(bilingualComplete)} onClick={()=>{const url=URL.createObjectURL(new Blob([labelCSV(queue.rows)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`SADU-wall-labels-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}><Download aria-hidden="true"/>Export to Editorial/Design — finalized labels</button>}{visible.map(row=>translate?<TranslationCard key={row.id} row={row} onSaved={()=>void queue.refresh()}/>:<article key={row.id} className="border-s-4 ps-3"><h3>{publicText(row,'ar')?.title??row.source.title}</h3><p>{row.source.title} · {row.translation_status}</p><p>{row.width_cm} × {row.height_cm} cm · {row.weight_kg} kg · {row.crate_count} crates</p>{bilingualComplete(row)?<><p className="text-green-800">Bilingual text approved / النص الثنائي معتمد · {row.translated_at}</p>{(['ar','en'] as const).map(lang=><section key={lang} lang={lang} dir={lang==='ar'?'rtl':'ltr'}>{translationFields.map(k=><p key={k}>{publicText(row,lang)?.[k]}</p>)}</section>)}</>:<p>Pending bilingual Editorial approval / بانتظار اعتماد الترجمة</p>}</article>)}</section>;
}
