import {damageHold} from '../data/conditionReporting';
import {useState} from 'react';
import {Landmark,CircleDollarSign,MapPin} from 'lucide-react';
import type {CommissionState} from '../types';
import type {CommissionAction} from '../data/commissionScenario';
import {validBanking,validTransactionDate} from '../data/artistAdministration';
const panel='my-5 space-y-3 rounded border border-[#D9CEBA] bg-[#F7F1E6] ps-5 pe-5 py-5 text-start';
const field='block w-full rounded border ps-3 pe-3 py-2';
const button='rounded bg-[#8B261E] ps-4 pe-4 py-2 text-white disabled:opacity-50 disabled:cursor-not-allowed';
type Props={state:CommissionState;actor:'ARTIST'|'FINANCE'|'LOGISTICS';onAction?:(a:CommissionAction)=>void};
export function PaymentReceiptSync({state,actor,onAction}:Props){
 const [date,setDate]=useState('');const bank=state.administration,c=state.contracts[0];
 if(!c)return null;
 const ready=Boolean(bank&&bank.contractId===c.id&&validBanking(bank)&&['ARTIST_APPROVED','LOCKED'].includes(c.status)&&!damageHold(state)&&state.installationStatus!=='EXECUTIVE_IMPOUND'&&state.installationStatus!=='ARCHIVED_CLOSED');
 return <section className={panel}><h2 className="flex gap-2 text-xl"><Landmark aria-hidden="true"/>تأكيد التحويل / Payment receipts</h2><p>Fictional session records only. No funds are transferred.</p>{actor==='FINANCE'&&<>{bank?.contractId===c.id?<dl><dt>Beneficiary / Bank</dt><dd>{bank.holder} · {bank.bankName??'Not supplied'}</dd><dt>SWIFT/BIC · IBAN</dt><dd><bdi>{bank.bic??'Not supplied'} · {bank.iban}</bdi></dd></dl>:<p>Waiting for Artist banking details.</p>}<label>Transaction date<input type="date" required max={new Date().toISOString().slice(0,10)} className={field} value={date} onChange={e=>setDate(e.target.value)}/></label></>}{(state.ledger??[]).map(row=>{const receipt=state.paymentReceipts?.find(r=>r.tranche===row.tranche&&r.revision===row.revision);return <article key={`${row.revision}:${row.tranche}`} className="border-s-4 ps-3 py-3"><p>{row.tranche} · AED {row.amount} · Agreement revision {row.revision}</p>{receipt?<p role="status" className="text-emerald-800"><CircleDollarSign aria-hidden="true"/>PAYMENT_DISBURSED_ON_{receipt.date} · Recorded {receipt.at}</p>:actor==='FINANCE'?<button className={button} disabled={!onAction||!ready||row.revision!==state.agreementRevision||!validTransactionDate(date)} onClick={()=>onAction?.({type:'record-payment-receipt',actor:'FINANCE',tranche:row.tranche,date,at:new Date().toISOString()})}>تأكيد التحويل / Mark as Disbursed — Simulation</button>:<p>Ledger entry recorded; dated transfer confirmation pending.</p>}</article>})}{!state.ledger?.length&&<p>No tranche ledger entries yet.</p>}</section>;
}
function OriginForm({state,assetId,index,onAction}:Props&{assetId:string;index:number}){
 const saved=state.freightOrigins?.[assetId];const [country,setCountry]=useState(saved?.country??''),[address,setAddress]=useState(saved?.address??'');
 const locked=state.installationStatus==='ARCHIVED_CLOSED'||state.originTickets?.some(t=>t.assetId===assetId&&t.revision===state.agreementRevision);
 return <form className="space-y-2 border-s-4 ps-3" onSubmit={e=>{e.preventDefault();if(!locked&&country.trim()&&address.trim().length>=10)onAction?.({type:'save-origin',actor:'ARTIST',assetId,address,country,at:new Date().toISOString()});}}><h3>{state.contracts[0].proposedWorkTitle} · Artwork {index+1} · {assetId}</h3><fieldset disabled={Boolean(locked)}><label>Current country<input required maxLength={100} className={field} value={country} onChange={e=>setCountry(e.target.value)}/></label><label>Current physical location — gallery, street, city, postal code<textarea required minLength={10} maxLength={2000} className={field} value={address} onChange={e=>setAddress(e.target.value)}/></label><button className={button} disabled={!country.trim()||address.trim().length<10}>Save Artwork Origin</button></fieldset>{saved&&<p role="status">Saved · {saved.country} · {saved.address} · Revision {saved.revision}</p>}{locked&&<p>Freight origin locked after ticket creation.</p>}</form>;
}
export function ArtworkFreightOrigins({state,actor,onAction}:Props){
 const c=state.contracts[0];if(!c||c.productionOrigin==='LOCAL_FABRICATION'||!['ARTIST_APPROVED','LOCKED'].includes(c.status))return null;
 return <section className={panel}><h2 className="flex gap-2 text-xl"><MapPin aria-hidden="true"/>موقع العمل الحالي / Current Physical Location</h2><p>Required separately for every artwork in the accepted agreement. Artist nationality is never used as a freight origin. Session rehearsal only.</p>{Array.from({length:c.artworkCount??1},(_,index)=>{const id=`${c.id}:${index+1}`,origin=state.freightOrigins?.[id],ticket=state.originTickets?.find(t=>t.assetId===id&&t.revision===state.agreementRevision);return actor==='ARTIST'?<OriginForm key={`${id}:${state.agreementRevision}`} state={state} actor={actor} assetId={id} index={index} onAction={onAction}/>:<article key={id} className="border-s-4 ps-3"><h3>{c.proposedWorkTitle} · Artwork {index+1} · {id}</h3>{origin?<p>{origin.country} · {origin.address}</p>:<p>Locked: Artist must provide this artwork’s current location.</p>}{ticket?<p role="status">{ticket.status} · {ticket.country} · {ticket.address}</p>:<button className={button} disabled={!onAction||!origin||origin.revision!==state.agreementRevision||state.installationStatus==='ARCHIVED_CLOSED'||state.installationStatus==='EXECUTIVE_IMPOUND'||damageHold(state)} onClick={()=>onAction?.({type:'request-origin-freight',actor:'LOGISTICS',assetId:id,at:new Date().toISOString()})}>Create Artwork Freight Ticket</button>}</article>})}</section>;
}
