import {useEffect,useRef,useState} from 'react';
import {pilotSupabase as client} from '../lib/pilotSupabase';
import {Download,Images} from 'lucide-react';
import type {CatalogArtwork} from '../data/catalogFreight';
export function CatalogLabelExport({rows}:{rows:CatalogArtwork[]}){
 const [scenario,setScenario]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const latest=useRef(rows),running=useRef(false);latest.current=rows;
 const controller=useRef<AbortController|null>(null);
 const mounted=useRef(true);useEffect(()=>{mounted.current=true;const auth=client?.auth.onAuthStateChange(()=>controller.current?.abort());return ()=>{mounted.current=false;controller.current?.abort();auth?.data.subscription.unsubscribe();};},[]);
 async function download(manifest=false){if(running.current)return;const selected=rows.filter(r=>r.scenario_id===scenario);if(!selected.length)return;running.current=true;setBusy(true);setMessage('Preparing export…');controller.current=new AbortController();const snapshot=JSON.stringify(selected);const timer=setTimeout(()=>controller.current?.abort(),60000);
  try{if(!client)throw new Error('Sign in required');const title=await client.from('sadu_exhibition_titles').select('status,title_ar,title_en').eq('scenario_id',scenario).single();if(title.error||title.data?.status!=='LOCKED'||!title.data.title_ar?.trim()||!title.data.title_en?.trim())throw new Error('Curator title lock required');const {catalogLabelsPdf}=await import('../utils/catalogLabelsPdf');const blob=manifest?await (await import('../utils/installationManifest')).installationManifest(selected,controller.current.signal):await catalogLabelsPdf(selected);if(!mounted.current||controller.current?.signal.aborted)return;if(JSON.stringify(latest.current.filter(r=>r.scenario_id===scenario))!==snapshot)throw new Error('Approval changed');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`SADU-${manifest?'installation-manifest':'labels'}-${scenario}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);setMessage('Label proof exported from the current approved data. Downloaded copies are snapshots.');}catch{if(mounted.current)setMessage('Export blocked: title unapproved, data changed, private PNG preview unavailable, scenario unsubmitted or PDF generation failed. Refresh and retry.');}finally{clearTimeout(timer);running.current=false;if(mounted.current)setBusy(false);}
 }
 return <section className="space-y-2 rounded border bg-[#FFFDF7] ps-3 pe-3 py-3"><label>Exhibition label set / مجموعة ملصقات المعرض<select className="block w-full border ps-2 pe-2 py-2" value={scenario} disabled={busy} onChange={e=>setScenario(e.target.value)}><option value="">Select complete approved exhibition</option>{[...new Set(rows.map(r=>r.scenario_id))].map(id=><option key={id}>{id}</option>)}</select></label><button className="rounded border ps-3 pe-3 py-2 disabled:opacity-50" disabled={busy||!rows.some(r=>r.scenario_id===scenario)} onClick={()=>void download()}><Download aria-hidden="true" className="inline size-4"/>Export bilingual labels PDF / تصدير الملصقات</button><button className="rounded border ps-3 pe-3 py-2 disabled:opacity-50" disabled={busy||!rows.some(r=>r.scenario_id===scenario)} onClick={()=>void download(true)}><Images aria-hidden="true" className="inline size-4"/>Visual Installation Manifest / بيان التركيب المرئي</button><p>Matching reference: the full artwork ID appears on both outputs. Transfer this same ID to the artwork backing or packing tag; existing physical tags are not inferred.</p><p>Manifest supports up to 100 artworks and requires readable private PNG images (up to 20 MiB each). TIFF/video preview conversion is pending.</p><p>Template-inspired proof. Museum layout approval and image-quality inspection remain separate.</p><p role="status">{message}</p></section>;
}
