import { pdfHasSignature } from '../data/visaIntake';
import { useState } from 'react';
import { Archive, Landmark, Truck } from 'lucide-react';
import type { CommissionState } from '../types';
import type { CommissionAction } from '../data/commissionScenario';
import { validCollectionTerms } from '../data/collectionCloseout';
import { damageHold } from '../data/conditionReporting';
const panel='my-5 space-y-4 rounded border bg-[#F7F1E6] ps-5 pe-5 py-5 text-start';
const button='rounded border ps-4 pe-4 py-2 disabled:opacity-50 disabled:cursor-not-allowed';
export function CollectionCloseout({state,actor,onAction}:{state:CommissionState;actor:string;onAction?:(a:CommissionAction)=>void}){
 const [notice,setNotice]=useState('');
 const [price,setPrice]=useState(''),[address,setAddress]=useState(''),[packing,setPacking]=useState('');
 const c=state.contracts[0];if(!c)return null;
 const send=(type:'acquire'|'return-ticket'|'archive')=>onAction?.({type,actor,at:new Date().toISOString()});
 const blocked=damageHold(state)||state.installationStatus==='EXECUTIVE_IMPOUND'||state.installationStatus==='ARCHIVED_CLOSED';
 return <section className={panel}><h2 className="flex items-center gap-2 text-xl font-semibold"><Landmark aria-hidden="true"/>{actor==='ARTIST'?'Acquisition & Return Intake':actor==='LOGISTICS'?'إجراءات الشحن العكسي وإغلاق الملف / Return Freight & Close-out':'Institutional Acquisition'} · {c.proposedWorkTitle}</h2><p className="text-sm">Session rehearsal record only — no purchase, payment or freight booking is executed.</p>
 {actor==='ARTIST'&&!state.collectionTerms&&<form onSubmit={e=>{e.preventDefault();onAction?.({type:'collection-terms',actor,terms:{priceUSD:Number(price),returnAddress:address,packing,at:new Date().toISOString()}});}}><fieldset disabled={blocked} className="space-y-3"><label className="block">Price (U.S $)<input className="block border ps-3 pe-3 py-2" required type="number" min="0.01" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label className="block">Full postal address (For returning the artworks)<textarea className="block w-full border ps-3 pe-3 py-2" required maxLength={2000} value={address} onChange={e=>setAddress(e.target.value)}/></label><label className="block">Packing Instructions<textarea className="block w-full border ps-3 pe-3 py-2" required maxLength={2000} value={packing} onChange={e=>setPacking(e.target.value)}/></label><button className={button} disabled={!validCollectionTerms({priceUSD:Number(price),returnAddress:address,packing,at:new Date().toISOString()})}>Submit Artist Intake</button></fieldset></form>}
 {state.collectionTerms&&<div><p>Artist-submitted price: USD {state.collectionTerms.priceUSD}</p><p className="whitespace-pre-wrap">Return address: {state.collectionTerms.returnAddress}</p><p className="whitespace-pre-wrap">Packing: {state.collectionTerms.packing}</p><p>{state.collectionTerms.at}</p></div>}
 {actor==='BIENNIAL_DIRECTOR'&&!state.acquisition&&<><button className={`${button} bg-amber-100 text-amber-900`} disabled={blocked||!state.collectionTerms||!state.logistics||Boolean(state.returnFreight?.awb)} onClick={()=>send('acquire')}>إصدار أمر اقتناء / Initiate Institutional Acquisition</button>{!state.collectionTerms&&<p>Awaiting artist-submitted sale price; no grant amount is substituted.</p>}</>}
 {state.acquisition&&<p role="status">ACQUIRED_BY_INSTITUTION · Acquisition Payout: USD {state.acquisition.priceUSD} · {state.acquisition.payoutStatus} · {state.acquisition.at}</p>}
 {actor==='LOGISTICS'&&<><h3 className="flex items-center gap-2"><Truck aria-hidden="true"/>Return Manifest</h3>{state.acquisition&&<p>Retained by institution. Pending return freight cancelled. Archive remains locked: acquired works need a separate permanent-collection accession workflow, not a return AWB.</p>}{!state.returnFreight&&!state.acquisition&&<button className={button} disabled={blocked||!state.collectionTerms||!state.logistics} onClick={()=>send('return-ticket')}>Generate Return Freight Manifest</button>}{state.returnFreight&&<><p>{state.returnFreight.status}</p><p>{state.returnFreight.address}</p><p>{state.returnFreight.packing}</p>{state.returnFreight.cancelledAt&&<p>Cancelled: {state.returnFreight.cancelledAt}</p>}{state.returnFreight.awb?<p>AWB: {state.returnFreight.awb.name} · {state.returnFreight.awbAt}</p>:<label className="block border-2 border-dashed ps-4 pe-4 py-4">Return Air Waybill — PDF<input disabled={blocked||Boolean(state.acquisition)} type="file" accept=".pdf,application/pdf" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(!await pdfHasSignature(file)){setNotice('Upload a valid PDF AWB, up to 10 MB.');return;}onAction?.({type:'return-awb',actor,file,at:new Date().toISOString()});setNotice('AWB recorded.');}catch{setNotice('Unable to read this file. Choose another PDF.');}}}/></label>}<button className={button} disabled={blocked||!state.returnFreight.awb||Boolean(state.acquisition)} onClick={()=>send('archive')}><Archive aria-hidden="true"/>أرشفة الملف نهائياً / Archive &amp; Close Dossier</button></>}</>}
 <p role="status">{notice}</p>
 {state.archivedAt&&<p role="status">ARCHIVED_CLOSED · {state.archivedAt} · Historical record</p>}
 </section>;
}
