import { useEffect, useRef, useState } from 'react';
import { PackageOpen, AlertTriangle, LifeBuoy } from 'lucide-react';
import type { CommissionState } from '../types';
import type { CommissionAction } from '../data/commissionScenario';
import { validDamagePhoto } from '../data/conditionReporting';
const panel='space-y-4 rounded border border-[#D9CEBA] bg-[#F7F1E6] ps-5 pe-5 py-5 text-start';
const button='rounded border border-[#8B261E] ps-4 pe-4 py-2 text-[#8B261E] disabled:opacity-50 disabled:cursor-not-allowed';
const field='mt-2 block w-full rounded border bg-white ps-3 pe-3 py-2';
function Photo({file}:{file:File}){const [url,setUrl]=useState('');useEffect(()=>{const u=URL.createObjectURL(file);setUrl(u);return()=>URL.revokeObjectURL(u);},[file]);return <a href={url||undefined} download={file.name} className="break-all underline">{file.name}</a>;}
export function ConditionReporting({state,isAr,actor,onRecord}:{state:CommissionState;isAr:boolean;actor:string;onRecord?:(a:CommissionAction)=>void}) {
 const [condition,setCondition]=useState<'INTACT'|'DAMAGED'>('INTACT'),[photos,setPhotos]=useState<File[]>([]),[error,setError]=useState('');
 const [reportId,setReportId]=useState(''),[grant,setGrant]=useState(''),[flight,setFlight]=useState(''),[reason,setReason]=useState('');
 const dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement|null>(null);
 const t=(ar:string,en:string)=>isAr?ar:en;
 const current=state.conditionReports?.find(r=>r.revision===state.agreementRevision&&r.receiptReference===state.logistics?.reference);
 const reportable=actor==='LOGISTICS'&&state.logistics&&!state.logistics.closedAt;
 const reports=(state.conditionReports??[]).filter(r=>actor!=='ARTIST'||Boolean(r.artistDispatchedAt));
 if(!reportable&&!reports.length&&!state.emergencyRequests?.length)return null;
 return <section className={panel}><h2 className="flex items-center gap-2 text-xl font-semibold"><PackageOpen aria-hidden="true"/>{t('تقرير حالة العمل الفني','Unboxing & Condition Report')}</h2><p className="text-sm">{t('أدلة وطلبات محاكاة للجلسة؛ لا مطالبة تأمينية أو حجز سفر أو تحويل مالي خارجي.','Session rehearsal evidence and requests; no external insurance claim, flight booking or money transfer.')}</p>
 {reportable&&!current&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();onRecord?.({type:'record-condition',actor,id:crypto.randomUUID(),condition,photos,at:new Date().toISOString()});}}><p>{state.logistics?.reference} · Revision {state.agreementRevision}</p><fieldset><legend>{t('حالة العمل عند فتح الصندوق','Condition on unboxing')}</legend>{(['INTACT','DAMAGED'] as const).map(value=><label key={value} className="me-4 inline-flex items-center gap-2"><input type="radio" checked={condition===value} onChange={()=>setCondition(value)}/>{value==='INTACT'?t('سليم','INTACT'):t('متضرر أثناء النقل','DAMAGED IN TRANSIT')}</label>)}</fieldset>
 {condition==='DAMAGED'&&<label className="block rounded border-2 border-dashed border-amber-400 ps-4 pe-4 py-4">{t('رفع أدلة الضرر — إلزامي','Upload Damage Evidence — required')}<input type="file" accept="image/png,image/jpeg" multiple className="mt-2 block w-full" onChange={e=>{const files=Array.from(e.target.files??[]);e.target.value='';if(!files.length||files.length>5||!files.every(validDamagePhoto)){setError('Choose 1–5 PNG/JPEG photos, up to 10 MB each.');return;}setPhotos(files);setError('');}}/><p>{photos.map(f=>f.name).join(', ')}</p></label>}
 {!state.contracts[0]?.shippingLiability&&<p role="status">{t('المسؤولية غير موثقة في الاتفاقية. يلزم تعديل رسمي؛ لا تفترض جهة التأمين.','Liability is missing from this legacy agreement. A formal amendment is required; no insurer is inferred.')}</p>}<button className={button} disabled={!state.contracts[0]?.shippingLiability||condition==='DAMAGED'&&!photos.length}>{t('تسجيل تقرير الحالة','Record condition report')}</button></form>}
 {error&&<p role="alert">{error}</p>}
 {reports.map(r=><article key={r.id} className={`space-y-3 rounded border ps-4 pe-4 py-4 ${r.condition==='DAMAGED'?'border-amber-400 bg-amber-50':'bg-white'}`}><h3 className="font-semibold">{r.condition} · {r.receiptReference}</h3><p>Revision {r.revision} · {new Date(r.at).toLocaleString(isAr?'ar-AE':'en-AE')}</p><p>{t('مسؤولية التأمين','Insurance liability')}: {r.liability}</p>{r.condition==='DAMAGED'&&<p className="flex items-center gap-2 font-semibold text-red-900"><AlertTriangle aria-hidden="true"/>{t('العمل محجوز — يمنع النقل إلى قاعة العرض','Artwork on hold — movement to exhibition hall blocked')}</p>}
 <ul>{r.photos.map((file,i)=><li key={i}><Photo file={file}/></li>)}</ul>
 {r.insuranceStatus&&<p role="status">HIGH PRIORITY · INSURANCE_CLAIM_PENDING · {t('منسق اللوجستيات والشحن','Logistics / Shipping Coordinator')}</p>}
 {r.artistDispatchedAt&&<p role="status">{t('أرسلت الأدلة إلى بوابة الفنان','Evidence dispatched to Artist Portal')} · {r.artistDispatchedAt}</p>}
 {actor==='LOGISTICS'&&r.condition==='DAMAGED'&&<div className="flex flex-wrap gap-3">{r.liability==='ARTIST'&&!r.artistDispatchedAt&&<button className={button} onClick={()=>onRecord?.({type:'dispatch-damage',actor,reportId:r.id,at:new Date().toISOString()})}>{t('إرسال الأدلة إلى بوابة الفنان','Dispatch Evidence to Artist Portal')}</button>}<button ref={el=>{if(reportId===r.id)trigger.current=el;}} disabled={state.emergencyRequests?.some(q=>q.reportId===r.id)} className={button} onClick={e=>{trigger.current=e.currentTarget;setReportId(r.id);setGrant('');setFlight('');setReason('');dialog.current?.showModal();}}><LifeBuoy aria-hidden="true" className="me-2 inline size-4"/>{t('تفعيل الخطة البديلة — إعادة إنتاج طارئة','Initiate Plan B (Emergency Re-Production)')}</button></div>}</article>)}
 {(state.emergencyRequests??[]).filter(q=>actor!=='ARTIST'||reports.some(r=>r.id===q.reportId)).map(q=><article key={q.id} className="space-y-3 rounded border border-red-300 bg-red-50 ps-4 pe-4 py-4"><h3 className="font-semibold">HIGH PRIORITY · Plan B · AED {q.grant.toLocaleString()}</h3><p>{q.flight}</p><p>{q.reason}</p><p>Director: {q.directorDecision??'PENDING_APPROVAL'} · Finance: {q.financeDecision??'PENDING_APPROVAL'}</p><p className="text-sm">{t('الاعتمادات لا ترفع الحجز ولا تصرف المنحة تلقائياً.','Approvals do not lift the hold or disburse the grant automatically.')}</p>{((actor==='BIENNIAL_DIRECTOR'&&!q.directorDecision)||(actor==='FINANCE'&&q.directorDecision==='APPROVED'&&!q.financeDecision))&&<div className="flex gap-3">{[true,false].map(approve=><button key={String(approve)} className={button} onClick={()=>onRecord?.({type:'review-plan-b',actor,requestId:q.id,approve,at:new Date().toISOString()})}>{approve?t('تسجيل الموافقة','Record approval'):t('رفض الطلب','Reject request')}</button>)}</div>}</article>)}
 <dialog ref={dialog} onClose={()=>trigger.current?.focus()} className="m-auto w-full max-w-lg rounded-xl border bg-[#F7F1E6] ps-6 pe-6 py-6 backdrop:bg-black/40" aria-labelledby="plan-b-title"><form className="space-y-4" onSubmit={e=>{e.preventDefault();if(!Number.isFinite(Number(grant))||Number(grant)<=0||!flight.trim()||!reason.trim())return;onRecord?.({type:'request-plan-b',actor,id:crypto.randomUUID(),reportId,grant:Number(grant),flight,reason,at:new Date().toISOString()});dialog.current?.close();}}><h3 id="plan-b-title" className="text-xl font-semibold">{t('طلب إعادة إنتاج طارئة','Emergency reproduction request')}</h3><label className="block">{t('منحة إنتاج ثانوية — درهم','Secondary production grant — AED')}<input autoFocus required type="number" min="0.01" max="10000000" step="0.01" className={field} value={grant} onChange={e=>setGrant(e.target.value)}/></label><label className="block">{t('طلب الرحلة الطارئة — المسار والتاريخ','Emergency flight — route and date')}<input required maxLength={500} className={field} value={flight} onChange={e=>setFlight(e.target.value)}/></label><label className="block">{t('مبررات الطوارئ','Emergency justification')}<textarea required maxLength={2000} className={field} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="flex gap-3"><button className={button}>{t('إحالة عاجلة للمدير والمالية','Route urgently to Director & Finance')}</button><button type="button" className={button} onClick={()=>dialog.current?.close()}>{t('إلغاء','Cancel')}</button></div></form></dialog>
 </section>;
}
