import RenewalQueue, { type RenewalCycle } from './RenewalQueue';
import EvidencePreview from './EvidencePreview';
import { useAmendmentReview } from './AmendmentImpact';
import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { selectPublishingRecord } from '../data/publishingRecord';
import type { PublishingRecord } from '../data/publishingRecord';
import { NextActionCard } from './NextActionCard';

type Evidence = { id:string; kind:string; name:string; url:string; source:string; sender:string; receivedAt:string|null; actorId:string; at:string; file_hash:string; byte_length:number };
type Spec = { supplier:string; quantity:number; size:string; stock:string; finishing:string; profile:string; deliveryDate:string };
type Package = { revision:number; proofId:string; proofHash:string; spec:Spec; preflight:{passed:boolean; evidenceId:string; note:string}|null; completedQuantity?:number };
type Delivery = {id:string;revision:number;quantity:number;reference:string;acceptance:{actorId:string;at:string}|null};
type Task = {renewal?:boolean;id:string;key?:string;owner:string;ownerId:string|null;title:string;blocker:string;accepted?:boolean;overdue?:boolean;dueAt?:string};
export type OperationsView = {renewals?:RenewalCycle[];version:number;serverTime:string;readiness:{preparationComplete:boolean;packingVerified:boolean;conditionAndAgreementCleared:boolean;departureReady:boolean;expired:boolean;blockers:string[]}|null;job:{record:PublishingRecord;packages:Package[];deliveries:Delivery[]}|null;files:Evidence[];tasks:Task[];accounts:{id:string;name:string;role:string}[]};
type Props={view:OperationsView;artworkId:string;role:string;actorId:string;locked:boolean;onChanged:()=>Promise<void>;onDirtyChange:(value:boolean)=>void};
const field='mt-1 block w-full min-h-12 rounded border border-[#D9CEBA] bg-white p-3 text-start';
const button='min-h-12 rounded border border-[#8B4513] px-4 py-2 text-[#1A1817] disabled:opacity-40';

function ActionForm({id,title,disabled,onChange,onSubmit,children}:{id?:string;title:string;disabled:boolean;onChange:()=>void;onSubmit:(form:FormData)=>Promise<boolean>;children:ReactNode}) {
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;if(await onSubmit(new FormData(form)))form.reset();};
  return <form id={id} tabIndex={-1} onChange={onChange} onSubmit={e=>void submit(e)} className="space-y-3"><fieldset disabled={disabled} className="space-y-3"><legend className="font-semibold">{title}</legend>{children}<button className={button}>{title}</button></fieldset></form>;
}
function FileChoice({files,name='evidenceId'}:{files:Evidence[];name?:string}) {return <label className="block">الملف / File<select className={field} name={name} required defaultValue=""><option value="" disabled>اختر الملف / Select file</option>{files.map(f=><option key={f.id} value={f.id}>{f.name} · {f.file_hash.slice(0,8)}</option>)}</select></label>;}
function TextField({name,label,type='text'}:{name:string;label:string;type?:string}) {return <label className="block">{label}<input className={field} required name={name} type={type} maxLength={1000} min={type==='number'?1:undefined} step={type==='number'?1:undefined}/></label>;}

export default function ConnectedOperations({view:initial,artworkId,role,actorId,locked,onChanged,onDirtyChange}:Props) {
  const [view,setView]=useState(initial),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[base,setBase]=useState(initial.version),[message,setMessage]=useState(''),[error,setError]=useState(''),[needsRefresh,setNeedsRefresh]=useState(false);
  const [preview,setPreview]=useState<Evidence|null>(null),[showFiles,setShowFiles]=useState(!initial.files.length);
  const amendment=useAmendmentReview(view.version);
  const pending=useRef(false),sequence=useRef(0),changed=useRef(onChanged),retry=useRef<{key:string;id:string;version?:number;reviewed?:{impactToken?:string}}|null>(null);changed.current=onChanged;
  const path=`/api/review/pilot/operations/${encodeURIComponent(artworkId)}`;
  useEffect(()=>setView(v=>initial.version>=v.version?initial:v),[initial]);
  useEffect(()=>{onDirtyChange(dirty||busy);},[dirty,busy,onDirtyChange]);
  const refresh=async()=>{const ticket=++sequence.current;const response=await fetch(path,{cache:'no-store'});const body=await response.json();if(!response.ok)throw Error(body.error??'Refresh unavailable');if(ticket===sequence.current)setView(v=>body.version>=v.version?body:v);return body as OperationsView;};
  useEffect(()=>{const update=()=>{if(!pending.current)void refresh().catch(()=>setMessage('تعذر التحديث؛ البيانات المحفوظة ظاهرة / Refresh unavailable; saved data remains visible.'));};const timer=window.setInterval(update,5000);window.addEventListener('focus',update);return()=>{clearInterval(timer);window.removeEventListener('focus',update);sequence.current++;};},[path]);
  const mark=()=>{if(!dirty)setBase(view.version);setDirty(true);};
  const stale=dirty&&base!==view.version;
  const run=async(action:string,data:Record<string,unknown>,file?:File)=>{
    if(pending.current||stale||needsRefresh||locked)return false;
    pending.current=true;sequence.current++;setBusy(true);setError('');setMessage('');
    const key=JSON.stringify({action,data,file:file?{name:file.name,size:file.size,modified:file.lastModified}:null});
    const previous=retry.current?.key===key?retry.current:null;
    const operationId=previous?.id??crypto.randomUUID();retry.current=previous??{key,id:operationId};
    const command:Record<string,unknown>={...data,action,version:previous?.version??(dirty?base:view.version),operationId};
    try {
      if(action==='SET_PRINT_PACKAGE') {
        const reviewed=previous?.reviewed??await amendment.review(path,command);
        if(reviewed===null){retry.current=null;return false;}
        Object.assign(command,reviewed);retry.current={key,id:operationId,version:command.version as number,reviewed};
      }
      const response=await fetch(file?path+'/evidence':path,{method:'POST',headers:file?{'Content-Type':'application/octet-stream','x-sadu-metadata':encodeURIComponent(JSON.stringify(command))}:{'Content-Type':'application/json'},body:file??JSON.stringify(command)});
      const result=await response.json();if(!response.ok){retry.current=null;if(response.status===409)await refresh();throw Error(result.error??'Save failed');}
      retry.current=null;if(file)setShowFiles(true);
      setDirty(false);onDirtyChange(false);
      try{const latest=await refresh();setBase(latest.version);await changed.current();setMessage('تم الحفظ في السجل المشترك / Saved in the shared local record.');}
      catch{setNeedsRefresh(true);setMessage('تم الحفظ؛ يلزم تحديث العرض / Saved; refresh before another change.');}
      return true;
    } catch(e){setError((e as Error).message);if(e instanceof TypeError)setNeedsRefresh(true);return false;}
    finally{pending.current=false;setBusy(false);}
  };
  const formProps={disabled:busy||stale||needsRefresh||locked,onChange:mark};
  const job=view.job,pkg=job?.packages.find(p=>p.revision===job.record.version),stage=job?selectPublishingRecord(job.record).stage:'drafting';
  const printCommand=(action:string,data:Record<string,unknown>={})=>run(action,{...data,revision:pkg?.revision});
  const renewalBlocked=(key:string)=>{const task=view.renewals?.find(c=>!c.supersededAt&&c.tasks.some(t=>t.key===key))?.tasks.find(t=>t.key===key);return !!task&&!task.canAct;};
  const tracked=(key:string)=>view.renewals?.some(c=>!c.supersededAt&&c.tasks.some(t=>t.key===key));
  const canPrepare=['Exhibition_Coordinator','General_Exhibition_Coordinator'].includes(role);
  const kinds=role==='Logistics'?['PACKING']:canPrepare?['PRINT_PROOF']:['Technical','Editorial'].includes(role)?['PREFLIGHT']:[];
  const title=(en:string,ar:string)=>`${ar} / ${en}`;
  const deliveryTotal=job?.deliveries.filter(d=>d.revision===pkg?.revision).reduce((n,d)=>n+d.quantity,0)??0;
  const acceptedTotal=job?.deliveries.filter(d=>d.revision===pkg?.revision&&d.acceptance).reduce((n,d)=>n+d.quantity,0)??0;
  return <section id="shared-operations" className="rounded-xl border border-[#D9CEBA] bg-white p-5 space-y-5 text-[#1A1817]" aria-label="Shared evidence and release">
    <header><h2 className="text-xl font-semibold">الأدلة والتسليم / Evidence &amp; release</h2><p className="text-sm">سجل محلي مشترك؛ حسابات تجريبية والتكاملات متوقفة / Shared local record; simulated accounts and paused integrations.</p></header>
    {error&&<p role="alert" className="text-[#8B261E]">{error}</p>}{message&&<p role="status">{message}</p>}
    {(stale||needsRefresh)&&<div role="alert"><p>تغيّر السجل. راجع النسخة الحالية قبل إعادة الحفظ. / The record changed. Review the current version before saving your retained input.</p><button className={button} disabled={busy} onClick={()=>void refresh().then(v=>{setBase(v.version);setNeedsRefresh(false);setError('');}).catch(e=>setError(e.message))}>مراجعة آخر إصدار / Review latest revision</button></div>}
    {dirty&&<button className={button} disabled={busy} onClick={()=>{setDirty(false);onDirtyChange(false);setBase(view.version);setMessage('لم يحفظ الإدخال / Draft not saved.');}}>ترك الإدخال دون حفظ / Leave draft unsaved</button>}
    {view.readiness&&<div className="space-y-2" role="status"><h3 className="font-semibold">الجاهزية الحالية / Current readiness</h3><p>{view.readiness.preparationComplete?'✓':'○'} التحضير / Preparation · {view.readiness.packingVerified?'✓':'○'} فحص ملف التغليف / Packing file reviewed · {view.readiness.conditionAndAgreementCleared?'✓':'○'} الحالة والاتفاق / Condition and agreement</p><p>{view.readiness.departureReady?'اكتملت متطلبات الخروج في التجربة / Departure prerequisites cleared in this rehearsal.':'الخروج معلّق / Departure remains on hold.'}</p><ul className="list-disc ps-5">{view.readiness.blockers.map(b=><li key={b}>{b}</li>)}</ul><p>لم يُسجّل حجز نقل أو تسليم فعلي في هذا المسار. / No transport booking or physical handover is recorded by this workflow.</p></div>}
    <RenewalQueue cycles={view.renewals??[]} accounts={view.accounts} actorId={actorId} role={role} disabled={formProps.disabled} dirty={dirty} mark={mark} run={run} openEvidence={id=>setPreview(view.files.find(f=>f.id===id)??null)}/>
    {view.tasks.filter(task=>!task.renewal).map(task=><NextActionCard key={task.id} title={task.title} owner={view.accounts.find(a=>a.id===task.ownerId)?.name??task.owner} blocker={`${task.blocker}${task.overdue?' · متأخر / Overdue':''}${task.dueAt?' · '+new Date(task.dueAt).toLocaleString():''}`}>{task.key&&task.ownerId===actorId&&!task.accepted&&<button disabled={busy||dirty||locked} className={button} onClick={()=>void run('ACCEPT_TASK',{key:task.key})}>قبول المهمة / Accept task</button>}</NextActionCard>)}
    {role==='General_Exhibition_Coordinator'&&!['technical','cost','editorial'].every(tracked)&&<details><summary>تعيين مسؤول وموعد / Assign task owner and deadline</summary><ActionForm {...formProps} title={title('Assign responsibility','تعيين المسؤولية')} onSubmit={f=>run('ASSIGN_TASK',{key:f.get('key'),ownerId:f.get('ownerId'),dueAt:new Date(String(f.get('dueAt'))).toISOString(),reason:f.get('reason')})}><label>المهمة / Task<select className={field} name="key" defaultValue={!tracked('technical')?'packing-technical':!tracked('cost')?'packing-cost':'print-review'}><option value="packing-technical" disabled={tracked('technical')}>مراجعة فنية / Technical packing review</option><option value="packing-cost" disabled={tracked('cost')}>المالية / Packing cost review</option><option value="print-review" disabled={tracked('editorial')}>قسم التحرير / Print review</option></select></label><label>المسؤول / Owner<select className={field} name="ownerId" required>{view.accounts.filter(a=>['Technical','Finance','Editorial'].includes(a.role)).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><TextField name="dueAt" type="datetime-local" label="الموعد بتوقيت جهازك / Due in your device timezone"/><TextField name="reason" label="سبب التعيين / Assignment reason"/></ActionForm></details>}
    <details open={showFiles} onToggle={e=>setShowFiles(e.currentTarget.open)}><summary>ملفات الأدلة / Evidence files ({view.files.length})</summary><ul className="space-y-3">{view.files.map(f=><li key={f.id}><button className="underline min-h-12" onClick={()=>setPreview(f)}>فتح / Open {f.name}</button><p className="text-sm">{f.source} · {f.sender} · {f.receivedAt??'وقت الاستلام غير مسجل / Receipt time unknown'}</p><p className="text-sm break-all">SHA-256: {f.file_hash}</p><p className="text-sm">سجله / Recorded by {f.actorId} · {f.at}</p></li>)}</ul><p className="text-sm">الفحص البصري مطلوب؛ البصمة لا تثبت صحة المحتوى. / Inspect the file; its hash does not certify its contents.</p></details>
    {kinds.length>0&&<details><summary>إرفاق ملف دليل / Attach evidence file</summary><ActionForm {...formProps} title={title('Save evidence file','حفظ ملف الدليل')} onSubmit={f=>{const file=f.get('file') as File;return run('UPLOAD',{kind:f.get('kind'),name:file.name,source:f.get('source'),sender:f.get('sender'),receivedAt:f.get('receivedAt')?new Date(String(f.get('receivedAt'))).toISOString():null},file);}}><label>الاستخدام / Purpose<select name="kind" className={field}>{kinds.map(kind=><option key={kind} value={kind}>{kind==='PACKING'?'دليل التغليف / Packing evidence':kind==='PRINT_PROOF'?'بروفة PDF / Print proof PDF':'تقرير فحص PDF / Preflight report PDF'}</option>)}</select></label><label>الملف / File<input className={field} type="file" name="file" accept={role==='Logistics'?'application/pdf,image/png,image/jpeg':'application/pdf'} required/></label><p className="text-sm">10 MB maximum. Synthetic files only in this local pilot.</p><TextField name="source" label="مرجع المصدر / Source reference"/><TextField name="sender" label="المرسل / Sender"/><label>وقت الاستلام إن عُرف / Received time if known<input className={field} name="receivedAt" type="datetime-local"/></label></ActionForm></details>}
    {role==='Logistics'&&<ActionForm {...formProps} id='packing-verification' disabled={formProps.disabled||renewalBlocked('packing')} title={title('Verify current packing file','تأكيد ملف التغليف الحالي')} onSubmit={f=>run('VERIFY_PACKING',{evidenceId:f.get('evidenceId'),checked:f.get('checked')==='on'})}><FileChoice files={view.files.filter(f=>f.kind==='PACKING')}/><label className="flex items-center gap-3 min-h-12"><input required type="checkbox" name="checked"/>راجعت الملف مقابل خطة التغليف الحالية / I inspected this file against the current packing plan</label></ActionForm>}
    {job&&<details open={!!pkg}><summary>أمر الطباعة / Print job · v{job.record.version}</summary><div className="space-y-5 mt-3">
      <p role="status">{({drafting:'إعداد البروفة / Drafting', 'manager-review':'مراجعة التحرير / Editorial review', 'executive-review':'بانتظار الاعتماد / Awaiting authorization', released:'معتمد / Approved', sent:'بانتظار تأكيد المورد / Awaiting supplier', acknowledged:'تأكيد المورد مسجل / Supplier acknowledged', printing:'قيد الطباعة / Printing', completed:'اكتمل الإنتاج / Production completed', correction:'تعليق للتصحيح / Correction hold', returned:'أعيد للمراجعة / Returned'})[stage]} · مسار اعتماد تجريبي؛ لا إرسال للمورد / Proposed rehearsal approval route; nothing sent to the supplier.</p>
      {pkg&&<><button className="underline min-h-12" onClick={()=>setPreview(view.files.find(f=>f.id===pkg.proofId)??null)}>فتح البروفة الحالية / Open current proof v{pkg.revision}</button><dl className="grid gap-2 sm:grid-cols-2">{Object.entries(pkg.spec).map(([key,value])=><div key={key}><dt className="text-sm">{({supplier:"المورد / Supplier",quantity:"الكمية / Quantity",size:"المقاس / Size",stock:"الخامة / Stock",finishing:"التشطيب / Finishing",profile:"مواصفات الفحص / Preflight profile",deliveryDate:"موعد التسليم / Delivery date"} as Record<string,string>)[key]??key}</dt><dd>{value}</dd></div>)}</dl><p>الفحص الفني / Preflight: {pkg.preflight?(pkg.preflight.passed?'Pass':'Hold'):'Pending'} · {pkg.preflight?.note}</p><p>المكتمل / Produced: {pkg.completedQuantity??0} · المستلم / Delivered: {deliveryTotal} · المقبول / Accepted: {acceptedTotal} / {pkg.spec.quantity}</p></>}
      {canPrepare&&(!job.record.dispatch||!!job.record.correction?.stopReference)&&<ActionForm {...formProps} title={title('Save a new print package revision','حفظ إصدار جديد لأمر الطباعة')} onSubmit={f=>run('SET_PRINT_PACKAGE',{evidenceId:f.get('evidenceId'),spec:Object.fromEntries(['supplier','quantity','size','stock','finishing','profile','deliveryDate'].map(k=>[k,k==='quantity'?Number(f.get(k)):String(f.get(k))]))})}><FileChoice files={view.files.filter(f=>f.kind==='PRINT_PROOF')}/>{[['supplier','المورد / Supplier'],['quantity','الكمية / Quantity'],['size','المقاس والهوامش / Size and bleed'],['stock','الخامة / Stock'],['finishing','التشطيب / Finishing'],['profile','مواصفات الفحص المتفق عليها / Agreed preflight profile'],['deliveryDate','موعد التسليم / Delivery date']].map(([name,label])=><TextField key={name} name={name} label={label} type={name==='quantity'?'number':name==='deliveryDate'?'date':'text'}/>)}<p>سيُحفظ الإصدار السابق وتُطلب مراجعات جديدة. / Previous versions remain available; new reviews are required.</p></ActionForm>}
      {pkg&&['Technical','Editorial'].includes(role)&&stage==='manager-review'&&<ActionForm {...formProps} id='print-preflight' disabled={formProps.disabled||renewalBlocked('preflight')} title={title('Record technical preflight','تسجيل الفحص الفني')} onSubmit={f=>printCommand('PREFLIGHT',{evidenceId:f.get('evidenceId'),passed:f.get('result')==='pass',note:f.get('note')})}><FileChoice files={view.files.filter(f=>f.kind==='PREFLIGHT')}/><label>النتيجة / Result<select name="result" className={field}><option value="hold">Hold / معلّق</option><option value="pass">Pass / مستوفٍ</option></select></label><TextField name="note" label="نطاق الفحص والملاحظات / Inspection scope and notes"/></ActionForm>}
      {pkg&&role==='Editorial'&&stage==='manager-review'&&<ActionForm {...formProps} id='print-editorial' disabled={formProps.disabled||renewalBlocked('editorial')} title={title('Submit editorial review','إحالة مراجعة التحرير')} onSubmit={f=>printCommand('REVIEW_PRINT',{editorialChecked:f.get('editorial')==='on',rightsChecked:f.get('rights')==='on'})}><label className="block min-h-12"><input required type="checkbox" name="editorial"/> راجعت العربية والإنجليزية / I reviewed Arabic and English</label><label className="block min-h-12"><input required type="checkbox" name="rights"/> راجعت صلاحيات الاستخدام / I checked permissions to use the content</label></ActionForm>}
      {role==='Chairman'&&stage==='executive-review'&&<ActionForm {...formProps} id='print-authorization' disabled={formProps.disabled||renewalBlocked('executive')} title={title('Approve this package','اعتماد هذا الإصدار')} onSubmit={f=>printCommand('APPROVE_PRINT',{checked:f.get('checked')==='on'})}><label><input required name="checked" type="checkbox"/> راجعت الملف والمواصفات الحالية / I reviewed the current file and specification</label></ActionForm>}
      {role==='Editorial'&&stage==='released'&&<button id='print-dispatch' className={button} disabled={busy||dirty||locked||renewalBlocked('dispatch')} onClick={()=>void printCommand('DISPATCH_PRINT')}>تسجيل تسليم البروفة — دون إرسال / Record proof dispatch — no sending</button>}
      {role==='Editorial'&&stage==='sent'&&<ActionForm {...formProps} id='print-supplier' disabled={formProps.disabled||renewalBlocked('supplier')} title={title('Record supplier acknowledgment','تسجيل تأكيد المورد')} onSubmit={f=>printCommand('ACK_PRINT',{proofId:pkg?.proofId,sender:f.get('sender'),receivedAt:new Date(String(f.get('receivedAt'))).toISOString(),reference:f.get('reference')})}><TextField name="sender" label="اسم المرسل من المورد / Supplier sender"/><TextField name="receivedAt" type="datetime-local" label="وقت استلام التأكيد / Acknowledgment received"/><TextField name="reference" label="مرجع تأكيد هذا الملف والمواصفات / Confirmation of this file and specification"/></ActionForm>}
      {role==='Editorial'&&stage==='acknowledged'&&<button className={button} disabled={busy||dirty||locked} onClick={()=>void printCommand('START_PRINT')}>تسجيل بدء الطباعة / Record printing started</button>}
      {role==='Editorial'&&stage==='printing'&&<ActionForm {...formProps} title={title('Record completed production','تسجيل اكتمال الإنتاج')} onSubmit={f=>printCommand('COMPLETE_PRINT',{quantity:Number(f.get('quantity')),reference:f.get('reference')})}><TextField name="quantity" type="number" label="الكمية المكتملة / Completed quantity"/><TextField name="reference" label="مرجع إتمام الإنتاج / Completion source"/></ActionForm>}
      {role==='Editorial'&&stage==='completed'&&deliveryTotal<(pkg?.completedQuantity??0)&&<ActionForm {...formProps} title={title('Record a delivery','تسجيل دفعة مستلمة')} onSubmit={f=>printCommand('RECORD_DELIVERY',{quantity:Number(f.get('quantity')),reference:f.get('reference')})}><TextField name="quantity" type="number" label="كمية هذه الدفعة / Quantity in this delivery"/><TextField name="reference" label="مرجع التسليم / Delivery reference"/></ActionForm>}
      {role==='General_Exhibition_Coordinator'&&stage==='completed'&&job.deliveries.filter(d=>d.revision===pkg?.revision&&!d.acceptance).map(d=><ActionForm key={d.id} {...formProps} title={title(`Accept delivery of ${d.quantity}`,'قبول الدفعة المستلمة')} onSubmit={f=>printCommand('ACCEPT_DELIVERY',{deliveryId:d.id,checked:f.get('checked')==='on',reference:f.get('reference')})}><p>{d.reference}</p><TextField name="reference" label="مرجع فحص الاستلام / Acceptance evidence"/><label><input required type="checkbox" name="checked"/> فحصت الدفعة / I inspected this delivery</label></ActionForm>)}
      {pkg&&(canPrepare||role==='Editorial')&&stage!=='correction'&&<details><summary>الإبلاغ عن تصحيح / Report a correction</summary><ActionForm {...formProps} title={title('Hold this revision','تعليق هذا الإصدار')} onSubmit={f=>printCommand('CORRECT_PRINT',{reason:f.get('reason')})}><TextField name="reason" label="سبب التصحيح / Correction reason"/></ActionForm></details>}
      {role==='Editorial'&&job.record.correction&&job.record.dispatch&&!job.record.correction.stopReference&&<ActionForm {...formProps} title={title('Record supplier stop or stock disposition','تسجيل إيقاف المورد أو التصرف في المطبوع')} onSubmit={f=>printCommand('STOP_PRINT',{reference:f.get('reference')})}><TextField name="reference" label="مرجع التأكيد الفعلي من المورد / Actual supplier acknowledgment reference"/></ActionForm>}
      {job.packages.length>1&&<details><summary>الإصدارات السابقة / Earlier packages</summary><ul>{job.packages.filter(p=>p.revision!==pkg?.revision).map(p=><li key={p.revision}><button className="underline min-h-12" onClick={()=>setPreview(view.files.find(f=>f.id===p.proofId)??null)}>v{p.revision} · {p.spec.supplier} · {p.spec.quantity}</button></li>)}</ul></details>}
    </div></details>}
    {preview&&<EvidencePreview key={preview.id} file={preview} onClose={()=>setPreview(null)}/>}
    {amendment.dialog}
  </section>;
}
