import { useEffect, useState } from 'react';
const endpoint='/api/review/pilot/invitation';
const input='block w-full rounded border border-[#D9CEBA] bg-white p-2 text-start';
const button='rounded bg-[#8B261E] px-4 py-2 text-white disabled:opacity-40';
export default function ConnectedInvitation({role,onChanged,onDirtyChange}:{role:string;onChanged:()=>Promise<void>;onDirtyChange:(v:boolean)=>void}) {
  const [view,setView]=useState<any>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const [discipline,setDiscipline]=useState('SCULPTURE'),[commission,setCommission]=useState(false),[existing,setExisting]=useState(true);
  const [welcome,setWelcome]=useState(''),[legalName,setLegalName]=useState(''),[en,setEn]=useState(''),[ar,setAr]=useState(''),[evidence,setEvidence]=useState('');
  const [link,setLink]=useState('');
  const [token,setToken]=useState(()=>new URLSearchParams(window.location.hash.slice(1)).get('token')??'');
  const load=async()=>{const r=await fetch(endpoint,{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error);setView(data);};
  useEffect(()=>{void load().catch(e=>setError(e.message));if(window.location.hash.includes('token='))window.history.replaceState(null,'',window.location.pathname+window.location.search);},[]);
  const changed=()=>onDirtyChange(true);
  const run=async(action:string,fields:object={})=>{setBusy(true);setError('');try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:view.version,action,...fields})});const result=await r.json();if(!r.ok){if(r.status===409)await load();throw new Error(result.error);}if(result.token)setLink(`${window.location.origin}/connected-pilot#invitation=${result.invitationId}&token=${result.token}`);if(action==='REDEEM')setToken('');onDirtyChange(false);await load();await onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const invitation=view?.invitation;const coordinator=['General_Exhibition_Coordinator','Exhibition_Coordinator'].includes(role);
  return <section className="rr-block rounded-xl border border-[#D9CEBA] bg-[#F7F1E6] p-5 space-y-4" aria-label="Invitation and identity">
    <h2 className="font-serif text-2xl">Invitation &amp; onboarding</h2><p className="text-sm">Local preview only. No email is sent. A self-declared name is not verified identity.</p><p role="alert">{error}</p>
    {!view?<p role="status">Loading invitation…</p>:<fieldset disabled={busy} className="space-y-4">
      {!!view.blockers.length&&<ul className="text-sm">{view.blockers.map((b:string)=><li key={b}>{b}</li>)}</ul>}
      {role==='General_Exhibition_Coordinator'&&<details><summary>Set the discipline brief</summary><label>Required discipline<select value={discipline} onChange={e=>{setDiscipline(e.target.value);changed();}} className={input}>{view.disciplines.map((d:string)=><option key={d}>{d}</option>)}</select></label><label className="block"><input type="checkbox" checked={existing} onChange={e=>{setExisting(e.target.checked);changed();}}/> Existing works permitted</label><label className="block"><input type="checkbox" checked={commission} onChange={e=>{setCommission(e.target.checked);changed();}}/> Commission proposals permitted, subject to edition policy</label><button disabled={!!view.blockers.length||(!existing&&!commission)} className={button} onClick={()=>void run('SET_BRIEF',{discipline,routes:[...(existing?['EXISTING_WORK']:[]),...(commission?['COMMISSION']:[])]})}>Save controlled brief</button></details>}
      {view.brief&&<p>Required discipline: {view.brief.discipline.replaceAll('_',' ')} · Allowed routes: {view.brief.routes.join(' / ').replaceAll('_',' ')}</p>}
      {coordinator&&<><label className="block">Personal welcome note<textarea maxLength={2000} value={welcome} onChange={e=>{setWelcome(e.target.value);changed();}} className={input}/></label><button disabled={!welcome.trim()||!view.brief||!!view.blockers.length} className={button} onClick={()=>void run('PREVIEW',{welcome})}>Prepare bilingual preview</button></>}
      {invitation&&<><details open><summary>Invitation preview · tentative recipient: {invitation.tentativeName}</summary><p className="whitespace-pre-wrap">{invitation.welcome}</p><div className="grid gap-4 md:grid-cols-2"><p lang="en" dir="ltr" className="whitespace-pre-wrap">{invitation.en}</p><p lang="ar" dir="rtl" className="whitespace-pre-wrap">{invitation.ar}</p></div></details>{!invitation.current&&<p role="status">The approved inputs changed. A coordinator must prepare a new preview.</p>}
        {coordinator&&<><button className={button} disabled={!invitation.current||invitation.redeemed} onClick={()=>void run('ISSUE_LOCAL_LINK')}>Prepare local portal link — no email</button>{link&&<label className="block text-sm">One-use local link (expires in 24 hours)<input readOnly value={link} className={input}/></label>}</>}
        {role==='Artist'&&!invitation.redeemed&&<><label className="block">Invitation token<input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} className={input}/></label><button className={button} disabled={!token||!invitation.current} onClick={()=>void run('REDEEM',{token,invitationId:invitation.id})}>Open my invitation</button></>}
        {role==='Artist'&&invitation.redeemed&&<><h3 className="font-semibold">Declare your identity</h3><p className="text-sm">Enter your legal name as it appears on your identity document. PR must review it before agreement preparation. Public display names are kept separately.</p><label>Legal name<input autoComplete="off" maxLength={200} value={legalName} onChange={e=>{setLegalName(e.target.value);changed();}} className={input}/></label><label>Public display name — English<input maxLength={200} value={en} onChange={e=>{setEn(e.target.value);changed();}} className={input}/></label><label>Public display name — Arabic<input lang="ar" dir="rtl" maxLength={200} value={ar} onChange={e=>{setAr(e.target.value);changed();}} className={input}/></label><button className={button} disabled={!legalName.trim()||!en.trim()||!ar.trim()} onClick={()=>void run('DECLARE_IDENTITY',{legalName,displayNameEn:en,displayNameAr:ar})}>Save identity declaration</button></>}
        {view.identity&&<p>Identity status: {view.identity.status.replaceAll('_',' ')}</p>}
        {role==='PR'&&view.identity?.status==='SELF_DECLARED'&&<><p>Declared legal name: {view.identity.legalName}</p><label>Reviewed evidence reference<input value={evidence} maxLength={300} onChange={e=>{setEvidence(e.target.value);changed();}} className={input}/></label><button disabled={!evidence.trim()} className={button} onClick={()=>void run('VERIFY_IDENTITY',{evidenceReference:evidence})}>Record local identity verification</button></>}
        {role==='Artist'&&view.identity&&invitation.redeemed&&<div className="space-y-2"><h3 className="font-semibold">Choose your submission route</h3>{invitation.routes.map((route:string)=><button key={route} className={button} disabled={!invitation.current||invitation.submissionRoute===route} onClick={()=>void run('CHOOSE_ROUTE',{route})}>{route==='COMMISSION'?'Propose a new commission':'Submit existing artwork'}</button>)}{invitation.submissionRoute&&<p>Selected: {invitation.submissionRoute.replaceAll('_',' ')}. Continue in Artist journey.</p>}</div>}
      </>}
    </fieldset>}
  </section>;
}
