import OperationalWorkspace from './OperationalWorkspace';
import { accountLabel, roleLabels, type Language } from '../lib/operationalWorkspace';
import ConnectedInvitation from './ConnectedInvitation';
import ConnectedTheme from './ConnectedTheme';
import ConnectedDispatch from './ConnectedDispatch';
import HeritageFields, { emptyHeritage } from './HeritageFields';
import { trackDemoState, trackDemoAction } from '../lib/demoReplay';
import AcquisitionPanel from './AcquisitionPanel';
import { useCallback, useEffect, useRef, useState } from 'react';
import SpatialPlanner from './SpatialPlanner';
import { ConservationRider, VenueClearance, ConditionPins, ConnectedBudgetGauge } from './MuseumCare';
const base='/api/review/ecosystem';
async function api(path:string,body?:unknown,method='POST') { const r=await fetch(path,{cache:'no-store',...(body?{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Object.assign(new Error(data.error??'Request failed'),{status:r.status});return data; }
const sampleImage=()=>new Blob([Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4XmN49vDSfwAI4wOZS6NgQwAAAABJRU5ErkJggg=='),c=>c.charCodeAt(0))],{type:'image/png'});
export default function ConnectedPilot(){
  const [workspace,setWorkspace]=useState<'operations'|'artwork'|'theme'|'invitation'>(window.location.hash.includes('token=')?'invitation':'operations');
  const [language,setLanguage]=useState<Language>('ar');
  const [connection,setConnection]=useState<'ok'|'session'|'offline'>('ok');
  const t=(ar:string,en:string)=>language==='ar'?ar:en;
  useEffect(()=>{const root=document.documentElement,oldLang=root.lang,oldDir=root.dir;root.lang=language;root.dir=language==='ar'?'rtl':'ltr';return()=>{root.lang=oldLang;root.dir=oldDir;};},[language]);
  const [submissionDetails,setSubmissionDetails]=useState({screenWidthCm:'',screenHeightCm:'',avRequirements:'',existingWorkWeightKg:'',packing:'',materials:'',fabrication:'',labour:''});
  const [heritage,setHeritage]=useState(emptyHeritage);
  const [session,setSession]=useState<any>(); const [data,setData]=useState<any>(); const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [checked,setChecked]=useState(false);const [dirty,setDirty]=useState(false);const [tick,setTick]=useState(0);
  const [operationsDirty,setOperationsDirty]=useState(false);
  const [operationsRecoverable,setOperationsRecoverable]=useState(false);
  const [title,setTitle]=useState('Kufic Horizon');const [concept,setConcept]=useState('A fictional bronze sculpture exploring architecture, calligraphy and the relationship between language and space.');const [file,setFile]=useState<File>();
  const [conservation,setConservation]=useState({max_lux:50,target_temp_c:20,target_humidity_pct:40});
  const readRequest=useRef(0);
  const guard=useCallback((value:boolean)=>setDirty(value),[]);
  const refresh=async()=>{const ticket=++readRequest.current;const view=await api('/api/review/pilot');if(ticket!==readRequest.current)return;setData(view);setConnection('ok');trackDemoState(view);if(workspace!=='operations')setChecked(false);setTick(n=>n+1);};
  useEffect(()=>{void api('/api/review/session').then(async s=>{setSession(s);if(s.actor?.role==='PREPARATORY_COMMITTEE_SPECTATOR'){window.location.replace('/committee-gallery');return;}if(s.actor){if(!['Logistics','Technical','Finance','Editorial','Chairman','General_Exhibition_Coordinator','Exhibition_Coordinator'].includes(s.actor.role))setWorkspace('artwork');await refresh();}}).catch(e=>setError(e.message));},[]);
  useEffect(()=>{if(!dirty&&(!operationsDirty||operationsRecoverable))return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,operationsDirty,operationsRecoverable]);
  const run=async(work:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setError('');try{const result=await work();if(result==='spectator'){window.location.assign('/committee-gallery');return;}trackDemoAction('workflow','completed');await refresh();setDirty(false);}catch(e){trackDemoAction('workflow','blocked');setError((e as Error).message);if((e as Error & {status?:number}).status===409){try{await refresh();}catch{/* Keep the original conflict visible. */}}}finally{setBusy(false);}};
  const revision=data?.revision; const actor=session?.actor; const command={artworkId:data?.artwork.id,versionHash:revision?.versionHash};
  useEffect(()=>{if(!actor)return;const update=()=>{if(!busy&&(workspace==='operations'||!dirty&&!operationsDirty))void refresh().catch(e=>setConnection(e.status===401?'session':'offline'));};const timer=window.setInterval(update,5000);window.addEventListener('focus',update);return()=>{clearInterval(timer);window.removeEventListener('focus',update);};},[actor?.id,dirty,operationsDirty,busy,workspace]);
  const onboarding=data?.onboarding;
  const invitation=onboarding?.invitation;
  const invitationFields=invitation?{targetDiscipline:invitation.discipline,participationRoute:invitation.submissionRoute,screenWidthCm:Number(submissionDetails.screenWidthCm),screenHeightCm:Number(submissionDetails.screenHeightCm),avRequirements:submissionDetails.avRequirements,existingWorkWeightKg:Number(submissionDetails.existingWorkWeightKg),packing:submissionDetails.packing,productionBudgetLines:(['materials','fabrication','labour'] as const).filter(k=>submissionDetails[k].trim().length>0).map(k=>({description:k,amountMinor:Math.round(Number(submissionDetails[k])*100)}))}:{};
  const mutate=(path:string,extra:object={})=>run(()=>api(base+path,{...command,...extra}));
  const action=(name:string,extra:object={})=>run(()=>api('/api/review/pilot/action',{version:data.version,action:name,checked,...extra}));
  const upload=async(path:string,metadata:unknown,blob:Blob)=>{const r=await fetch(base+path,{method:'POST',headers:{'Content-Type':'application/octet-stream','x-sadu-metadata':encodeURIComponent(JSON.stringify(metadata))},body:blob});const result=await r.json();if(!r.ok)throw new Error(result.error);return result;};
  const paymentBlock=(n:number)=>{if(data?.payments.some((p:any)=>p.tranche===n))return 'Recorded';if(!data?.agreement?.accepted||data.agreement.revisionId!==revision?.id)return 'Awaiting artist acceptance of current agreement';if(revision?.approvals.pr?.hash!==revision?.versionHash||revision?.approvals.technical?.hash!==revision?.versionHash)return 'Awaiting PR and Technical evidence';if(n>0&&!data.payments.some((p:any)=>p.tranche===n-1))return 'Awaiting prior tranche';if(n===1&&data.conditionClearance?.revisionId!==revision?.id)return 'Awaiting receipt and condition reconciliation';if(n===2&&data.returnClearance?.revisionId!==revision?.id)return 'Awaiting safe return';return '';};
  const b='rounded bg-[#8B261E] text-white p-3 disabled:opacity-40'; const card='rounded-xl border border-[#D9CEBA] bg-white p-5 space-y-3';
  return <main className="connected-shell" dir={language==='ar'?'rtl':'ltr'}><div>
    <header className="connected-header"><div><span className="connected-brand">{t('سدو','SADU')}</span><p className="text-sm">{t('مساحة العمل · تجربة محلية','Workspace · local rehearsal')}</p></div>
      <div className="connected-controls"><label>{t('الدور التجريبي','Simulation role')} <select disabled={busy||dirty||operationsDirty} value={actor?.id??''} onChange={e=>void run(async()=>{readRequest.current++;setData(undefined);const s=await api('/api/review/session',{accountId:e.target.value});setWorkspace(['Logistics','Technical','Finance','Editorial','Chairman','General_Exhibition_Coordinator','Exhibition_Coordinator'].includes(s.actor.role)?'operations':'artwork');setSession({...session,actor:s.actor});if(s.actor.role==='PREPARATORY_COMMITTEE_SPECTATOR')return 'spectator';})}><option value="" disabled>{t('اختر الدور','Choose account')}</option>{session?.accounts.map((a:any)=><option key={a.id} value={a.id}>{accountLabel(a,language)}</option>)}</select></label>
        <button type="button" onClick={()=>setLanguage(v=>v==='ar'?'en':'ar')} lang={language==='ar'?'en':'ar'}>{language==='ar'?'English':'العربية'}</button>
      </div>
    </header>
    {connection!=='ok'&&<div className="connected-connection" role="alert"><strong>{connection==='session'?t('انتهت جلسة الدور التجريبي. البيانات المعروضة محفوظة سابقاً.','Your local role session ended. The displayed record is cached.'):t('تعذر الاتصال. البيانات المعروضة قديمة ولا يمكن حفظ تغيير الآن.','Connection unavailable. Displayed information may be stale; changes cannot be saved.')}</strong><button disabled={busy} onClick={()=>void run(async()=>{if(connection==='session'){const s=await api('/api/review/session',{accountId:actor.id});setSession({...session,actor:s.actor});}})}>{connection==='session'?t('استعادة جلسة هذا الدور','Restore this role session'):t('إعادة الاتصال','Reconnect')}</button></div>}
    {error&&<p role="alert">{error}</p>}
    {actor&&<nav className="connected-nav" aria-label={t('مساحات العمل','Workspaces')}>{(['operations','artwork','theme','invitation'] as const).filter(w=>w!=='operations'||!!data?.operations).filter(w=>w!=='theme'||!['Artist','PR','Logistics','Technical','Finance'].includes(actor.role)).filter(w=>w!=='invitation'||['Artist','Exhibition_Coordinator','General_Exhibition_Coordinator','Director','PR'].includes(actor.role)).map(w=><button type="button" disabled={dirty||operationsDirty||busy} key={w} aria-pressed={workspace===w} onClick={()=>setWorkspace(w)}>{({operations:t('مهامي','My tasks'),artwork:t('ملف العمل','Work record'),theme:t('الموضوع والتحرير','Theme & editorial'),invitation:t('الدعوة والهوية','Invitation & identity')})[w]}</button>)}</nav>}
    {actor&&workspace==='operations'&&data?.operations&&<OperationalWorkspace key={actor.id} operations={data.operations} collection={data.collection} artworkId={data.artwork.id} artworkTitle={revision?.title} collectionLocked={data.artwork.physicalStatus!=='Pending_Shipment'} actor={actor} language={language} locked={busy||connection!=='ok'||!!data.artwork.acquisition||data.artwork.lifecycleStatus==='ARCHIVED_CLOSED'} onChanged={refresh} onDirtyChange={setOperationsDirty} onRecoverySafetyChange={setOperationsRecoverable}/>}
    {actor&&workspace==='operations'&&!data&&<p role="status">{t('جارٍ تحميل المهام…','Loading tasks…')}</p>}
    {actor&&workspace==='invitation'&&<ConnectedInvitation key={actor.id} role={actor.role} onChanged={refresh} onDirtyChange={guard}/>}
    {actor&&workspace==='theme'&&<ConnectedTheme key={actor.id} role={actor.role} onDirtyChange={guard}/>}
    {actor&&workspace==='artwork'&&<AcquisitionPanel key={actor.id} role={actor.role} artwork={data?.artwork} versionHash={revision?.versionHash} onChanged={refresh}/>}
    {data&&workspace==='artwork'&&<><section className={card} aria-label="Your next actions"><h2 className="text-xl font-semibold">Your next actions</h2>{data.nextActions?.length ? <ul className="space-y-3">{data.nextActions.map((task:{id?:string;artworkId?:string;owner:string;ownerId?:string;title:string;blocker:string;href?:string;deadline?:string;dueAt?:string;overdue?:boolean})=><li key={task.id??`${task.artworkId??data.artwork.id}-${task.title}`}><strong>{task.href?.match(/collection|packing|print|renewal/)?<button type="button" className="underline" onClick={()=>setWorkspace('operations')}>{task.title}</button>:task.href?<a href={task.href} className="underline">{task.title}</a>:task.title}</strong><p className="text-sm">Owner: {task.ownerId?(session?.accounts.find((a:{id:string})=>a.id===task.ownerId)?.name??task.ownerId):task.owner.replaceAll('_',' ')}</p>{task.dueAt&&<p className="text-sm">{task.overdue?'متأخر / Overdue · ':''}الموعد بتوقيت جهازك / Due in your device timezone: {new Date(task.dueAt).toLocaleString()}</p>}{task.deadline&&<p className="text-sm">Window ends: {task.deadline}</p>}{task.blocker&&<p className="text-sm">Waiting: {task.blocker}</p>}</li>)}</ul> : <p>No pending actions in this journey for your role.</p>}<p className="text-sm">Actions below are checked again by the server when submitted.</p></section><section className={card}><h2 className="text-xl font-semibold">{revision?.title.en??'Awaiting artist submission'}</h2><p>{revision?`Revision ${revision.sequence} · ${revision.state.replaceAll('_',' ')}`:'No artwork files submitted.'}</p>{data.artwork.lifecycleStatus==='ARCHIVED_CLOSED'&&<p role="status">ARCHIVED_CLOSED · Read-only historical record</p>}<p>Physical status: {data.artwork.physicalStatus.replaceAll('_',' ')}</p><p>Payments recorded: {data.payments.length} of 3 · {data.artwork.acquisition?'Permanent acquisition; return freight void':data.returnClearance?'Safe return reconciled':'Return clearance outstanding'}</p></section>
    {actor.role==='Artist'&&data.artwork.lifecycleStatus!=='ARCHIVED_CLOSED'&&<form className={card} onSubmit={e=>{e.preventDefault();void run(()=>upload('/submission',{artworkId:data.artwork.id,expectedRevisionId:revision?.id??null,...invitationFields,artistName:onboarding?.displayName??{en:'Noura Al Mazrouei',ar:'نورة المزروعي'},title:{en:title,ar:'أفق كوفي'},concept_text:concept,heritage,width_cm:120,height_cm:180,year:2026,conservation_reqs:conservation,technicalRequirements:[{item:'Projector',quantity:1,external:true}]},file??sampleImage()));}}><h2>Artwork submission</h2>{invitation&&<><p>Approved discipline: {invitation.discipline.replaceAll('_',' ')} · {invitation.submissionRoute?.replaceAll('_',' ')??'Choose your route in Invitation & identity'}</p>{(!invitation.current||!invitation.redeemed||!onboarding.displayName)&&<p>Complete the current invitation and identity declaration before submitting.</p>}{(invitation.discipline==='VIDEO_DIGITAL'?['screenWidthCm','screenHeightCm','avRequirements']:[]).concat(invitation.submissionRoute==='COMMISSION'?['materials','fabrication','labour']:['existingWorkWeightKg','packing']).map(key=><label className="block" key={key}>{({screenWidthCm:'Screen width (cm)',screenHeightCm:'Screen height (cm)',avRequirements:'Audiovisual requirements',existingWorkWeightKg:'Artwork weight (kg)',packing:'Packing specifications',materials:'Materials budget (AED)',fabrication:'Fabrication budget (AED)',labour:'Labour budget (AED)'} as Record<string,string>)[key]}<input className="block border p-2" value={submissionDetails[key as keyof typeof submissionDetails]} maxLength={1000} onChange={e=>{setSubmissionDetails({...submissionDetails,[key]:e.target.value});setDirty(true);}}/></label>)}</>}<label className="block">Artwork title<input required value={title} onChange={e=>{setTitle(e.target.value);setDirty(true);}} className="block border p-2"/></label><label className="block">Concept text<textarea required value={concept} onChange={e=>{setConcept(e.target.value);setDirty(true);}} className="block w-full border p-2"/></label><label className="block">{invitation?.submissionRoute==='COMMISSION'?'Concept sketch':'Reference image'}<input type="file" accept="image/png" onChange={e=>{setFile(e.target.files?.[0]);setDirty(true);}}/></label><p>{invitation?'A PNG image or concept sketch is required. Image quality still needs human review.':'Without a file this test uses a one-pixel PNG fixture, not print-ready artwork.'} Pilot dimensions: 120 × 180 cm. Fixed bilingual sample title and name.</p><HeritageFields value={heritage} actors={data.socialActors??[]} onChange={v=>{setHeritage(v);setDirty(true);}}/><ConservationRider value={conservation} onChange={v=>{setConservation(v);setDirty(true);}}/><button className={b} disabled={busy||revision?.state==='PUBLISHED'||!!(invitation&&(!invitation.current||!invitation.redeemed||!invitation.submissionRoute||!onboarding.displayName||!file))}>Submit artwork package</button></form>}
    {revision&&<>
    {data.dispatch&&<ConnectedDispatch key={`${actor.id}-${revision.id}`} view={data.dispatch} role={actor.role} version={data.version} versionHash={revision.versionHash} locked={revision.state!=='PUBLISHED'||!data.agreement?.accepted||data.artwork.lifecycleStatus==='ARCHIVED_CLOSED'||!['Pending_Shipment','In_Transit','Customs_Clearance'].includes(data.artwork.physicalStatus)} onChanged={refresh} onDirtyChange={guard}/>}
    {['Director','General_Exhibition_Coordinator'].includes(actor.role)&&<section className={card}><h2>Master archival record</h2><a className="underline block" href={`${base}/assertion/${data.artwork.id}`}>View safeguarding declaration for audit</a>{data.artwork.lifecycleStatus==='ARCHIVED_CLOSED'?<a className="underline" href={`${base}/archive/${data.artwork.id}.pdf`}>Download Master Archival Record / تحميل ملف الأرشيف الشامل</a>:<><p>{data.artwork.acquisition?'Permanent-collection closeout requires its own title, receipt and purchase reconciliation. Return-based closure does not apply.':'Available after return reconciliation and all three Finance clearances.'}</p>{actor.role==='Director'&&<button className={b} disabled={busy||!data.returnClearance||data.payments.length!==3} onClick={()=>void mutate('/archive-close')}>Archive &amp; close dossier</button>}</>}</section>}
    <fieldset className="contents" disabled={data.artwork.lifecycleStatus==='ARCHIVED_CLOSED'}>
    {actor.role==='Editorial'&&<section className={card}><h2>Editorial review</h2><p>{revision.concept_text}</p><p>Tags: {revision.curatorial_tags.join(', ')}</p><ul>{revision.Arabic_Terms.map((t:any)=><li key={t.dictionaryId}>{t.term}: {t.arabic} · suggestion only</li>)}</ul><button className={b} disabled={busy||revision.state!=='EDITORIAL_DRAFT'} onClick={()=>void mutate('/editorial',{description:{en:revision.concept_text,ar:'عمل تجريبي يجمع الخط والعمارة في تكوين برونزي.'}})}>Verify sample bilingual text</button></section>}
    {actor.role==='General_Exhibition_Coordinator'&&<><SpatialPlanner fixedWall key={`${revision.id}-${tick}`} role={actor.role} onDirtyChange={guard}/><section className={card}><button className={b} disabled={busy||dirty||revision.state!=='EXECUTIVE_REVIEW'} onClick={()=>void mutate('/ready')}>Ready for Director review</button><button className={b} disabled={busy||dirty||!!data.agreement} onClick={()=>void action('agreement')}>Record sample three-tranche agreement</button><p>Equipment requests: {data.requests.length} · External dispatch paused.</p></section></>}
    {actor.role==='Museum_Operations'&&<section className={card}><VenueClearance requirements={revision.conservation_reqs} capability={data.wall.climateCapability}/><button className={b} disabled={busy} onClick={()=>void mutate('/venue-clearance')}>Record venue clearance</button></section>}
    {actor.role==='Director'&&<section className={card}><button className={b} disabled={busy||!revision.approvals.coordinator||revision.state==='PUBLISHED'} onClick={()=>void mutate('/publish')}>Approve &amp; publish local snapshot</button><p>Publication creates a private digital twin and PDF label together.</p></section>}
    {actor.role==='Artist'&&<p>Sample agreement: AED 45,000; advance 30%, delivery 40%, completion after safe return 30%. This is a simulated acceptance, not a legal signature.</p>}
    {actor.role==='Artist'&&<button className={b} disabled={busy||!data.agreement||data.agreement.accepted} onClick={()=>void action('accept')}>Accept sample agreement — no legal signature</button>}
    {['PR','Technical','Logistics'].includes(actor.role)&&<label className="block"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/> I have reviewed the required fictional evidence for this action.</label>}
    {['PR','Technical'].includes(actor.role)&&<button className={b} disabled={busy||!checked} onClick={()=>void action(actor.role==='PR'?'pr':'technical')}>Record {actor.role} evidence</button>}
    {actor.role==='Logistics'&&<section className={card}><button className={b} disabled={busy} onClick={()=>void run(async()=>{if(data.simulatedLocation)return api('/api/review/pilot/simulated-arrival',command);const p=await new Promise<GeolocationPosition>((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,maximumAge:0,timeout:15000}));return api(base+'/arrival',{...command,location:{latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,timestamp:p.timestamp}},'PATCH');})}>{data.simulatedLocation?'Simulate museum receipt — test coordinates':'Record arrival — check GPS'}</button><ConditionPins key={revision.id} imageUrl="/api/review/pilot/media" pins={data.pins} onSave={async pin=>{await upload('/condition',{...command,x_pct:pin.x_pct,y_pct:pin.y_pct,description:pin.description},pin.photo);await refresh();}}/><button className={b} disabled={busy||!checked} onClick={()=>void action('condition-clear')}>Confirm condition reconciliation</button><button className={b} disabled={busy||!checked||!!data.artwork.acquisition} onClick={()=>void action('return')}>Record safe return &amp; closure</button></section>}
    {actor.role==='Finance'&&<section className={card}><h2>Finance authorization</h2><p>Sample agreement: AED 45,000 · 30% / 40% / 30%. No money is transferred.</p>{['Advance','Delivery','Completion after return'].map((name,n)=><div key={name}><button className={b} disabled={busy||!!paymentBlock(n)} onClick={()=>void action('pay',{tranche:n})}>Authorize {name}</button><p className="text-sm">{paymentBlock(n)||'Ready for Finance authorization'}</p></div>)}</section>}
    {['Director','General_Exhibition_Coordinator','Finance'].includes(actor.role)&&<ConnectedBudgetGauge key={tick}/>}
    </fieldset>
    <section className={card}><h2>Shared documents</h2><p>Source SHA-256: <code className="break-all">{revision.media.file_hash}</code></p><a className="underline block" href="/api/review/pilot/media">View submitted image</a>{revision.state==='PUBLISHED'&&<><a className="underline block" href="/api/review/pilot/label.pdf">Download gallery label</a>{!data.artwork.acquisition&&<p>Draft shipping documents are managed in Before shipping.</p>}{data.twins.filter((t:any)=>t.revisionId===revision.id).map((t:any)=><a key={t.id} className="underline block" href={t.uri}>Open private artwork &amp; audio guide</a>)}</>}</section>
    </>}
    <details className={card}><summary>Decision history · {data.decisions.length} entries</summary><ol>{data.decisions.map((d:any)=><li key={d.id}>{d.action} · {d.actorId} · {new Date(d.at).toLocaleString('en-GB')}</li>)}</ol></details>
    </>}
  </div></main>;
}
