import {workerNames,validWorkers,venueWorkBlock,type WorkActivity,type WorkLocation} from '../data/venueProtocols';
import {WorkerManifest} from './WorkerManifest';
import { VenueClearanceStep } from './VenueGovernance';
import { activeSpatialClaim, type SpatialClaim } from '../data/spatialClaims';
import { useEffect, useState } from 'react';
import { BellRing, Hammer, ClipboardList } from 'lucide-react';
import { useSessionDraft } from '../context/SessionDrafts';
import { addNudge, deadlineTime, MISSING_ITEMS, addFabrication, readyFabrication, type CuratorialNudge, type MissingItem, type FabricationTicket } from '../data/deliverableRouting';
const panel='my-4 space-y-3 rounded border border-[#D9CEBA] bg-[#F7F1E6] ps-4 pe-4 py-4 text-start';
const field='mt-2 block w-full rounded border bg-white ps-3 pe-3 py-2';
const button='rounded border border-[#8B261E] ps-4 pe-4 py-2 text-[#8B261E] disabled:opacity-50 disabled:cursor-not-allowed';
export function MissingDeliverables({artistId,artistName,isAr,canRequest=false}:{artistId:string;artistName?:string;isAr:boolean;canRequest?:boolean}) {
 const [rows,setRows]=useSessionDraft<CuratorialNudge[]>('curatorial-nudges:v1',[]);
 const [items,setItems]=useState<MissingItem[]>([]),[deadline,setDeadline]=useState(''),[now,setNow]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const requests=rows.filter(r=>r.artistId===artistId),t=(ar:string,en:string)=>isAr?ar:en;
 const duplicate=requests.some(r=>r.deadline===deadline&&[...r.items].sort().join()===[...items].sort().join());
 if(!canRequest&&!requests.length)return null;
 return <section className={panel}><h3 className="flex items-center gap-2 font-semibold"><BellRing aria-hidden="true" className="size-5"/>{t('طلب استكمال نواقص','Request Missing Deliverables')} · {artistName}</h3>
 {canRequest&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();setRows(prev=>addNudge(prev,{id:crypto.randomUUID(),artistId,items,deadline,createdAt:new Date().toISOString()},'HIP'));}}><fieldset><legend>{t('المواد المطلوبة','Missing items')}</legend>{(Object.keys(MISSING_ITEMS) as MissingItem[]).map(i=><label key={i} className="my-2 flex items-center gap-2"><input type="checkbox" checked={items.includes(i)} onChange={e=>setItems(prev=>e.target.checked?[...prev,i]:prev.filter(x=>x!==i))}/>{MISSING_ITEMS[i][isAr?'ar':'en']}</label>)}</fieldset><label className="block">{t('الموعد العاجل — نهاية اليوم بتوقيت الإمارات','Urgent Deadline — end of day, UAE time')}<input required type="date" className={field} value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><button className={button} disabled={!items.length||!Number.isFinite(deadlineTime(deadline))||deadlineTime(deadline)<=now||duplicate}>{t('إرسال تنبيه عاجل','Send urgent nudge')}</button></form>}
 {requests.map(r=>{const remaining=deadlineTime(r.deadline)-now,seconds=Math.floor(Math.abs(remaining)/1000);return <article key={r.id} className="space-y-2 rounded border border-red-300 bg-red-50 ps-4 pe-4 py-4"><p className="font-semibold text-red-900">{t('أولوية عالية — نواقص مطلوبة','HIGH PRIORITY — missing deliverables')}</p><ul className="list-inside list-disc">{r.items.map(i=><li key={i}>{MISSING_ITEMS[i][isAr?'ar':'en']}</li>)}</ul><p><time dateTime={r.deadline}>{r.deadline}</time> · 23:59 UAE</p><p className="font-mono">{remaining<0?t('متأخر','Overdue'):t('متبقي','Remaining')}: {Math.floor(seconds/86400)}d {Math.floor(seconds%86400/3600)}h {Math.floor(seconds%3600/60)}m {seconds%60}s</p><p className="text-xs">{t('إشعار داخل جلسة المحاكاة؛ لا بريد خارجي.','In-session notification; no external email.')}</p></article>})}</section>;
}
export function FabricationLedger({artistId,artistName,isAr,actor,blocked=false}:{artistId:string;artistName?:string;isAr:boolean;actor:'COORDINATOR'|'TECHNICAL';blocked?:boolean}) {
 const [claims]=useSessionDraft<SpatialClaim[]>('spatial-claims:biennial-2026',[]);
 const claim=activeSpatialClaim(claims,artistId);
 const [rows,setRows]=useSessionDraft<FabricationTicket[]>(`fabrication:${artistId}`,[]);
 const [workers,setWorkers]=useState('');
 const [activity,setActivity]=useState<WorkActivity>('CARPENTRY'),[workLocation,setWorkLocation]=useState<WorkLocation>('INSIDE_HALL');
 const protocolBlock=venueWorkBlock(claim?.venueId,activity,workLocation);
 const [route,setRoute]=useState(''),[item,setItem]=useState(''),[vendor,setVendor]=useState(''),[disposition,setDisposition]=useState<'RETURN_TO_ARTIST'|'DISCARD'>('RETURN_TO_ARTIST');
 const t=(ar:string,en:string)=>isAr?ar:en;
 const duplicate=rows.some(r=>r.item.toLowerCase()===item.trim().toLowerCase()&&r.vendor.toLowerCase()===vendor.trim().toLowerCase());
 return <section className={panel}><h3 className="flex items-center gap-2 font-semibold"><Hammer aria-hidden="true" className="size-5"/>{t('أمر تصنيع خارجي','Third-Party Fabrication / Vendor Order')} · {artistName}</h3>
 {blocked&&<p role="status" className="text-red-900">{t('التنفيذ مقفل بسبب حجز العمل.','Execution is locked by the artwork hold.')}</p>}
 {actor==='COORDINATOR'&&<><label className="block">{t('مسار الطلب','Request track')}<select disabled={blocked} className={field} value={route} onChange={e=>setRoute(e.target.value)}><option value="">{t('اختر المسار','Select track')}</option><option value="fabrication">{t('تصنيع خارجي / أمر مورد','Third-Party Fabrication / Vendor Order')}</option></select></label>{route==='fabrication'&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();setRows(prev=>addFabrication(prev,{id:crypto.randomUUID(),artistId,item,vendor,workers:workerNames(workers),venueId:claim?.venueId,activity,workLocation,disposition,status:'PENDING_FABRICATION',createdAt:new Date().toISOString()},actor,blocked,claims));}}><fieldset disabled={blocked} className="space-y-3"><label className="block">{t('العنصر المطلوب تصنيعه','Fabricated Item')}<input required maxLength={250} className={field} value={item} onChange={e=>setItem(e.target.value)}/></label><label className="block">{t('المورد / الفني المكلّف','Assigned Vendor/Technician')}<input required maxLength={200} className={field} value={vendor} onChange={e=>setVendor(e.target.value)}/></label><label className="block">Assigned personnel — one full name per line<textarea required maxLength={15000} className={field} value={workers} onChange={e=>setWorkers(e.target.value)}/></label><label className="block">Work activity<select className={field} value={activity} onChange={e=>setActivity(e.target.value as WorkActivity)}><option value="INSTALLATION">Installation</option><option value="WELDING">Welding</option><option value="CARPENTRY">Carpentry</option></select></label><label className="block">Work location<select className={field} value={workLocation} onChange={e=>setWorkLocation(e.target.value as WorkLocation)}><option value="INSIDE_HALL">Inside exhibition hall</option><option value="OUTSIDE_HALL">Outside exhibition hall</option></select></label>{protocolBlock&&<p role="alert" className="text-red-800">{protocolBlock}</p>}<fieldset><legend>{t('مصير الأصل','Original Asset Disposition')}</legend>{(['RETURN_TO_ARTIST','DISCARD'] as const).map(v=><label key={v} className="my-2 flex items-center gap-2"><input type="radio" checked={disposition===v} onChange={()=>setDisposition(v)}/>{v==='DISCARD'?t('التخلص من الأصل','Discard'):t('إعادة الأصل إلى الفنان','Return original to artist')}</label>)}</fieldset><p className="text-xs">{t('تسجيل تعليمات فقط؛ لا إذن إتلاف ولا طلب خارجي فعلي.','Instruction record only; no disposal authorization or external order.')}</p><button className={button} disabled={!item.trim()||!vendor.trim()||duplicate||Boolean(protocolBlock)||!claim||!validWorkers(workerNames(workers))}>{t('تسجيل أمر التصنيع','Record fabrication order')}</button></fieldset></form>}</>}
 <WorkerManifest artistId={artistId} venueId={claim?.venueId??''}/><h4 className="flex items-center gap-2"><ClipboardList aria-hidden="true" className="size-4"/>{t('سجل التنفيذ','Execution Ledger')}</h4>{!rows.length&&<p>{t('لا توجد أوامر تصنيع.','No fabrication orders.')}</p>}{rows.map(r=><article key={r.id} className="space-y-2 rounded border bg-white ps-4 pe-4 py-4"><h5 className="font-semibold">{r.item} · {r.vendor}</h5><p>{r.disposition} · {r.activity??'Activity not recorded'} · {r.workLocation??'Location not recorded'}</p><p role="status">{r.status==='READY_FOR_INSTALL'?'Fabrication ready — venue approval required':r.status}</p><VenueClearanceStep ticket={{id:`fabrication:${artistId}:${r.id}`,artistId,title:r.item,venueId:claim?.venueId??'',authority:claim?.curator??'',coordinator:claim?.coordinatorName??'Assigned Coordinator',vendor:r.vendor,constraints:['Requires floor protection carpet','Visitor safety perimeter base'],blocked:blocked||!claim||r.status!=='READY_FOR_INSTALL'}}/><p className="text-xs">{r.readyAt??r.createdAt}</p>{actor==='TECHNICAL'&&r.status==='PENDING_FABRICATION'&&<button disabled={blocked} className={button} onClick={()=>setRows(prev=>readyFabrication(prev,r.id,actor,new Date().toISOString(),blocked))}>{t('تسجيل الجاهزية للتركيب','Record ready for installation')}</button>}<p className="text-xs">{t('الجاهزية لا تستبدل تصريح الموقع أو اعتماد المالية.','Readiness does not replace venue or Finance clearance.')}</p></article>)}</section>;
}
