import {useEffect, useRef} from 'react';
import type {WorkspaceDraft, DraftComparison as Comparison} from '../lib/workspaceDraft';
import {taskTitles,type Language,type WorkspaceTask} from '../lib/operationalWorkspace';
import DraftComparison from './DraftComparison';

const labels:Record<string,[string,string]>={pickupDate:['موعد الاستلام','Pickup date'],note:['ملاحظات الفحص','Inspection notes'],reference:['مرجع الإثبات','Evidence reference'],reason:['السبب','Reason'],address:['العنوان','Address'],city:['المدينة','City'],country:['البلد','Country'],contact:['جهة الاتصال','Contact'],sourceRef:['مرجع المصدر','Source reference'],timezone:['المنطقة الزمنية','Timezone'],start:['الإتاحة من','Available from'],end:['الإتاحة إلى','Available until'],closures:['فترات الإغلاق','Closure periods'],conflict:['تعارض المصدر','Source conflict'],specification:['مواصفات التغليف','Packing specification'],packingOwner:['مسؤول التغليف','Packing owner'],amount:['التكلفة','Cost'],technical:['المراجعة الفنية','Technical review'],technicalReason:['سبب الاستثناء الفني','Technical exception reason'],evidenceId:['مرجع الملف','File reference'],supplier:['المورد','Supplier'],quantity:['الكمية','Quantity'],size:['المقاس','Size'],stock:['الخامة','Stock'],finishing:['التشطيب','Finishing'],profile:['مواصفات الفحص','Inspection profile'],deliveryDate:['تاريخ التسليم','Delivery date'],sender:['المرسل','Sender'],receivedAt:['تاريخ الاستلام','Received time'],deliveryId:['مرجع التسليم','Delivery reference'],primaryId:['المسؤول الأساسي','Primary owner'],backupId:['المسؤول البديل','Backup owner'],active:['المسؤول الحالي','Active owner'],ownerId:['المسؤول','Owner'],dueAt:['الموعد النهائي','Deadline'],source:['المصدر','Source']};
const extraLabels:Record<string,[string,string]>={activeId:['المسؤول الحالي','Active owner'],acceptedBy:['قبول المسؤولية','Accepted by'],printRevision:['إصدار الطباعة','Print revision'],sourceCheck:['تأكيد المصدر','Source confirmation'],technicalCheck:['المراجعة الفنية','Technical review'],costCheck:['اعتماد التكلفة','Cost approval'],packingCheck:['فحص التغليف','Packing inspection'],preflightCheck:['فحص ملف الطباعة','Print preflight'],editorialCheck:['مراجعة التحرير','Editorial review'],executiveCheck:['اعتماد الطباعة','Print authorization'],supplierCheck:['تأكيد المورد','Supplier acknowledgment'],correctionReason:['سبب تعليق الطباعة','Print correction reason'],status:['حالة المهمة','Task status']};
const states:Record<string,[string,string]>={complete:['مكتمل','Complete'],pending:['مطلوب','Pending'],hold:['معلّق','On hold'],notRequired:['غير مطلوب بسبب موثق','Not required, with reason'],UNASSIGNED:['لم يُعيّن مسؤول','Unassigned'],ASSIGNED:['بانتظار قبول المسؤول','Awaiting acceptance'],ACCEPTED:['قبل المسؤول المهمة','Owner accepted'],RETURNED:['أعيدت للمنسقة','Returned to coordinator'],COMPLETE:['مكتمل','Complete'],NOT_REQUIRED:['غير مطلوب بسبب موثق','Not required, with reason']};
export default function DraftRecovery({language,status,candidate,canResume,onResume,onDiscard,onReload,busy,dirty,references,comparison=null,version,tasks=[]}:{language:Language;status:string;candidate:WorkspaceDraft|null;canResume:boolean;onResume:()=>void;onDiscard:()=>void;onReload:()=>void;busy:boolean;dirty:boolean;references:Record<string,string>;comparison?:Comparison|null;version?:number;tasks?:WorkspaceTask[]}) {
  const titleRef=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{if(candidate){titleRef.current?.focus({preventScroll:true});titleRef.current?.scrollIntoView({block:'start'});}},[candidate?.taskId]);
  const t=(ar:string,en:string)=>language==='ar'?ar:en;
  const label=(key:string):string=>{const parts=key.split('.');if(parts[0]==='task')return `${taskTitles[parts[1]]?.[language]??parts[1]} · ${label(parts[2])}`;return (labels[key]??extraLabels[key])?.[language==='ar'?0:1]??key;};
  const display=(key:string,value:string)=>{
    if(!value)return t('غير مسجل','Not recorded');
    key=key.split('.').at(-1)!;
    if(['evidenceId','deliveryId','ownerId','primaryId','backupId','activeId','acceptedBy'].includes(key))return references[value]??t('مرجع سابق غير متاح في العرض الحالي','Earlier reference unavailable in this view');
    if(key==='status'||key.endsWith('Check'))return states[value]?.[language==='ar'?0:1]??value;
    if(key==='dueAt'&&Number.isFinite(Date.parse(value)))return new Date(value).toLocaleString(language==='ar'?'ar-AE':'en-GB');
    if(key==='conflict')return value==='true'?t('نعم','Yes'):t('لا','No');
    if(key==='technical')return value==='yes'?t('مطلوبة','Required'):t('غير مطلوبة','Not required');
    if(key==='active')return value==='primary'?t('المسؤول الأساسي','Primary owner'):t('المسؤول البديل','Backup owner');
    if(key==='closures'){try{const rows=JSON.parse(value);if(Array.isArray(rows))return rows.length?rows.map(c=>`${c.start} → ${c.end}`).join(' · '):t('لا توجد','None');}catch{return t('راجع فترات الإغلاق','Review closure periods');}}
    return value;
  };
  if(candidate)return <div className="work-recovery" role="region" aria-label={t('استعادة المسودة','Draft recovery')}>
    <h3 ref={titleRef} tabIndex={-1}>{t('لديك مسودة خاصة محفوظة','You have a saved private draft')} · {taskTitles[candidate.key]?.[language]}</h3>
    <p>{candidate.savedAt&&new Date(candidate.savedAt).toLocaleString(language==='ar'?'ar-AE':'en-GB')} · {t('هذه المسودة لم تغيّر السجل المشترك','This draft has not changed the shared record')}</p>
    {!canResume&&(candidate.attempted||candidate.baseVersion===version)&&<p role="status">{candidate.attempted?t('سبق محاولة إرسال هذه المسودة. راجع السجل الحالي قبل بدء إجراء جديد؛ لن نعيد إرسالها.','Submission was attempted. Check the current record before starting a new action; this draft will not be replayed.'):t('تغيّرت صلاحية المهمة. النص متاح للمراجعة فقط.','Task permission changed. This text is for reference only.')}</p>}
    {version!==undefined&&candidate.baseVersion!==version&&<DraftComparison comparison={comparison} draft={candidate} version={version} language={language} tasks={tasks} references={references} label={label} display={display}/>}
    <details><summary>{t('عرض الإدخال المحفوظ','Inspect saved input')}</summary><dl>{Object.entries(candidate.fields).filter(([,v])=>v).map(([key,value])=><div key={key}><dt>{label(key)}</dt><dd dir="auto">{display(key,value)}</dd></div>)}{candidate.fileName&&<div><dt>{t('ملف يحتاج إلى إعادة إرفاق','File to reattach')}</dt><dd dir="auto">{candidate.fileName}</dd></div>}</dl></details>
    <div className="work-recovery-actions">{canResume&&<button className="work-secondary" disabled={busy||status==='loading'} onClick={onResume}>{dirty?t('استبدال الإدخال بهذه المسودة','Replace input with saved draft'):t('استئناف المسودة','Resume draft')}</button>}<button className="work-link" disabled={busy||status==='loading'} onClick={onDiscard}>{t('تجاهل المسودة وفتح السجل الحالي','Discard draft and open current record')}</button></div>
  </div>;
  if(status==='error'||status==='conflict')return <div className="work-alert" role="alert"><strong>{status==='conflict'?t('تغيّرت المسودة في نافذة أخرى','The draft changed in another tab'):t('تعذر تأكيد حفظ المسودة','Draft saving could not be confirmed')}</strong><p>{t('إدخالك باقٍ هنا. راجع النسخة المحفوظة قبل المتابعة.','Your input remains here. Review the saved copy before continuing.')}</p><button className="work-secondary" disabled={busy} onClick={onReload}>{t('مراجعة المسودة المحفوظة','Review saved draft')}</button></div>;
  if(status==='loading')return <p role="status" className="work-hint">{t('جارٍ التحقق من مسودتك الخاصة…','Checking your private draft…')}</p>;
  return null;
}
