import { useEffect, useState } from 'react';
import '@fontsource/amiri/400.css';
import './ExecutiveLanding.css';
import GuidedPresentation from './GuidedPresentation';
import PitchCollectionDemo from './PitchCollectionDemo';
import PitchPrintDemo from './PitchPrintDemo';
import { ClientPresentation, TechnicalExplainer } from './ClientProposal';
import PitchCuratorialDemo from './PitchCuratorialDemo';

const chapters = [
  {name:'Direction',ar:'الرؤية',owner:'Chairman · Director · Committee',title:'Begin with an agreed direction.',body:'Develop the theme in a shared bilingual workspace. Preserve the exact version authorized for publication.',output:'Approved theme and its decision history',boundary:'Planning can begin before the final publication text is ready.'},
  {name:'Curation',ar:'الاختيار',owner:'Committee · General Coordinator',title:'Bring artistic judgment and physical space together.',body:'Connect proposals to the curatorial brief, available spaces and their technical requirements.',output:'A reasoned recommendation and proposed allocation',boundary:'A Committee recommendation remains separate from executive approval.'},
  {name:'Invitation',ar:'الدعوة',owner:'Coordinator · Artist',title:'Invite with clarity. Collect information once.',body:'Carry the approved theme and discipline into the invitation. The artist confirms their details and submits within the agreed scope.',output:'A version-linked invitation and artist response',boundary:'A simulated invitation is not a sent email or an executed agreement.'},
  {name:'Delivery',ar:'التنفيذ',owner:'Logistics · Technical · General Coordinator',title:'Make the next action unmistakable.',body:'Keep collection details, availability, source references and ownership together. A change reopens only the checks that depend on it.',output:'A confirmed collection record and attributed handoff',boundary:'A pickup plan does not book transport or authorize payment.'},
  {name:'Legacy',ar:'الأرشيف',owner:'Logistics · Finance · General Coordinator',title:'Close the exhibition. Keep the knowledge.',body:'Bring condition evidence, return records and outstanding obligations into view before closing the dossier.',output:'A traceable closeout record',boundary:'Financial clearance and physical receipt retain separate authorities.'},
];
export default function ExecutiveLanding() {
  const detailed = new URLSearchParams(window.location.search).get('view') === 'explore';
  return detailed ? <DetailedOverview /> : <GuidedPresentation />;
}
function DetailedOverview() {
  const [chapter,setChapter]=useState(0);
  useEffect(()=>{document.title='SADU — More room for the art';},[]);
  const phase=chapters[chapter];
  return <div className="sadu-executive" lang="en" dir="ltr">
    <a className="sadu-skip" href="#pitch-content">Skip to presentation</a>
    <header className="sadu-header"><a className="sadu-brand" href="#top" aria-label="SADU home"><span lang="ar" dir="rtl">سدو</span><span>SADU<small>CULTURAL WORK, CONNECTED</small></span></a><nav aria-label="Presentation navigation"><a href="/overview">العرض الموجّه / Guided tour</a><a href="#top">Overview</a><a href="#presentation">Presentation</a><a href="#prototype">Prototype</a><a href="#technical">Technical</a><a href="#next">Next step</a></nav><span className="sadu-private">PRIVATE PRESENTATION</span></header>
    <main id="pitch-content">
      <section id="top" className="sadu-hero">
        <div className="sadu-hero-copy"><p className="sadu-eyebrow">BUILT AROUND THE PEOPLE BEHIND AN EXHIBITION</p><h1>More room<br/>for <em>the art.</em></h1><p className="sadu-lead">A clearer path for the decisions,<br className="sadu-wide-break"/> people and details that bring it to life.</p><p className="sadu-hero-note">SADU is designed to connect exhibition work from the first curatorial brief to the final return—with clear ownership at every handoff.</p><div className="sadu-actions"><a className="sadu-cta" href="#presentation">Start the presentation <span aria-hidden="true">↗</span></a><a className="sadu-text-link" href="#journey">Explore the whole journey ↓</a></div><p className="sadu-prototype-note">Functional prototype · Separate synthetic workflow examples · Live integrations paused</p></div>
        <div className="sadu-thread-map" aria-label="Illustration: people and evidence connected through an exhibition record"><div className="sadu-map-caption">THE INSTITUTIONAL THREAD <span>01 — 05</span></div><svg viewBox="0 0 520 470" fill="none" aria-hidden="true"><g stroke="#DEC08D" strokeWidth="1"><path d="M45 50H190Q260 50 260 120V355Q260 420 330 420H480"/><path d="M475 60H340Q260 60 260 140V355Q260 390 185 390H45"/><path d="M45 180H475M45 285H475" opacity=".3"/><path d="M140 20V445M390 20V445" opacity=".12"/></g>{[100,185,280,375].map(y=><g key={y}><circle cx="260" cy={y} r="13" fill="#152335" stroke="#DEC08D"/><circle cx="260" cy={y} r="4" fill="#DEC08D"/></g>)}</svg><div className="sadu-map-note sadu-map-note-a"><small>CURATORIAL INTENT</small><strong>A shared direction.</strong></div><div className="sadu-map-note sadu-map-note-b"><small>THE ARTIST’S RECORD</small><strong>A preserved version.</strong></div><div className="sadu-map-note sadu-map-note-c"><small>OPERATIONAL HANDOFF</small><strong>A named next owner.</strong></div><div className="sadu-map-note sadu-map-note-d"><small>INSTITUTIONAL MEMORY</small><strong>A traceable decision.</strong></div><p className="sadu-map-foot" lang="ar" dir="rtl">خيوط العمل، في مسار واحد.</p></div>
      </section>
      <div className="sadu-principles"><span>Traceable decisions</span><span>Distinct approval authorities</span><span>Visible next actions</span></div>
      <ClientPresentation />
      <section className="sadu-section sadu-shift"><div><p className="sadu-eyebrow">01 / THE OPPORTUNITY</p><h2>Let coordination<br/><em>serve curation.</em></h2></div><div><p>An exhibition moves through many hands. Each handoff should carry the current information, the decision behind it, and a clear next step.</p><p>SADU makes those connections visible—so teams spend less effort reconstructing the story and more attention on the exhibition.</p><div className="sadu-before-after"><div><small>WHEN INFORMATION IS FRAGMENTED</small><p>Which file is current?<br/>Who confirmed the address?<br/>Who takes over now?</p></div><div><small>THE PROPOSED WORKING EXPERIENCE</small><p>The current revision.<br/>Its source and confirmation.<br/>The responsible next owner.</p></div></div></div></section>
      <section id="journey" className="sadu-section sadu-journey"><div className="sadu-section-heading"><div><p className="sadu-eyebrow">02 / ONE CONTINUOUS JOURNEY</p><h2>Many responsibilities.<br/><em>A shared direction.</em></h2></div><p>Explore the handoffs. Each team keeps its own authority; the record connects their work.</p></div><div className="sadu-chapters" aria-label="Explore exhibition phases">{chapters.map((c,i)=><button key={c.name} aria-pressed={chapter===i} aria-controls="phase-detail" onClick={()=>setChapter(i)}><small>0{i+1}</small><strong>{c.name}</strong><span lang="ar" dir="rtl">{c.ar}</span></button>)}</div><div id="phase-detail" className="sadu-phase-detail" aria-live="polite"><div><p className="sadu-eyebrow">{phase.owner}</p><h3>{phase.title}</h3><p>{phase.body}</p></div><div className="sadu-phase-output"><small>WHAT PASSES FORWARD</small><strong>{phase.output}</strong><p>{phase.boundary}</p></div></div></section>
      <nav id="prototype" className="sadu-demo-index" aria-label="Demonstration navigation"><span>Explore a working example</span><a href="#curatorial-handoff">1 · Curatorial review</a><a href="#experience">2 · Collection readiness</a><a href="#print-release">3 · Print release</a></nav>
      <PitchCuratorialDemo /><a className="sadu-demo-return" href="#presentation">Return to presentation ↑</a>
      <PitchCollectionDemo /><a className="sadu-demo-return" href="#presentation">Return to presentation ↑</a>
      <PitchPrintDemo /><a className="sadu-demo-return" href="#presentation">Return to presentation ↑</a>
      <TechnicalExplainer />
      <section className="sadu-section sadu-proof"><div><p className="sadu-eyebrow">04 / SUBSTANCE BEHIND THE EXPERIENCE</p><h2>Confidence comes<br/>from <em>clear boundaries.</em></h2><p>The collection handoff has been exercised in local backend and browser tests. Institutional readiness remains a separate assessment.</p></div><div className="sadu-proof-list"><article><span>01</span><div><h3>Changes keep their history.</h3><p>A revised address preserves the earlier record and reopens the checks that depend on it.</p></div></article><article><span>02</span><div><h3>Responsibility follows the handoff.</h3><p>Only the active Logistics owner can edit. The Coordinator assigns the backup with a recorded reason.</p></div></article><article><span>03</span><div><h3>Planning stays distinct from execution.</h3><p>A valid date creates a local plan. It does not book freight or authorize a financial release.</p></div></article></div></section>
      <section id="next" className="sadu-section sadu-next"><p className="sadu-eyebrow">05 / A PRACTICAL PATH FORWARD</p><h2>Start with one journey.<br/><em>Earn the next step.</em></h2><div className="sadu-roadmap"><article><small>NOW</small><h3>Demonstrate the workflow</h3><p>Refine the presentation and exercise a bounded, synthetic scenario.</p></article><article><small>WITH THE INSTITUTION</small><h3>Confirm the requirements</h3><p>Validate responsibilities, hosting, identity, retention and support with the relevant teams.</p></article><article><small>AFTER AGREEMENT</small><h3>Run a supervised pilot</h3><p>Measure staff effort, missing information and rework against an agreed baseline.</p></article></div><div className="sadu-closing"><p>A focused demonstration today.<br/>An evidence-led implementation decision next.</p><a className="sadu-cta" href="#experience">Try the collection demonstration <span aria-hidden="true">↗</span></a></div><details className="sadu-readiness"><summary>What is—and is not—connected?</summary><p>This page explains the proposed exhibition journey. These examples save synthetic steps in this browser tab; refresh and unlock can resume them when tab storage is available. They are separate workflow examples, not a shared live dossier. The local backend persists collection records and uses the same packing and readiness rules. Other workspaces have different persistence boundaries. Institutional identity, government storage, live communications, shipping and payments require separately scoped integration and validation. Operational savings have not yet been measured.</p></details></section>
    </main><footer className="sadu-footer"><a className="sadu-brand" href="#top"><span lang="ar" dir="rtl">سدو</span><span>SADU<small>MORE ROOM FOR THE ART</small></span></a><p>Exhibition workflow prototype<br/>Prepared for discussion · No government endorsement is represented.</p><a href="#top">Back to top ↑</a></footer>
  </div>;
}
