import { isLocalPreview } from '../lib/previewRoutes';
import { useEffect, useRef, useState } from 'react';
import './ExecutiveLanding.css';
function Weave({ compact = false }: { compact?: boolean }) {
  return <svg className={`sadu-weave ${compact ? 'sadu-weave-small' : ''}`} viewBox="0 0 600 600" fill="none" aria-hidden="true">
    <defs><linearGradient id={compact ? 'thread-small' : 'thread-hero'} x1="0" y1="0" x2="600" y2="600" gradientUnits="userSpaceOnUse"><stop stopColor="#A94048"/><stop offset=".5" stopColor="#E2C38C"/><stop offset="1" stopColor="#568A9E"/></linearGradient></defs>
    <g stroke={`url(#${compact ? 'thread-small' : 'thread-hero'})`} strokeWidth="1.2">
      {Array.from({ length: 15 }, (_, i) => <path key={i} className="sadu-thread" style={{ animationDelay: `${i * -0.4}s` }} d={`M ${50+i*13} 40 L ${560-i*13} 550 M 40 ${50+i*13} L 550 ${560-i*13}`}/>)}
      {[250,205,160,115].map((r,i) => <path key={r} className="sadu-diamond" style={{ animationDelay: `${i * -.8}s` }} d={`M300 ${300-r} L${300+r} 300 L300 ${300+r} L${300-r} 300 Z`}/>)}
      <rect x="260" y="260" width="80" height="80" rx="8" fill="#101F32" strokeWidth="2"/>
      {[275,290,310,325].map(p => <path key={p} d={`M${p} 240V260 M${p} 340V360 M240 ${p}H260 M340 ${p}H360`}/>)}
      <path d="M280 300L300 280L320 300L300 320Z" strokeWidth="3"/>
    </g>
    {[['300','50'],['550','300'],['300','550'],['50','300']].map(([cx,cy]) => <circle key={cx+cy} cx={cx} cy={cy} r="4" fill="#E2C38C"/>)}
  </svg>;
}
function Counter({ value, label, detail }: { value: number; label: string; detail: string }) {
  const ref = useRef<HTMLDivElement>(null); const [count,setCount] = useState(value);
  useEffect(() => {
    if (matchMedia('(prefers-reduced-motion: reduce)').matches || !('IntersectionObserver' in window)) return;
    let frame = 0;
    const observer = new IntersectionObserver(entries => { if (!entries[0].isIntersecting) return; observer.disconnect(); const start = performance.now(); const draw = (now:number) => { const progress = Math.min((now-start)/1100,1); setCount(Math.round(value * (1-Math.pow(1-progress,3)))); if(progress<1) frame=requestAnimationFrame(draw); }; frame=requestAnimationFrame(draw); },{threshold:.5});
    if(ref.current) observer.observe(ref.current);return()=>{observer.disconnect();cancelAnimationFrame(frame);};
  },[value]);
  return <div ref={ref} className="sadu-metric"><span className="sadu-number" aria-hidden="true">{String(count).padStart(2,'0')}</span><span className="sr-only">{value}</span><h3>{label}</h3><p>{detail}</p></div>;
}
export default function ExecutiveLanding() {
  const root=useRef<HTMLDivElement>(null);
  const local = isLocalPreview(window.location.hostname);
  const [paused, setPaused] = useState(false);
  useEffect(()=>{
    document.title='SADU — A connected exhibition journey';
    if(!root.current || matchMedia('(prefers-reduced-motion: reduce)').matches || !('IntersectionObserver' in window)) return;
    const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target);}}),{threshold:.12});
    const nodes=root.current.querySelectorAll('.sadu-reveal');nodes.forEach(n=>{n.classList.add('will-reveal');observer.observe(n);});return()=>{observer.disconnect();nodes.forEach(n=>n.classList.remove('will-reveal'));};
  },[]);
  return <div className={`sadu-executive ${paused ? 'sadu-motion-paused' : ''}`} ref={root} lang="en" dir="ltr">
    <a className="sadu-skip" href="#executive-content">Skip to presentation</a>
    <div className="sadu-institutional"><span>SDC LOGO <small>Official asset placeholder</small></span><span>SHARJAH GOVERNMENT BADGE <small>Official asset placeholder</small></span></div>
    <header className="sadu-header"><a className="sadu-brand" href="#top" aria-label="SADU home"><span className="sadu-mark">◈</span><span>SADU<small>EXHIBITION INTELLIGENCE</small></span></a><nav aria-label="Presentation navigation"><a href="#approach">The approach</a><a href="#capabilities">Capabilities</a><a href="#gateway">Explore SADU <span aria-hidden="true">↗</span></a></nav><button className="sadu-motion-toggle" aria-pressed={paused} onClick={() => setPaused(v => !v)}>{paused ? 'Resume background motion' : 'Pause background motion'}</button></header>
    <main id="executive-content">
      <section id="top" className="sadu-hero"><div className="sadu-hero-copy"><p className="sadu-eyebrow"><span/> FROM CULTURAL HERITAGE TO CONNECTED WORK</p><h1>Securing our<br/>heritage.<br/><em>Unifying our<br/>future.</em></h1><p className="sadu-lead">SADU: Secure Architecture for Data Unification.</p><p className="sadu-hero-note">A fictional demonstration of the people, decisions and details behind an exhibition.</p><a className="sadu-cta" href="#approach">Discover the architecture <span aria-hidden="true">↓</span></a></div><div className="sadu-hero-art"><div className="sadu-orbit"/><Weave/><span className="sadu-art-caption">MANY THREADS. ONE SHARED PICTURE.</span><span className="sadu-coordinate">CULTURE / PEOPLE / PLACE<br/>INSPIRED BY SHARJAH</span></div><div className="sadu-hero-bottom"><span>FICTIONAL SADU REHEARSAL</span><a href="#approach">SCROLL TO EXPLORE ↓</a><span>DESIGNED AROUND CULTURAL WORK</span></div></section>
      <section id="approach" className="sadu-section sadu-metaphor sadu-reveal"><div className="sadu-pattern-panel"><Weave compact/><span>01 / THE CONNECTING THREAD</span></div><div><p className="sadu-eyebrow">A FAMILIAR IDEA. A NEW APPLICATION.</p><h2>Individual threads.<br/><em>A stronger whole.</em></h2><p>Inspired by the geometry of Sadu weaving, SADU brings exhibition information into a connected working record.</p><p>Artist submissions, specialist evidence and recorded decisions stay linked. Each team sees its next action, while every approval retains its own responsibility.</p><div className="sadu-thread-legend"><span>People</span><span>Evidence</span><span>Decisions</span></div></div></section>
      <section id="capabilities" className="sadu-section sadu-reveal"><div className="sadu-section-heading"><div><p className="sadu-eyebrow">02 / THE CORE PILLARS</p><h2>More space for<br/><em>the work that matters.</em></h2></div><p>Practical tools for a clearer path from the artist’s first submission to the gallery wall.</p></div><div className="sadu-pillars">
        <article><span className="sadu-card-number">01 / CURATION</span><div className="sadu-pillar-icon" aria-hidden="true">⌘</div><h3>Less administration.<br/>More artistic focus.</h3><p>Connected submissions, revision notes and thematic filters help the Coordinator keep the work in view.</p><a href="/review">Explore the local workflow ↗</a><span className="sadu-state">{local ? 'AVAILABLE IN THE LOCAL REHEARSAL' : 'LOCAL SERVICE ONLY'}</span></article>
        <article><span className="sadu-card-number">02 / GOVERNANCE</span><div className="sadu-pillar-icon" aria-hidden="true">◇</div><h3>Clear boundaries.<br/>Accountable decisions.</h3><p>Separate review roles and attributed decisions demonstrate the approach. Encrypted vaults and UAE PASS remain planned integrations.</p><span className="sadu-state sadu-state-planned">LIVE SECURITY INTEGRATIONS PAUSED</span></article>
        <article><span className="sadu-card-number">03 / SPATIAL PLANNING</span><div className="sadu-pillar-icon" aria-hidden="true">▦</div><h3>From digital canvas<br/>to physical gallery.</h3><p>Scaled artwork blocks, boundary checks and overlap warnings support an informed conversation about fit.</p><a href="/review">Open the wall planner ↗</a><span className="sadu-state">{local ? 'AVAILABLE IN THE LOCAL REHEARSAL' : 'LOCAL SERVICE ONLY'}</span></article>
      </div></section>
      <section className="sadu-metrics-section sadu-reveal"><div className="sadu-section-heading"><div><p className="sadu-eyebrow">03 / THE REHEARSAL, IN NUMBERS</p><h2>A connected process.<br/><em>Visible at every step.</em></h2></div><p>These describe the fictional build. Operational savings have not yet been measured.</p></div><div className="sadu-metrics"><Counter value={14} label="Journey tasks" detail="Outstanding work in one linked artist journey."/><Counter value={3} label="Review roles" detail="Artist, Coordinator and Director, with distinct actions."/><Counter value={1} label="Fictional commission" detail="Kufic Horizon, followed from submission to arrival."/></div></section>
      <section className="sadu-section sadu-dashboard-section sadu-reveal"><p className="sadu-eyebrow">04 / A SHARED OPERATIONAL VIEW</p><h2>The whole journey.<br/><em>Without losing the detail.</em></h2><p>See the next action. Read the decision behind it. Follow the artwork into the gallery.</p><div className="sadu-laptop" aria-label="Illustrative Coordinator dashboard preview"><div className="sadu-laptop-screen"><aside><strong>◈ SADU</strong><span className="sadu-sidebar-active">Overview</span><span>Artist submissions</span><span>Spatial planning</span><span>Physical logistics</span><small>FICTIONAL PREVIEW</small></aside><div className="sadu-preview-content"><div className="sadu-preview-header"><span>GENERAL EXHIBITION COORDINATOR</span><span>KH</span></div><h3>A clearer view of what’s next.</h3><p>Kufic Horizon / Noura Al Mazrouei</p><div className="sadu-preview-stats"><div><b>01</b><span>Artist journey</span></div><div><b>03</b><span>Review roles</span></div><div><b>14</b><span>Linked tasks</span></div></div><div className="sadu-preview-row"><span>Concept review</span><small>Revision history</small><i>Linked</i></div><div className="sadu-preview-row"><span>Wall planning</span><small>Dimensions & placement</small><i>Available</i></div><div className="sadu-preview-row"><span>Crate tracking</span><small>Manifest & receipt</small><i>Available</i></div></div></div><div className="sadu-laptop-base"/></div><p className="sadu-preview-caption">Illustrative overview · Open the rehearsal to interact with saved records.</p></section>
      <section id="gateway" className="sadu-gateway sadu-reveal"><p className="sadu-eyebrow">05 / ENTER THE REHEARSAL</p><h2>From the idea<br/><em>to the experience.</em></h2><p>Explore the fictional artist journey. Advanced Coordinator tools run in the separate local rehearsal service.</p><div className="sadu-gateway-actions"><a className="sadu-cta" href="/review">{local ? 'Open the Coordinator workflow' : 'View advanced-tool availability'} <span aria-hidden="true">↗</span></a><a className="sadu-secondary" href="/journey">Explore the 14-task journey →</a></div><div className="sadu-pass"><button disabled aria-describedby="uae-pass-note"><span aria-hidden="true">◈</span> Sign in with UAE PASS</button><p id="uae-pass-note">Integration placeholder · Not connected. The rehearsal uses fictional account selection.</p></div></section>
    </main><footer className="sadu-footer"><div className="sadu-logo-slot">SDC LOGO<span>Official asset placeholder</span></div><p>SADU / Executive presentation<br/><span>Fictional demonstration. No government endorsement or live integration is represented.</span></p><div className="sadu-logo-slot">GOVERNMENT BADGE<span>Official asset placeholder</span></div></footer>
  </div>;
}
