import {useEffect,useRef,useState} from 'react';
import {Lock,BookOpen} from 'lucide-react';
import {pilotSupabase as client} from '../lib/pilotSupabase';
import {useOperationalRows} from '../lib/useOperationalRows';
export type ExhibitionTitle={scenario_id:string;title_ar:string;title_en:string;status:'PENDING_CURATOR_REVIEW'|'LOCKED';locked_at:string|null};
export function ExhibitionTitleGate({scenarioId,curator=false}:{scenarioId?:string;curator?:boolean}){
 const queue=useOperationalRows<ExhibitionTitle>('sadu_exhibition_titles',scenarioId?{column:'scenario_id',value:scenarioId}:undefined);
 const [ar,setAr]=useState(''),[en,setEn]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const running=useRef(false);const epoch=useRef(0);useEffect(()=>{const auth=client?.auth.onAuthStateChange(()=>{epoch.current++;setMessage('');setBusy(false);setAr('');setEn('');});return()=>{epoch.current++;auth?.data.subscription.unsubscribe();};},[]);
 async function save(row?:ExhibitionTitle){if(!client||running.current)return;if(!row&&(!scenarioId||!ar.trim()||!en.trim()))return;running.current=true;setBusy(true);const version=epoch.current;
 try{const result=row?await client.from('sadu_exhibition_titles').update({status:'LOCKED'}).eq('scenario_id',row.scenario_id).eq('status','PENDING_CURATOR_REVIEW').select('scenario_id').single():await client.from('sadu_exhibition_titles').insert({scenario_id:scenarioId,title_ar:ar.trim(),title_en:en.trim()});if(result.error)throw new Error();if(version!==epoch.current)return;await queue.refresh();if(version!==epoch.current)return;setMessage(row?'Curator title lock recorded.':'Title submitted for curatorial review.');}catch{if(version===epoch.current)setMessage('Not saved. Refresh and check ownership, curator role or an existing title receipt.');}finally{running.current=false;if(version===epoch.current)setBusy(false);}}
 return <section className="space-y-3 rounded border bg-[#F7F1E6] ps-4 pe-4 py-4 text-start"><h3 className="flex gap-2 text-xl"><BookOpen aria-hidden="true"/>Exhibition Title & Materials Gate / عنوان المعرض واعتماد المواد</h3><p>Materials export requires the artist’s bilingual exhibition title locked by HIP/curatorial review. Physical receiving does not wait for publication.</p>
 {scenarioId&&!queue.rows.length&&<fieldset disabled={busy} className="space-y-3"><label className="block">Exhibition title Arabic / عنوان المعرض<input dir="rtl" maxLength={250} value={ar} onChange={e=>setAr(e.target.value)} className="block w-full border ps-3 pe-3 py-2"/></label><label className="block">Exhibition title English<input maxLength={250} value={en} onChange={e=>setEn(e.target.value)} className="block w-full border ps-3 pe-3 py-2"/></label><button type="button" disabled={!ar.trim()||!en.trim()} onClick={()=>void save()} className="rounded border ps-3 pe-3 py-2 disabled:opacity-50">Submit title for review</button></fieldset>}
 {queue.rows.map(r=><article key={r.scenario_id} className="rounded border bg-[#FFFDF7] ps-3 pe-3 py-3"><p>{r.scenario_id}</p><p dir="rtl">{r.title_ar}</p><p>{r.title_en}</p><p>{r.status} · {r.locked_at??'Awaiting curator'}</p>{curator&&r.status==='PENDING_CURATOR_REVIEW'&&<button disabled={busy} onClick={()=>void save(r)} className="rounded bg-green-800 text-white ps-3 pe-3 py-2 disabled:opacity-50"><Lock className="inline size-4" aria-hidden="true"/>Approve & lock title / اعتماد العنوان</button>}</article>)}<p aria-live="polite">{message||queue.notice}</p></section>;
}
