import {useState} from 'react';
import {CalendarDays,MapPin,Truck,PackageCheck} from 'lucide-react';
import {pilotSupabase as client} from '../lib/pilotSupabase';
import {useOperationalRows} from '../lib/useOperationalRows';
import {safeMapUrl,shipmentStatuses,type FreightBooking,type CatalogArtwork} from '../data/catalogFreight';
import {operationalPanel as panel,operationalInput as field,operationalButton as button} from './ArtworkMetadataLedger';
const statusLabels=['Pending Origin Dispatch / قيد التجهيز','In Transit / قيد الشحن','Customs Clearance / التخليص الجمركي','Received & Condition Checked / تم الاستلام والفحص'];
function BookingCard({row,artwork,logistics,refresh}:{row:FreightBooking;artwork?:CatalogArtwork;logistics:boolean;refresh:()=>void}){
 const [date,setDate]=useState(''),[reason,setReason]=useState(''),[next,setNext]=useState(''),[reference,setReference]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function update(patch:Partial<FreightBooking>){if(!client||busy)return;setBusy(true);let query=client.from('sadu_freight_bookings').update(patch).eq('id',row.id).eq('status',row.status).eq('ready_date',row.ready_date);query=row.requested_date?query.eq('requested_date',row.requested_date):query.is('requested_date',null);query=row.change_status?query.eq('change_status',row.change_status):query.is('change_status',null);const result=await query.select('id').single();setBusy(false);if(result.error)setMessage('Update rejected. Refresh and check permissions, dates and inspection evidence.');else{setMessage('Saved to database.');refresh();}}
 const index=shipmentStatuses.indexOf(row.status);
 return <article className="space-y-3 rounded border bg-[#FFFDF7] ps-4 pe-4 py-4"><h3>{artwork?.translation_ar?.title??artwork?.source.title??row.artwork_id}</h3><p>{artwork?.width_cm} × {artwork?.height_cm} cm · {artwork?.weight_kg} kg · {artwork?.crate_count} crates</p><p className="flex gap-2"><MapPin aria-hidden="true"/>{Object.values(row.address).join(' · ')}</p><a className="underline" href={safeMapUrl(row.map_url)?row.map_url:undefined} target="_blank" rel="noopener noreferrer">Artist-supplied map link — location requires Logistics verification</a><p>Pickup: <time>{row.ready_date}</time> · Travel/unavailable: {row.unavailable_start??'Not declared'} — {row.unavailable_end??'Not declared'}</p><ol className="grid gap-2 sm:grid-cols-2">{statusLabels.map((label,i)=><li key={label} aria-current={i===index?'step':undefined} className={`rounded border ps-3 pe-3 py-2 ${i===index?'border-[#8B261E] font-semibold':''}`}>{i<index&&<PackageCheck aria-hidden="true" size={16}/>} {i+1}. {label}</li>)}</ol>{row.change_status&&<p role="status">Date change: {row.change_status} · {row.requested_date} · {row.change_reason}</p>}
 {!logistics&&row.status==='PENDING_ORIGIN_DISPATCH'&&row.change_status!=='PENDING'&&<fieldset disabled={busy} className="space-y-2"><legend>Request Date Change / طلب تغيير الموعد</legend><label>Proposed pickup date<input type="date" className={field} min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Reason<textarea className={field} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className={button} disabled={!date||date===row.ready_date||reason.trim().length<3} onClick={()=>void update({requested_date:date,change_reason:reason,change_status:'PENDING'})}>Request Date Change</button></fieldset>}
 {logistics&&row.change_status==='PENDING'&&<div className="flex gap-2"><button className={button} disabled={busy} onClick={()=>void update({change_status:'APPROVED'})}>Approve requested date</button><button className={button} disabled={busy} onClick={()=>void update({change_status:'REJECTED'})}>Reject date change</button></div>}
 {logistics&&row.status!=='RECEIVED_CONDITION_CHECKED'&&<fieldset disabled={busy||row.change_status==='PENDING'} className="space-y-2"><label>Shipment status<select className={field} value={next} onChange={e=>setNext(e.target.value)}><option value="">Choose next milestone</option>{shipmentStatuses.filter((s,i)=>i===index+1||(row.status==='IN_TRANSIT'&&s==='RECEIVED_CONDITION_CHECKED')).map(s=><option key={s} value={s}>{statusLabels[shipmentStatuses.indexOf(s)]}</option>)}</select></label>{next==='RECEIVED_CONDITION_CHECKED'&&<label>Completed condition-report reference<input className={field} value={reference} onChange={e=>setReference(e.target.value)} maxLength={200}/></label>}<button className={button} disabled={!next||next==='RECEIVED_CONDITION_CHECKED'&&reference.trim().length<3} onClick={()=>void update({status:next as FreightBooking['status'],...(next==='RECEIVED_CONDITION_CHECKED'?{condition_reference:reference}:{})})}>Record shipment milestone</button></fieldset>}
 <details><summary>Booking audit history</summary><ul>{row.history.map((e,i)=><li key={i}>{e.event} · {new Date(e.at).toLocaleString()} · {e.date}{e.requested_date?` → ${e.requested_date}`:''}</li>)}</ul></details><p role="status">{message}</p></article>;
}
export function FreightPickupScheduler({logistics=false}:{logistics?:boolean}){
 const bookings=useOperationalRows<FreightBooking>('sadu_freight_bookings'),artworks=useOperationalRows<CatalogArtwork>('sadu_artwork_checklist');
 const [selected,setSelected]=useState(''),[ready,setReady]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[pin,setPin]=useState('');
 const [address,setAddress]=useState({country:'',city:'',district:'',street:'',building:''}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const available=artworks.rows.filter(a=>!bookings.rows.some(b=>b.artwork_id===a.id));
 const valid=selected&&available.some(a=>a.id===selected)&&ready>=new Date().toISOString().slice(0,10)&&Object.values(address).every(v=>v.trim())&&safeMapUrl(pin)&&((!start&&!end)||(start&&end&&end>=start&&(ready<start||ready>end)));
 async function submit(){if(!client||busy||!valid)return;setBusy(true);const user=await client.auth.getUser();if(!user.data.user){setBusy(false);setMessage('Sign in with the owning Artist account.');return;}const result=await client.from('sadu_freight_bookings').insert({artwork_id:selected,artist_id:user.data.user.id,ready_date:ready,unavailable_start:start||null,unavailable_end:end||null,address,map_url:pin});setBusy(false);if(result.error)setMessage('Booking not saved. Check ownership, structured address and non-overlapping travel dates.');else{setSelected('');setMessage('Pickup request locked and routed to Logistics.');await bookings.refresh();}}
 return <section className={panel}><h2 className="flex gap-2 text-xl"><Truck aria-hidden="true"/>Freight Pickup Scheduler & Live Tracking / جدولة وتتبع الشحن</h2><p>{bookings.live?'Live database updates connected.':'Connection pending — refreshing every 15 seconds.'} Shipment tracking does not release funds automatically.</p>{!logistics&&<fieldset disabled={busy} className="grid gap-3 md:grid-cols-2"><legend className="flex gap-2"><CalendarDays aria-hidden="true"/>Structured artwork collection request</legend><label>Approved artwork metadata<select className={field} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select artwork</option>{available.map(a=><option key={a.id} value={a.id}>{a.source.title}</option>)}</select></label><label>Ready for Pickup Date / تاريخ الاستلام<input type="date" className={field} min={new Date().toISOString().slice(0,10)} value={ready} onChange={e=>setReady(e.target.value)}/></label><label>Unavailable from / بداية السفر<input type="date" className={field} value={start} onChange={e=>setStart(e.target.value)}/></label><label>Unavailable until / نهاية السفر<input type="date" className={field} min={start} value={end} onChange={e=>setEnd(e.target.value)}/></label>{(['country','city','district','street','building'] as const).map(key=><label key={key}>{{country:"Country / البلد",city:"City / المدينة",district:"District / المنطقة",street:"Street / الشارع",building:"Villa / Building / المبنى"}[key]}<input className={field} maxLength={250} value={address[key]} onChange={e=>setAddress({...address,[key]:e.target.value})}/></label>)}<label>Google Maps / Makani Pin URL<input type="url" className={field} value={pin} onChange={e=>setPin(e.target.value)}/></label><button className={button} disabled={!valid||busy} onClick={()=>void submit()}>Submit & lock pickup request</button></fieldset>}<p role="status">{message||bookings.notice||artworks.notice}</p><button className="underline" onClick={()=>{void bookings.refresh();void artworks.refresh();}}>Refresh database records</button>{bookings.rows.map(row=><BookingCard key={`${row.id}:${row.status}:${row.change_status}`} row={row} artwork={artworks.rows.find(a=>a.id===row.artwork_id)} logistics={logistics} refresh={()=>void bookings.refresh()}/>)}{!bookings.rows.length&&<p><PackageCheck aria-hidden="true"/>No shipment records visible.</p>}</section>;
}
