import {useEffect,useRef,useState} from 'react';
import {Clock,ClipboardCheck} from 'lucide-react';
import {pilotSupabase as client} from '../lib/pilotSupabase';
import {useOperationalRows} from '../lib/useOperationalRows';
import {type Consignment,validConsignment} from '../data/consignment';
type Ticket={consignment_id:string;officer_id:string;ready_at:string;opened_at:string|null;actioned_at:string|null;action_note:string|null;escalated_at:string|null};
export function LogisticsActionQueue({artist=false,officer=false}:{artist?:boolean;officer?:boolean}){
 const tickets=useOperationalRows<Ticket>('sadu_logistics_tickets'),records=useOperationalRows<Consignment>('sadu_consignments');
 const [notes,setNotes]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const epoch=useRef(0),running=useRef(false);
 useEffect(()=>{const auth=client?.auth.onAuthStateChange(()=>{epoch.current++;setNotes({});setMessage('');setBusy(false)});return()=>{epoch.current++;auth?.data.subscription.unsubscribe()};},[]);
 async function record(id:string,action:'ready'|'open'|'action'){
 if(!client||running.current)return;running.current=true;setBusy(true);const version=epoch.current;
 try{const r=action==='ready'?await client.from('sadu_logistics_tickets').insert({consignment_id:id}):await client.from('sadu_logistics_tickets').update(action==='open'?{opened_at:new Date().toISOString()}:{action_note:notes[id]?.trim()}).eq('consignment_id',id).select('consignment_id').single();if(r.error)throw r.error;if(version!==epoch.current)return;await tickets.refresh();if(version===epoch.current)setMessage('Receipt recorded. Opening alone does not satisfy the 48-hour action deadline.');}catch{if(version===epoch.current)setMessage('Not recorded. Check assigned-account authority, complete packing data and configured Logistics routing.');}finally{running.current=false;if(version===epoch.current)setBusy(false);}
 }
 return <section className="space-y-3 rounded border bg-[#F7F1E6] ps-4 pe-4 py-4 text-start"><h2 className="flex gap-2 text-xl"><ClipboardCheck aria-hidden="true"/>Logistics action tickets / تذاكر إجراءات الشحن</h2><p>48 elapsed hours from Ready for Shipping. A server-recorded action reference is required; viewing the ticket is insufficient. Escalation appears to the configured department head, without sending an email.</p>{artist&&records.rows.filter(c=>c.status==='CONSIGNMENT_DATA_RECEIVED'&&!tickets.rows.some(t=>t.consignment_id===c.id)).map(c=><button key={c.id} disabled={busy||!c.details||!validConsignment(c.details)} className="rounded border ps-3 pe-3 py-2 disabled:opacity-50" onClick={()=>void record(c.id,'ready')}>Ready for Shipping / جاهز للشحن · {c.artwork_id}</button>)}{tickets.rows.map(t=><article key={t.consignment_id} className="space-y-2 rounded border bg-[#FFFDF7] ps-3 pe-3 py-3"><h3 className="break-all">{t.consignment_id}</h3><p><Clock className="inline size-4" aria-hidden="true"/>Action due: <bdi>{new Date(Date.parse(t.ready_at)+48*3600000).toLocaleString()}</bdi></p><p>Assigned officer: <bdi>{t.officer_id}</bdi></p><p>Opened: <bdi>{t.opened_at??'Not opened'}</bdi> · Action recorded: <bdi>{t.actioned_at??'Pending'}</bdi></p>{t.escalated_at&&<p className="text-red-800">48-hour SLA breached — department head escalation recorded{t.actioned_at?' (subsequently actioned)':''}</p>}{t.action_note&&<p>{t.action_note}</p>}{officer&&!t.actioned_at&&<><button disabled={busy||Boolean(t.opened_at)} onClick={()=>void record(t.consignment_id,'open')} className="rounded border ps-3 pe-3 py-2 disabled:opacity-50">Acknowledge opening / تأكيد الاطلاع</button><label className="block">Action taken / الإجراء المتخذ<textarea maxLength={1000} disabled={busy} className="block w-full rounded border ps-3 pe-3 py-2" value={notes[t.consignment_id]??''} onChange={e=>setNotes({...notes,[t.consignment_id]:e.target.value})}/></label><button disabled={busy||(notes[t.consignment_id]?.trim().length??0)<10} onClick={()=>void record(t.consignment_id,'action')} className="rounded border ps-3 pe-3 py-2 disabled:opacity-50">Record logistics action / توثيق الإجراء</button></>}</article>)}<p role="status">{message||tickets.notice}</p></section>;
}
