import { useEffect, useState } from 'react';
import { BookOpen, Globe, UploadCloud, Search } from 'lucide-react';
import { useMasterDirectory } from '../context/MasterDirectory';
import { filterProfiles, validPressFile, type MasterProfile } from '../data/masterDirectory';
const panel='space-y-4 rounded-xl border border-[#D9CEBA] bg-[#F7F1E6] ps-5 pe-5 py-5 text-start';
const input='mt-1 block w-full rounded border border-[#D9CEBA] bg-white ps-3 pe-3 py-2';
function PressDownload({file}:{file:File}) {const [url,setUrl]=useState('');useEffect(()=>{const next=URL.createObjectURL(file);setUrl(next);return()=>URL.revokeObjectURL(next);},[file]);return <a href={url||undefined} download={file.name} className="break-all underline">{file.name}</a>;}
function StorageNotice({isAr}:{isAr:boolean}){return <p className="text-sm text-[#736357]">{isAr?'سجل تجريبي دائم في هذا المتصفح؛ ليس قاعدة بيانات الدائرة. استخدم ملفات تجريبية فقط.':'Persistent prototype records in this browser; not the Department’s server directory. Use sample files only.'}</p>;}
export function LivingProfileEditor({artistId,isAr}:{artistId:string;isAr:boolean}) {
 const {profiles,ready,error,save}=useMasterDirectory();const profile=profiles.find(p=>p.id===artistId);
 if(!ready||!profile)return <section className={panel}><p role="status">{error||'Loading master profile…'}</p></section>;
 return <ProfileForm key={artistId} profile={profile} isAr={isAr} save={save}/>;
}
function ProfileForm({profile,isAr,save}:{profile:MasterProfile;isAr:boolean;save:(p:MasterProfile)=>Promise<void>}) {
 const [draft,setDraft]=useState(profile),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const t=(ar:string,en:string)=>isAr?ar:en;
 async function add(files:FileList|null){if(!files)return;const list=Array.from(files);if(draft.press.length+list.length>10||list.some(f=>!validPressFile(f))){setNotice(t('ملفات PDF فقط، حتى 20 ميغابايت للملف و10 ملفات.','PDFs only, up to 20 MB each and 10 files.'));return;}const fresh=list.filter((f,i)=>!draft.press.some(p=>p.file.name===f.name&&p.file.size===f.size)&&list.findIndex(other=>other.name===f.name&&other.size===f.size)===i);setDraft(p=>({...p,press:[...p.press,...fresh.map(file=>({id:crypto.randomUUID(),file,uploadedAt:new Date().toISOString()}))]}));setNotice(t('مرفقات مسودة — احفظ لإتاحتها للسجل.','Draft attachments — save to publish them to the directory.'));}
 return <form className={panel} onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);try{await save({...draft,updatedAt:new Date().toISOString()});setNotice(t('تم الحفظ في السجل الموحد على هذا الجهاز.','Saved to the master directory on this device.'));}catch{setNotice(t('تعذر الحفظ؛ قد تكون مساحة التخزين ممتلئة.','Save failed; browser storage may be full.'));}finally{setBusy(false);}}}>
 <h2 className="flex items-center gap-2 text-2xl font-semibold"><BookOpen aria-hidden="true"/>الملف التعريفي والسجل الإعلامي / Living Profile & Press Vault</h2><p>{profile.name}</p><StorageNotice isAr={isAr}/>
 <fieldset disabled={busy} className="space-y-4"><label className="block">السيرة الذاتية بالعربية<textarea dir="rtl" className={input} rows={5} maxLength={12000} value={draft.bioAr} onChange={e=>setDraft(p=>({...p,bioAr:e.target.value}))}/></label><label className="block">Biography in English<textarea dir="ltr" className={input} rows={5} maxLength={12000} value={draft.bioEn} onChange={e=>setDraft(p=>({...p,bioEn:e.target.value}))}/></label><label className="block"><Globe className="inline size-4" aria-hidden="true"/> {t('الانتماءات المؤسسية / تمثيل المعارض','Current Institutional Affiliations / Gallery Representation')}<input className={input} maxLength={1000} value={draft.affiliations} onChange={e=>setDraft(p=>({...p,affiliations:e.target.value}))}/></label>
 <label className="block rounded border-2 border-dashed border-[#D9CEBA] bg-white ps-4 pe-4 py-6"><span className="flex items-center gap-2"><UploadCloud aria-hidden="true"/>Press, Publications & Monographs</span><span className="block text-sm">PDF · 20 MB maximum per file · 10 files</span><input type="file" accept=".pdf,application/pdf" multiple className="mt-3 block w-full" onChange={e=>{void add(e.target.files);e.target.value='';}}/></label><ul>{draft.press.map(p=><li key={p.id} className="py-2"><PressDownload file={p.file}/></li>)}</ul>
 <button disabled={busy} className="rounded bg-[#8B261E] ps-5 pe-5 py-3 text-white disabled:opacity-50">{t('حفظ في السجل الموحد','Save to Master Directory')}</button></fieldset><p role="status">{notice}</p></form>;
}
export function MasterDirectory({isAr}:{isAr:boolean}) {
 const {profiles,ready,error}=useMasterDirectory();const [query,setQuery]=useState(''),[medium,setMedium]=useState(''),[nationality,setNationality]=useState(''),[edition,setEdition]=useState(''),[selected,setSelected]=useState<string|null>(null);const t=(ar:string,en:string)=>isAr?ar:en;
 const matches=filterProfiles(profiles,query,medium,nationality,edition),profile=profiles.find(p=>p.id===selected);
 return <details className={panel}><summary className="cursor-pointer text-xl font-semibold">السجل الموحد لفناني الخط / Master Calligraphy & Islamic Arts Directory</summary><StorageNotice isAr={isAr}/><p>{t('ملفات مسجلة في هذا المتصفح؛ بيانات العروض التجريبية ليست سجلاً تاريخياً موثقاً.','Profiles registered in this browser; rehearsal participation is not verified institutional history.')}</p>
 <label className="block"><Search className="inline size-4" aria-hidden="true"/> {t('البحث بالاسم والسيرة والانتماءات','Search name, biography or affiliations')}<input className={input} value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="grid gap-3 sm:grid-cols-3">{[{label:t('الوسيط','Medium'),value:medium,set:setMedium,options:profiles.map(p=>p.medium)},{label:t('الجنسية / المنطقة','Nationality / Region'),value:nationality,set:setNationality,options:profiles.map(p=>p.nationality)},{label:t('دورات المشاركة','Participation history'),value:edition,set:setEdition,options:profiles.flatMap(p=>p.editions)}].map(f=><label key={f.label}>{f.label}<select className={input} value={f.value} onChange={e=>f.set(e.target.value)}><option value="">{t('الكل','All')}</option>{[...new Set(f.options)].sort().map(o=><option key={o}>{o}</option>)}</select></label>)}</div>
 <p role="status">{error||(!ready?'Loading directory…':`${matches.length} ${t('ملف','profiles')}`)}</p><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{matches.map(p=><button type="button" aria-pressed={selected===p.id} key={p.id} onClick={()=>setSelected(p.id)} className="space-y-2 rounded-lg border border-[#D9CEBA] bg-white ps-4 pe-4 py-5 text-start hover:border-[#8B261E]"><span className="block text-lg font-semibold">{p.name}</span><span className="block text-sm text-[#736357]">{p.nationality} · {p.medium}</span><span className="block text-xs">{p.editions.join(' · ')}</span></button>)}</div>
 {profile&&<section aria-label={profile.name} className="space-y-4 border-t border-[#D9CEBA] pt-5"><div className="flex items-center justify-between gap-3"><h3 className="text-2xl font-semibold">{profile.name}</h3><button type="button" onClick={()=>setSelected(null)} className="rounded border ps-3 pe-3 py-2">{t('إغلاق','Close')}</button></div><p dir="rtl" className="whitespace-pre-wrap">{profile.bioAr||'لم تضف سيرة عربية بعد.'}</p><p dir="ltr" className="whitespace-pre-wrap">{profile.bioEn||'No English biography yet.'}</p><p>{profile.affiliations||t('لا توجد انتماءات مسجلة.','No affiliations recorded.')}</p><h4 className="font-semibold">Press, Publications & Monographs</h4>{!profile.press.length&&<p>{t('لا توجد مرفقات.','No publications uploaded.')}</p>}<ul className="space-y-2">{profile.press.map(p=><li key={p.id}><PressDownload file={p.file}/></li>)}</ul>{profile.updatedAt&&<p className="text-sm">{new Date(profile.updatedAt).toLocaleString(isAr?'ar-AE':'en-AE')}</p>}</section>}
 </details>;
}
