import { useEffect, useState } from 'react';
import { conservationWarnings, normalizedPin } from '../logistics/museumCare.mjs';
export type Conservation = { max_lux: number; target_temp_c: number; target_humidity_pct: number };
export function ConservationRider({ value, onChange }: { value: Conservation; onChange: (value: Conservation) => void }) {
  return <fieldset className="space-y-3"><legend className="font-semibold">Conservation requirements</legend>{(['max_lux','target_temp_c','target_humidity_pct'] as const).map(key => <label className="block" key={key}>{({ max_lux: 'Maximum light (lux)', target_temp_c: 'Target temperature (°C)', target_humidity_pct: 'Target relative humidity (%)' })[key]}<input type="number" required step="any" value={Number.isFinite(value[key]) ? value[key] : ''} onChange={e => onChange({ ...value, [key]: e.target.value === '' ? NaN : Number(e.target.value) })} className="block border rounded p-2"/></label>)}<p className="text-sm">Artist-provided requirements need specialist review; these fields do not certify safe display.</p></fieldset>;
}
export function VenueClearance({ requirements, capability }: { requirements: Conservation; capability: { lux: number; min_temp_c: number; max_temp_c: number; min_humidity_pct: number; max_humidity_pct: number } }) {
  let warnings: string[]; try { warnings = conservationWarnings(requirements, capability) as string[]; } catch { warnings = ['Conservation requirements are incomplete.']; }
  return <section><h3>Conservation rider</h3><p>Maximum {requirements.max_lux} lux · Target {requirements.target_temp_c} °C · {requirements.target_humidity_pct}% RH</p><ul>{warnings.map(w => <li key={w}>{w}</li>)}</ul>{!warnings.length && <p>Declared venue capability meets these targets. Specialist sign-off remains required.</p>}</section>;
}
type Pin = { id: string; x_pct: number; y_pct: number; description: string };
export function ConditionPins({ imageUrl, pins, onSave }: { imageUrl: string; pins: Pin[]; onSave: (pin: { x_pct: number; y_pct: number; description: string; photo: File }) => Promise<void> }) {
  const [point, setPoint] = useState<{ x_pct: number; y_pct: number }>(); const [description, setDescription] = useState(''); const [photo, setPhoto] = useState<File>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [loaded, setLoaded] = useState(false);
  return <section className="space-y-3"><h3 className="font-semibold">Condition map</h3><p>Tap the reference image, or enter percentage coordinates below. Each observation stays linked to this image revision.</p>
    <div className="relative block w-full max-w-xl"><img src={imageUrl} alt="Artwork reference for condition observations" className="block w-full h-auto" onLoad={() => setLoaded(true)} onError={() => { setLoaded(false); setError('Reference image could not be loaded.'); }} onClick={e => { if (!loaded) return; const r = e.currentTarget.getBoundingClientRect(); setPoint(normalizedPin((e.clientX-r.left)/r.width*100, (e.clientY-r.top)/r.height*100)); }}/>{[...pins, ...(point ? [{ ...point, id: 'new', description: 'New observation' }] : [])].map((p,i) => <span key={p.id} title={p.description} style={{ position:'absolute', left:`${p.x_pct}%`, top:`${p.y_pct}%`, transform:'translate(-50%,-50%)', pointerEvents:'none' }} className="rounded-full bg-red-800 text-white px-2 border-2 border-white">{i+1}</span>)}</div>
    <form className="space-y-3" onSubmit={async e => { e.preventDefault(); const form = e.currentTarget; if (!point || !photo || !description.trim() || busy) return; setBusy(true); setError(''); try { normalizedPin(point.x_pct,point.y_pct); await onSave({ ...point,description:description.trim(),photo }); setDescription(''); setPoint(undefined); setPhoto(undefined); form.reset(); } catch { setError('Observation could not be saved. Your entries have been retained.'); } finally { setBusy(false); } }}>
    {(['x_pct','y_pct'] as const).map(k => <label key={k} className="block">{k === 'x_pct' ? 'Horizontal position (%)' : 'Vertical position (%)'}<input type="number" min="0" max="100" step="any" required value={point?.[k] ?? ''} onChange={e => setPoint({ ...(point ?? { x_pct:0,y_pct:0 }), [k]: Number(e.target.value) })} className="border rounded p-2"/></label>)}
    <label className="block">Damage description<textarea required maxLength={2000} value={description} onChange={e => setDescription(e.target.value)} className="block border rounded p-2"/></label><label className="block">Damage photograph<input type="file" accept="image/jpeg,image/png,image/webp" required onChange={e => setPhoto(e.target.files?.[0])}/></label><button disabled={busy || !loaded || !point || !photo || !description.trim()} className="rounded bg-[#8B261E] text-white p-3 disabled:opacity-40">{busy ? 'Saving…' : 'Save pinned observation'}</button></form>
    <p role="alert">{error}</p><ol>{pins.map((p,i) => <li key={p.id}>{i+1}. {p.description} ({p.x_pct.toFixed(1)}%, {p.y_pct.toFixed(1)}%)</li>)}</ol>
  </section>;
}
export function BudgetGauge({ value }: { value: { ceiling: number; allocated: number; reserved: number; spent: number; available: number } }) {
  const money = (n: number) => new Intl.NumberFormat('en-AE',{ style:'currency',currency:'AED' }).format(n/100);
  return <section><h3 className="font-semibold">Exhibition funds</h3><meter aria-label="Committed and spent budget" min={0} max={Math.max(1,value.ceiling)} value={Math.min(value.ceiling, value.allocated+value.reserved+value.spent)}/><dl>{(['allocated','reserved','spent','available'] as const).map(k => <div key={k}><dt>{k === 'reserved' ? 'Reserved pending reconciliation' : k}</dt><dd>{money(value[k])}</dd></div>)}</dl><p>Withdrawal does not automatically release unpaid commitments. Finance must record the reconciled release.</p>{value.available < 0 && <p role="alert">Budget exceeded.</p>}</section>;
}
export function ConnectedBudgetGauge() {
  const [value, setValue] = useState<{ ceiling: number; allocated: number; reserved: number; spent: number; available: number }>(); const [error, setError] = useState('');
  useEffect(() => { let active = true; let loading = false; const refresh = async () => { if (loading) return; loading = true; try { const r = await fetch('/api/review/ecosystem/budget', { cache:'no-store' }); if (!r.ok) throw new Error('Verified budget is not available from the unified service.'); const result = await r.json(); if (active) { setValue(result); setError(''); } } catch { if (active) { setValue(undefined); setError('Budget unavailable. No available-funds figure is assumed.'); } } finally { loading=false; } }; void refresh(); const interval=setInterval(refresh,5000); window.addEventListener('sadu:budget-changed',refresh); return () => { active=false; clearInterval(interval); window.removeEventListener('sadu:budget-changed',refresh); }; }, []);
  return <section>{value && <BudgetGauge value={value}/>}<p role="status">{error || 'Budget refreshes every five seconds while this view is open.'}</p></section>;
}
