import { useContext, useLayoutEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { DraftForm, DraftFieldsContext } from './DraftForm';
import type { OperationsView } from './ConnectedOperations';
import type { CollectionView } from '../lib/useCollectionWorkflow';
import { type Language, type WorkspaceTask, accountLabel } from '../lib/operationalWorkspace';
import { treatmentDomains } from '../lib/treatment';

const photoKinds = ['TREATMENT_SAMPLE', 'TREATMENT_COMPLETION'];
export type WorkspaceCommand =(channel: 'collection' | 'operations', action: string, data: Record<string, unknown>, file?: File) => Promise<boolean>;
type Props = { task: WorkspaceTask; ops: OperationsView; collection?: CollectionView; actor: { id: string; role: string }; language: Language;
  disabled: boolean; mark: () => void; run: WorkspaceCommand; evidenceId: string; evidenceReady?: boolean; onEvidence: (id: string) => void };
function Input({label,name,type='text',value,required=true,min}: {label:string;name:string;type?:string;value?:string|number;required?:boolean;min?:number}) {
  return <label className="work-field">{label}<input name={name} type={type} defaultValue={value} required={required} maxLength={1000} min={min} step={type==='number'?'any':undefined}/></label>;
}
function Check({name,children}: {name:string;children:ReactNode}) {return <label className="work-check"><input type="checkbox" name={name} required/>{children}</label>;}
function Form({label,disabled,submitDisabled=false,mark,submit,children}: {label:string;disabled:boolean;submitDisabled?:boolean;mark:()=>void;submit:(f:FormData)=>Promise<boolean>;children:ReactNode}) {
  const root=useRef<HTMLDivElement>(null),[valid,setValid]=useState(false);
  const validate=()=>setValid(!!root.current?.querySelector('form')?.checkValidity());
  useLayoutEffect(validate);
  return <div ref={root}><DraftForm onChange={()=>{validate();mark();}} onInput={()=>{validate();mark();}} onSubmit={async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;if(disabled||submitDisabled||!form.checkValidity())return;mark();if(await submit(new FormData(form))){form.reset();validate();}}}>
    <fieldset disabled={disabled} className="work-fields"><legend className="sr-only">{label}</legend>{children}<button className="work-primary" disabled={disabled||submitDisabled||!valid}>{label}</button></fieldset>
  </DraftForm></div>;
}
export function ResponsibilityForm({task,ops,language,disabled,mark,run}:Pick<Props,'task'|'ops'|'language'|'disabled'|'mark'|'run'>) {
  const t=(ar:string,en:string)=>language==='ar'?ar:en;
  const eligible=task.renewal?ops.accounts.filter(a=>task.renewal!.eligibleOwners.includes(a.id)):ops.accounts.filter(a=>a.role===task.ownerRole);
  return <Form label={t('حفظ المسؤول والموعد','Save owner and deadline')} disabled={disabled} mark={mark} submit={f=>run('operations',task.renewal?'ASSIGN_RENEWAL':'ASSIGN_TASK',{
    ...(task.renewal?{taskId:task.id}:{key:task.legacyKey}),ownerId:f.get('ownerId'),dueAt:new Date(String(f.get('dueAt'))).toISOString(),reason:f.get('reason')})}>
    <label className="work-field">{t('المسؤول المخوّل','Eligible owner')}<select required name="ownerId" defaultValue={task.ownerId??''}><option value="" disabled>{t('اختر المسؤول','Select owner')}</option>{eligible.map(a=><option key={a.id} value={a.id}>{accountLabel(a,language)}</option>)}</select></label>
    <Input name="dueAt" type="datetime-local" label={t('الموعد النهائي بتوقيت جهازك','Deadline in your device timezone')}/>
    <Input name="reason" label={t('سبب التعيين أو تغييره','Reason for assignment or change')}/>
    <details className="work-help"><summary>{t('مساعدة','Help')}</summary><p>{t('يجب أن يقبل المسؤول المهمة؛ التعيين وحده ليس اعتماداً.','The owner must accept this task. Assignment is not approval.')}</p></details>
  </Form>;
}

export function EvidenceUpload({kind,language,disabled,mark,run}: {kind:string;language:Language;disabled:boolean;mark:()=>void;run:WorkspaceCommand}) {
  const t=(ar:string,en:string)=>language==='ar'?ar:en;
  const [fileError,setFileError]=useState('');
  return <Form label={disabled?t('جارٍ الحفظ أو بانتظار الاتصال','Saving or awaiting connection'):t('رفع الملف ومراجعته','Upload and review')} disabled={disabled} mark={mark} submit={f=>{const file=f.get('file') as File;if(!file?.size||fileError)return Promise.resolve(false);return run('operations','UPLOAD',{kind,name:file.name,source:f.get('source'),sender:f.get('sender'),receivedAt:f.get('receivedAt')?new Date(String(f.get('receivedAt'))).toISOString():null},file);}}>
    <label className="work-file-drop"><strong>{({PACKING:t('صورة التغليف أو ملف PDF','Packing photo or PDF'),PREFLIGHT:t('تقرير الفحص بصيغة PDF','Preflight report PDF'),TREATMENT_SOURCE:t('مستند الإذن بصيغة PDF','Permission record PDF'),TREATMENT_SAMPLE:t('صورة فعلية لتجربة الحرف الواحد','Actual photograph of the one-letter trial'),TREATMENT_COMPLETION:t('صورة فعلية لاكتمال المعالجة','Actual photograph of the completed treatment')} as Record<string,string>)[kind]??t('بروفة الطباعة بصيغة PDF','Print proof PDF')}</strong><span>{t('مطلوب','Required')} · {kind==='PACKING'?'JPG, PNG, PDF':photoKinds.includes(kind)?'JPG, PNG':'PDF'} · {t('حتى 10 ميغابايت','Up to 10 MB')}</span><input name="file" required type="file" accept={kind==='PACKING'?'image/png,image/jpeg,application/pdf':photoKinds.includes(kind)?'image/png,image/jpeg':'application/pdf'} onChange={e=>{const file=e.currentTarget.files?.[0];const allowed=kind==='PACKING'?['image/png','image/jpeg','application/pdf']:photoKinds.includes(kind)?['image/png','image/jpeg']:['application/pdf'];const error=file&&(!file.size||file.size>10*1024*1024||!allowed.includes(file.type))?t('اختر ملفاً غير فارغ من النوع المحدد، لا يتجاوز 10 ميغابايت.','Choose a non-empty supported file, up to 10 MB.'):'';e.currentTarget.setCustomValidity(error);setFileError(error);}}/></label>
    {fileError&&<p role="alert" className="work-hold">{fileError}</p>}
    <div className="work-field-pair"><Input name="source" label={t('مرجع المصدر','Source reference')}/><Input name="sender" label={t('المرسل','Sender')}/></div>
    <details className="work-help"><summary>{t('تفاصيل اختيارية ومساعدة','Optional details and help')}</summary><p>{t('استخدم ملفات تجريبية فقط. الرفع لا يعتمد التغليف أو الطباعة.','Use synthetic files only. Uploading does not approve packing or printing.')}</p><Input name="receivedAt" type="datetime-local" required={false} label={t('وقت الاستلام، إن عُرف','Received time, if known')}/></details>
  </Form>;
}

function CollectionSource({collection,language,disabled,mark,run}:Pick<Props,'collection'|'language'|'disabled'|'mark'|'run'>) {
  const r=collection?.record,t=(ar:string,en:string)=>language==='ar'?ar:en;
  const recovered=useContext(DraftFieldsContext);
  const [closures,setClosures]=useState<Array<{start:string;end:string}>>(()=>{try{const v=JSON.parse(recovered.closures??'null');if(Array.isArray(v)&&v.length<=20&&v.every(c=>typeof c.start==='string'&&typeof c.end==='string'))return v;}catch{/* Retain current record when a draft is invalid. */}return r?.closures??[];});
  return <Form label={t('حفظ بيانات الاستلام','Save collection details')} disabled={disabled} mark={mark} submit={f=>run('collection','SAVE',{details:{
    ...Object.fromEntries(['address','city','country','contact','sourceRef','timezone'].map(k=>[k,String(f.get(k))])),availability:{start:f.get('start'),end:f.get('end')},closures,conflict:f.get('conflict')==='on'}})}>
    <input type="hidden" name="closures" value={JSON.stringify(closures)}/>
    <Input name="address" value={r?.address} label={t('عنوان الاستلام الفعلي','Physical collection address')}/>
    <div className="work-field-pair"><Input name="city" value={r?.city} label={t('المدينة','City')}/><Input name="country" value={r?.country} label={t('بلد الاستلام','Collection country')}/></div>
    <Input name="contact" value={r?.contact} label={t('جهة الاتصال للاستلام','Collection contact')}/><Input name="sourceRef" value={r?.sourceRef} label={t('مرجع تأكيد العنوان','Address source reference')}/>
    <Input name="timezone" value={r?.timezone} label={t('المنطقة الزمنية، مثل Europe/Paris','Timezone, e.g. Europe/Paris')}/>
    <div className="work-field-pair"><Input name="start" type="date" value={r?.availability.start} label={t('الإتاحة من','Available from')}/><Input name="end" type="date" value={r?.availability.end} label={t('إلى','Until')}/></div>
    <details><summary>{t('فترات إغلاق الموقع','Site closure periods')} ({closures.length})</summary>{closures.map((c,i)=><div className="work-field-pair" key={i}>{(['start','end'] as const).map(k=><label className="work-field" key={k}>{k==='start'?t('بداية الإغلاق','Closure starts'):t('نهاية الإغلاق','Closure ends')}<input required type="date" value={c[k]} onInput={e=>{const value=e.currentTarget.value;setClosures(v=>v.map((old,n)=>n===i?{...old,[k]:value}:old));mark();}} onChange={e=>{const value=e.target.value;setClosures(v=>v.map((old,n)=>n===i?{...old,[k]:value}:old));mark();}}/></label>)}<button type="button" className="work-secondary" onClick={()=>{setClosures(v=>v.filter((_,n)=>n!==i));mark();}}>{t('إزالة الفترة','Remove period')}</button></div>)}<button type="button" className="work-secondary" disabled={closures.length>=20} onClick={()=>{setClosures(v=>[...v,{start:'',end:''}]);mark();}}>{t('إضافة فترة إغلاق','Add closure')}</button></details>
    <label className="work-check"><input type="checkbox" name="conflict" defaultChecked={r?.conflict}/>{t('المعلومات متعارضة وتحتاج إلى توضيح','The source information conflicts and needs clarification')}</label>
  </Form>;
}

type Condition={domain:string;text:string};
function TreatmentRecord({ops,language,disabled,mark,run,task,actor}:Props) {
  const t=(ar:string,en:string)=>language==='ar'?ar:en;
  const cur=ops.treatment?.current??null,amend=task.key==='amendTreatment'&&!!cur;
  const recovered=useContext(DraftFieldsContext);
  const [conditions,setConditions]=useState<Condition[]>(()=>{try{const v=JSON.parse(recovered.conditions??'null');if(Array.isArray(v)&&v.length<=12&&v.every(c=>typeof c.domain==='string'&&typeof c.text==='string'))return v;}catch{/* Retain the current record when a draft is invalid. */}return amend?cur!.conditions.map(c=>({domain:c.domain,text:c.text})):[{domain:'VENUE',text:''}];});
  const edit=(i:number,patch:Partial<Condition>)=>{setConditions(v=>v.map((c,n)=>n===i?{...c,...patch}:c));mark();};
  const others=ops.accounts.filter(a=>a.id!==actor.id&&a.role!=='Logistics');
  return <Form disabled={disabled} mark={mark} submitDisabled={!conditions.length||conditions.some(c=>!c.text.trim())} label={amend?t('حفظ إصدار جديد من المعالجة','Save a new treatment revision'):t('حفظ المعالجة المشروطة','Save the conditional treatment')} submit={f=>run('operations','TREATMENT_RECORD',{baseRevision:cur?.revision??0,workTitle:f.get('workTitle'),method:f.get('method'),sourceRef:f.get('sourceRef'),
      decisionMaker:{name:f.get('decisionMakerName'),capacity:f.get('decisionMakerCapacity'),...(f.get('decisionMakerAccountId')?{accountId:f.get('decisionMakerAccountId')}:{})},conditions})}>
    <input type="hidden" name="conditions" value={JSON.stringify(conditions)}/>
    {amend&&<p className="work-hint" role="note">{t('الإصدار الجديد يُبطل التفويض وصورة العيّنة وموافقة الفنان فقط. تبقى المتطلبات المستقلة وتعيين الفني، وتُحفظ الإصدارات السابقة.','A new revision invalidates only the authorization, trial photograph and artist approval. Independent requirements and the technician assignment stay; earlier revisions are retained.')}</p>}
    <Input name="workTitle" value={cur?.workTitle} label={t('العمل الفني','Artwork')}/>
    <Input name="method" value={cur?.method} label={t('المعالجة المحددة (تجربة حرف واحد أولاً)','Exact treatment (one-letter trial first)')}/>
    <Input name="sourceRef" value={cur?.sourceRef} label={t('مرجع المصدر','Source reference')}/>
    <div className="work-field-pair"><Input name="decisionMakerName" value={cur?.decisionMaker.name} label={t('صاحب القرار المسمّى','Named decision-maker')}/><Input name="decisionMakerCapacity" value={cur?.decisionMaker.capacity} label={t('صفته','Capacity')}/></div>
    <details className="work-help"><summary>{t('حساب داخل النظام لصاحب القرار (اختياري)','Decision-maker’s SADU account (optional)')}</summary><label className="work-field">{t('الحساب','Account')}<select name="decisionMakerAccountId" defaultValue={cur?.decisionMaker.accountId??''}><option value="">{t('خارج النظام — يُسجَّل إذنه فقط','Outside SADU — only their permission is recorded')}</option>{others.map(a=><option key={a.id} value={a.id}>{accountLabel(a,language)}</option>)}</select></label></details>
    <fieldset className="work-fields"><legend>{t('الشروط','Conditions')} ({conditions.length})</legend>{conditions.map((c,i)=><div className="work-field-pair" key={i}>
      <label className="work-field">{t('الفئة','Category')}<select value={c.domain} onChange={e=>edit(i,{domain:e.target.value})}>{(['VENUE','ENGINEERING','FINANCIAL','OTHER'] as const).map(d=><option key={d} value={d}>{treatmentDomains[d][language]}</option>)}</select></label>
      <label className="work-field">{t('الشرط','Condition')}<input required maxLength={500} value={c.text} onInput={e=>edit(i,{text:e.currentTarget.value})} onChange={e=>edit(i,{text:e.target.value})}/></label>
      <button type="button" className="work-secondary" disabled={conditions.length<2} onClick={()=>{setConditions(v=>v.filter((_,n)=>n!==i));mark();}}>{t('إزالة','Remove')}</button></div>)}
      <button type="button" className="work-secondary" disabled={conditions.length>=12} onClick={()=>{setConditions(v=>[...v,{domain:'VENUE',text:''}]);mark();}}>{t('إضافة شرط','Add a condition')}</button></fieldset>
  </Form>;
}

export default function OperationalForms(p:Props) {
  const {task,ops,collection,language,disabled,mark,run,evidenceId,onEvidence,evidenceReady=false}=p;
  const t=(ar:string,en:string)=>language==='ar'?ar:en;
  const r=collection?.record,job=ops.job,pkg=job?.packages.find(v=>v.revision===job.record.version);
  const common={disabled,mark},print=(action:string,data:Record<string,unknown>={})=>run('operations',action,{...data,revision:pkg?.revision});
  // Files for an earlier packing plan or treatment revision, or photographs already submitted, cannot be reused.
  const eligible=(kind:string)=>ops.files.filter(f=>f.kind===kind&&f.currentScope!==false&&!(ops.treatment?.trials.some(x=>x.evidenceId===f.id)));
  const step=ops.treatment?.steps.find(s=>s.key===task.key),cur=ops.treatment?.current??null;
  const revision=cur?.revision;
  const choice=(kind:string,name='evidenceId')=><label className="work-field">{t('الملف قيد المراجعة','File under review')}<select name={name} required value={evidenceId} onChange={e=>onEvidence(e.target.value)}><option value="" disabled>{t('اختر الملف','Select a file')}</option>{eligible(kind).map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>;
  if(task.key==='amendSource'||task.key==='source'&&!r) return <CollectionSource {...p}/>;
  if(task.key==='acceptCollection')return <Form {...common} label={t('قبول مسؤولية الاستلام','Accept collection responsibility')} submit={()=>run('collection','ACCEPT',{})}><p>{t('ستصبح مسؤولاً عن متابعة هذا الاستلام.','You will be responsible for following this collection through.')}</p></Form>;
  if(task.key==='source')return <Form {...common} label={t('تأكيد مصدر البيانات','Confirm source details')} submit={f=>run('collection','CONFIRM',{checked:f.get('checked')==='on'})}><Check name="checked">{t('راجعت العنوان وجهة الاتصال وفترة الإتاحة مقابل المصدر المعروض.','I checked this address, contact and availability against the displayed source.')}</Check>{r?.conflict&&<p role="alert">{t('يلزم حل تعارض المصدر قبل التأكيد.','Resolve the source conflict before confirming.')}</p>}</Form>;
  if(['pickup','amendPickup'].includes(task.key))return <Form {...common} label={t('حفظ موعد الاستلام','Save pickup plan')} submit={f=>run('collection','PLAN',{pickupDate:f.get('pickupDate')})}><Input name="pickupDate" type="date" value={r?.plan?.pickupDate} label={t('موعد الاستلام المقترح','Proposed pickup date')}/><span className="work-hint">{r?.timezone}</span><details className="work-help"><summary>{t('مساعدة','Help')}</summary><p>{t('هذا تخطيط؛ لا يحجز وسيلة نقل.','This records a plan; it does not book transport.')}</p></details></Form>;
  if(task.key==='plan')return <Form {...common} label={t('حفظ خطة التغليف','Save packing plan')} submit={f=>run('collection','PACK',{value:f.get('specification'),packingOwner:f.get('packingOwner'),amount:Number(f.get('amount')),requiresTechnical:f.get('technical')==='yes',technicalReason:f.get('technicalReason')})}>
    <Input name="specification" label={t('طريقة التغليف والحماية','Packing and protection specification')}/><Input name="packingOwner" label={t('اسم المسؤول عن التغليف','Named packing owner')}/><Input name="amount" type="number" min={0} label={t('التكلفة المقترحة بالدرهم','Proposed cost in AED')}/>
    <label className="work-field">{t('المراجعة الفنية','Specialist review')}<select name="technical"><option value="yes">{t('مطلوبة','Required')}</option><option value="no">{t('غير مطلوبة، بسبب موثق','Not required, with recorded reason')}</option></select></label><Input name="technicalReason" required={false} label={t('السبب إذا لم تكن المراجعة مطلوبة','Reason if review is not required')}/>
  </Form>;
  if(['technical','cost'].includes(task.key))return <Form {...common} label={t('تسجيل المراجعة','Record review')} submit={f=>run('collection',task.key==='technical'?'TECHNICAL':'COST',{value:f.get('reference')})}><Input name="reference" label={t('مرجع المراجعة والنتيجة','Review reference and result')}/></Form>;
  if(task.key==='reopen')return <Form {...common} label={t('مراجعة أثر تغيير التغليف','Review packing change impact')} submit={f=>run('collection','REOPEN',{value:f.get('reason')})}><Input name="reason" label={t('ما الذي تغيّر؟','What changed?')}/></Form>;
  if(task.key==='packing')return <Form {...common} submitDisabled={!evidenceReady||!eligible('PACKING').some(f=>f.id===evidenceId)} label={t('تأكيد فحص التغليف','Confirm packing inspection')} submit={f=>run('operations','VERIFY_PACKING',{evidenceId:f.get('evidenceId'),checked:f.get('checked')==='on'})}>{choice('PACKING')}<Check key={evidenceId} name="checked">{t('التغليف مطابق للخطة والصورة أو الملف المرفق.','Packing matches the plan and attached photo or document.')}</Check></Form>;
  if(['package','amendPackage'].includes(task.key))return <Form {...common} submitDisabled={!evidenceReady||!eligible('PRINT_PROOF').some(f=>f.id===evidenceId)} label={t('مراجعة وحفظ أمر الطباعة','Review and save print package')} submit={f=>run('operations','SET_PRINT_PACKAGE',{evidenceId:f.get('evidenceId'),spec:Object.fromEntries(['supplier','quantity','size','stock','finishing','profile','deliveryDate'].map(k=>[k,k==='quantity'?Number(f.get(k)):f.get(k)]))})}>{choice('PRINT_PROOF')}
    {([['supplier','المورد','Supplier'],['quantity','الكمية','Quantity'],['size','المقاس والهوامش','Size and bleed'],['stock','الخامة','Stock'],['finishing','التشطيب','Finishing'],['profile','مواصفات الفحص المتفق عليها','Agreed preflight profile'],['deliveryDate','تاريخ التسليم','Delivery date']] as const).map(([name,ar,en])=><Input key={name} name={name} label={t(ar,en)} value={pkg?.spec[name]} type={name==='quantity'?'number':name==='deliveryDate'?'date':'text'} min={name==='quantity'?1:undefined}/>)}
  </Form>;
  if(task.key==='preflight')return <Form {...common} submitDisabled={!evidenceReady||!eligible('PREFLIGHT').some(f=>f.id===evidenceId)} label={t('تسجيل نتيجة الفحص','Record preflight result')} submit={f=>print('PREFLIGHT',{evidenceId:f.get('evidenceId'),passed:f.get('result')==='pass',note:f.get('note')})}>{choice('PREFLIGHT')}<label className="work-field">{t('النتيجة','Result')}<select name="result"><option value="hold">{t('معلّق — يحتاج إلى تصحيح','Hold — correction needed')}</option><option value="pass">{t('مستوفٍ','Pass')}</option></select></label><Input name="note" label={t('نطاق الفحص والملاحظات','Inspection scope and notes')}/></Form>;
  if(task.key==='editorial')return <Form {...common} label={t('إحالة المراجعة للاعتماد','Submit review for authorization')} submit={f=>print('REVIEW_PRINT',{editorialChecked:f.get('bilingual')==='on',rightsChecked:f.get('rights')==='on'})}><Check name="bilingual">{t('راجعت النص العربي والإنجليزي في هذه البروفة.','I reviewed the Arabic and English text in this proof.')}</Check><Check name="rights">{t('راجعت صلاحيات استخدام المحتوى.','I checked the rights to use this content.')}</Check></Form>;
  if(task.key==='executive')return <Form {...common} label={t('اعتماد هذا الإصدار','Authorize this revision')} submit={f=>print('APPROVE_PRINT',{checked:f.get('checked')==='on'})}><Check name="checked">{t('راجعت الملف والمواصفات الحالية وأوافق عليها.','I reviewed and approve the current file and specification.')}</Check></Form>;
  if(task.key==='dispatch'||task.key==='start')return <Form {...common} label={task.title[language]} submit={()=>print(task.key==='dispatch'?'DISPATCH_PRINT':'START_PRINT')}><p className="work-hint">{t('توثيق تجريبي فقط؛ لا يُرسل طلب إلى المورد.','Local rehearsal record only; no request is sent to a supplier.')}</p></Form>;
  if(task.key==='supplier')return <Form {...common} label={task.title[language]} submit={f=>print('ACK_PRINT',{proofId:pkg?.proofId,sender:f.get('sender'),receivedAt:new Date(String(f.get('receivedAt'))).toISOString(),reference:f.get('reference')})}><Input name="sender" label={t('اسم المرسل من المورد','Supplier sender')}/><Input name="receivedAt" type="datetime-local" label={t('وقت استلام التأكيد بتوقيت جهازك','Acknowledgment received in your device timezone')}/><Input name="reference" label={t('مرجع تأكيد هذا الملف والمواصفات','Confirmation reference for this file and specification')}/></Form>;
  if(['production','delivery'].includes(task.key))return <Form {...common} label={task.title[language]} submit={f=>print(task.key==='production'?'COMPLETE_PRINT':'RECORD_DELIVERY',{quantity:Number(f.get('quantity')),reference:f.get('reference')})}><Input name="quantity" type="number" min={1} label={t('الكمية','Quantity')}/><Input name="reference" label={t('مرجع الإثبات','Evidence reference')}/></Form>;
  if(task.key==='acceptance')return <Form {...common} label={task.title[language]} submit={f=>print('ACCEPT_DELIVERY',{deliveryId:f.get('deliveryId'),checked:f.get('checked')==='on',reference:f.get('reference')})}><label className="work-field">{t('الدفعة المستلمة','Received delivery')}<select name="deliveryId" required>{job?.deliveries.filter(d=>d.revision===pkg?.revision&&!d.acceptance).map(d=><option key={d.id} value={d.id}>{d.quantity} · {d.reference}</option>)}</select></label><Input name="reference" label={t('مرجع فحص الاستلام','Acceptance evidence')}/><Check name="checked">{t('فحصت هذه الدفعة وأقبلها.','I inspected and accept this delivery.')}</Check></Form>;
  if(task.key==='correction'||task.key==='stop')return <Form {...common} label={task.title[language]} submit={f=>print(task.key==='stop'?'STOP_PRINT':'CORRECT_PRINT',task.key==='stop'?{reference:f.get('reference')}:{reason:f.get('reference')})}><Input name="reference" label={task.key==='stop'?t('مرجع تأكيد الإيقاف أو التصرف في المطبوع','Supplier stop or stock disposition reference'):t('سبب التصحيح','Correction reason')}/></Form>;
  if(task.key==='tRecord'||task.key==='amendTreatment')return <TreatmentRecord {...p}/>;
  if(task.key==='tAuthorize'&&step?.authModes?.includes('SADU_APPROVAL')&&revision)return <Form {...common} label={t('اعتماد هذا الإصدار داخل النظام','Approve this revision in SADU')} submit={f=>run('operations','TREATMENT_AUTHORIZE',{revision,mode:'SADU_APPROVAL',checked:f.get('checked')==='on'})}><Check name="checked">{t('راجعت المعالجة والشروط الظاهرة وأوافق على تجربة حرف واحد فقط.','I reviewed the displayed treatment and conditions and approve a one-letter trial only.')}</Check></Form>;
  if(task.key==='tAuthorize'&&revision)return <Form {...common} submitDisabled={!evidenceReady||!eligible('TREATMENT_SOURCE').some(f=>f.id===evidenceId)} label={t('تسجيل الإذن الخارجي','Record external permission')} submit={f=>run('operations','TREATMENT_AUTHORIZE',{revision,mode:'EXTERNAL_PERMISSION',evidenceId:f.get('evidenceId'),reference:f.get('reference'),checked:f.get('checked')==='on'})}>{choice('TREATMENT_SOURCE')}<Input name="reference" label={t('مرجع الإذن','Permission reference')}/><Check key={evidenceId} name="checked">{t(`الملف يثبت إذن ${cur?.decisionMaker.name??''} لهذا الإصدار تحديداً. هذا تسجيل لقرار خارجي، لا اعتماد داخل النظام.`,`The file shows permission from ${cur?.decisionMaker.name??''} for this exact revision. This records an outside decision; it is not an approval in SADU.`)}</Check></Form>;
  if(['tVenue','tEngineering','tFinancial','tOther'].includes(task.key)&&step?.domain)return <Form {...common} label={t('تسجيل استيفاء المتطلب','Record requirement as cleared')} submit={f=>run('operations','TREATMENT_REQUIREMENT',{domain:step.domain,checked:f.get('checked')==='on',reference:f.get('reference')})}><ul className="work-conditions">{cur?.conditions.filter(c=>c.domain===step.domain).map(c=><li key={c.id} dir="auto">{c.text}</li>)}</ul><Check name="checked">{t('راجعت هذا المتطلب بنفسي، وهو مستقل عن بقية المتطلبات.','I reviewed this requirement myself; it is independent of the others.')}</Check><details className="work-help"><summary>{t('تفاصيل اختيارية','Optional details')}</summary><Input name="reference" required={false} label={t('مرجع أو ملاحظة','Reference or note')}/></details></Form>;
  if(task.key==='tSample'&&revision)return <Form {...common} submitDisabled={!evidenceReady||!eligible('TREATMENT_SAMPLE').some(f=>f.id===evidenceId)} label={t('إرسال التجربة لمراجعة الفنان','Submit the trial for artist review')} submit={f=>run('operations','TREATMENT_SUBMIT_SAMPLE',{revision,evidenceId:f.get('evidenceId'),checked:f.get('checked')==='on',note:f.get('note')||undefined})}>{choice('TREATMENT_SAMPLE')}<Check key={evidenceId} name="checked">{t('الصورة تُظهر حرفاً واحداً بعد المعالجة المحددة.','The photograph shows one letter after the specified treatment.')}</Check><details className="work-help"><summary>{t('ملاحظة اختيارية','Optional note')}</summary><Input name="note" required={false} label={t('ملاحظة للفنان','Note for the artist')}/></details></Form>;
  if(task.key==='tArtist'&&revision&&step?.trialId)return <Form {...common} submitDisabled={!evidenceReady||!step.evidenceIds.includes(evidenceId)} label={t('حفظ قرار الفنان','Save the artist’s decision')} submit={f=>run('operations','TREATMENT_ARTIST_DECISION',{revision,trialId:step.trialId,evidenceId,decision:f.get('result'),checked:f.get('checked')==='on',note:f.get('note')||undefined})}><label className="work-field">{t('القرار','Decision')}<select name="result" required defaultValue=""><option value="" disabled>{t('اختر القرار','Choose a decision')}</option><option value="APPROVE">{t('أوافق على هذه الصورة وهذا الإصدار','I approve this photograph and revision')}</option><option value="REQUEST_CHANGES">{t('أطلب تغييرات','I request changes')}</option></select></label><Check key={evidenceId} name="checked">{t(`شاهدت الصورة المعروضة للإصدار ${revision}.`,`I viewed the displayed photograph for revision ${revision}.`)}</Check><details className="work-help"><summary>{t('ملاحظة اختيارية','Optional note')}</summary><Input name="note" required={false} label={t('ملاحظة','Note')}/></details></Form>;
  if(task.key==='tComplete'&&revision)return <Form {...common} submitDisabled={!evidenceReady||!eligible('TREATMENT_COMPLETION').some(f=>f.id===evidenceId)} label={t('تسجيل اكتمال المعالجة','Record completion')} submit={f=>run('operations','TREATMENT_COMPLETE',{revision,evidenceId:f.get('evidenceId'),lettersTreated:Number(f.get('lettersTreated')),note:f.get('note')||undefined})}>{choice('TREATMENT_COMPLETION')}<Input name="lettersTreated" type="number" min={1} label={t('عدد الحروف المعالجة','Letters treated')}/><details className="work-help"><summary>{t('ملاحظة اختيارية','Optional note')}</summary><Input name="note" required={false} label={t('ملاحظة','Note')}/></details></Form>;
  if(task.key==='owners')return <Form {...common} label={t('حفظ تسليم المسؤولية','Save responsibility handoff')} submit={f=>run('collection','ASSIGN',{primaryId:f.get('primaryId'),backupId:f.get('backupId'),activeId:f.get('active')==='backup'?f.get('backupId'):f.get('primaryId'),reason:f.get('reason')})}>
    {(['primaryId','backupId'] as const).map(k=><label className="work-field" key={k}>{k==='primaryId'?t('المسؤول الأساسي','Primary owner'):t('المسؤول البديل','Backup owner')}<select name={k} required defaultValue={collection?.assignment[k]??''}><option value="" disabled>{t('اختر المسؤول','Select owner')}</option>{collection?.accounts.map(a=><option key={a.id} value={a.id}>{accountLabel({...a,role:'Logistics'},language)}</option>)}</select></label>)}
    <label className="work-field">{t('يتولى المهمة الآن','Active responsibility')}<select name="active" defaultValue={collection?.assignment.activeId===collection?.assignment.backupId?'backup':'primary'}><option value="primary">{t('المسؤول الأساسي','Primary owner')}</option><option value="backup">{t('المسؤول البديل','Backup owner')}</option></select></label><Input name="reason" label={t('سبب تسليم المسؤولية','Handoff reason')}/><details className="work-help"><summary>{t('مساعدة','Help')}</summary><p>{t('يلزم قبول جديد. لا تنتقل صلاحيات الاعتماد إلى البديل.','Fresh acceptance is required. Approval authority is not transferred.')}</p></details>
  </Form>;
  return null;
}
