import {useEffect,useRef,useState} from 'react';
import {PackageSearch} from 'lucide-react';
import {pilotSupabase as client} from '../lib/pilotSupabase';
type Scope={scenario_id:string;expected_count:number;approved_at:string};
export function PendingAssetTracker(){
 const [scenarios,setScenarios]=useState<{id:string;contract_id:string}[]>([]),[scopes,setScopes]=useState<Scope[]>([]),[labels,setLabels]=useState<{scenario_id:string}[]>([]),[queued,setQueued]=useState<string[]>([]),[role,setRole]=useState(''),[message,setMessage]=useState('');
 const [id,setId]=useState(''),[count,setCount]=useState(''),[reference,setReference]=useState(''),[busy,setBusy]=useState(false);const epoch=useRef(0),running=useRef(false);
 async function load(){const version=++epoch.current;if(!client)return;try{const u=await client.auth.getUser();const results=await Promise.all([client.from('sadu_exhibition_scenarios').select('id,contract_id'),client.from('sadu_asset_scope').select('*'),client.from('sadu_artwork_checklist').select('scenario_id'),client.from('sadu_asset_reminders').select('scenario_id').eq('status','PENDING_DELIVERY')]);if(version!==epoch.current)return;if(results.some(r=>r.error)){setScenarios([]);setMessage('Asset tracking unavailable — sign in and verify local schema.');return;}setRole(u.data.user?.app_metadata?.institutional_role??'');setScenarios(results[0].data??[]);setScopes(results[1].data??[]);setLabels(results[2].data??[]);setQueued((results[3].data??[]).map(r=>r.scenario_id));setMessage('Database scope tracking · refreshes every 15 seconds');}catch{if(version===epoch.current){setScenarios([]);setMessage('Asset tracking unavailable.');}}}
 useEffect(()=>{let active=true;void load();const timer=setInterval(()=>void load(),15000);const sub=client?.auth.onAuthStateChange(()=>{epoch.current++;setScenarios([]);setRole('');setTimeout(()=>{if(active)void load();},0);});return()=>{active=false;epoch.current++;clearInterval(timer);sub?.data.subscription.unsubscribe();};},[]);
 return <section className="space-y-3 rounded border bg-[#F7F1E6] ps-4 pe-4 py-4 text-start"><h2 className="flex gap-2 text-xl"><PackageSearch aria-hidden="true"/>Pending Assets / الأصول المعلقة</h2><p role="status">{message}</p>{role==='BIENNIAL_DIRECTOR'&&<form className="grid gap-2" onSubmit={async e=>{e.preventDefault();if(!client||running.current||!id||!Number.isInteger(+count)||+count<1||+count>3000||reference.trim().length<3)return;running.current=true;setBusy(true);try{const r=await client.from('sadu_asset_scope').insert({scenario_id:id,expected_count:+count,approval_reference:reference.trim()});if(r.error)setMessage('Scope receipt failed or already recorded.');else await load();}catch{setMessage('Scope save interrupted — refresh before retry.');}finally{running.current=false;setBusy(false);}}}><label>Reviewed Stage 5 scope<select className="block w-full border ps-2 pe-2 py-2" value={id} onChange={e=>setId(e.target.value)}><option value="">Select contract</option>{scenarios.filter(s=>!scopes.some(a=>a.scenario_id===s.id)).map(s=><option key={s.id} value={s.id}>{s.contract_id}</option>)}</select></label><label>Approved artwork count<input className="block w-full border ps-2 pe-2 py-2" type="number" min="1" max="3000" value={count} onChange={e=>setCount(e.target.value)}/></label><label>Decision reference<input className="block w-full border ps-2 pe-2 py-2" maxLength={500} value={reference} onChange={e=>setReference(e.target.value)}/></label><button disabled={busy||!id||!Number.isInteger(+count)||+count<1||reference.trim().length<3} className="rounded border ps-3 pe-3 py-2 disabled:opacity-50">Record approved scope count</button></form>}{scenarios.map(s=>{const scope=scopes.find(a=>a.scenario_id===s.id),received=labels.filter(a=>a.scenario_id===s.id).length;return <article key={s.id} className="border-s-4 ps-3"><h3>{s.contract_id}</h3><p className={!scope||received!==scope.expected_count?'text-red-800':'text-green-800'}>{!scope?'Approved count not recorded':received<scope.expected_count?`PENDING_ASSET · ${received}/${scope.expected_count}`:received>scope.expected_count?'Scope mismatch — additional works require review':`Bundled artwork records complete · ${received}/${scope.expected_count}`}</p>{queued.includes(s.id)&&<p>48-hour reminder queued — email delivery not configured.</p>}</article>})}</section>;
}
