import { useState } from 'react';
import { useDemoCheckpoint } from '../lib/useDemoCheckpoint';
import { CommunicationConfirmation } from './CommunicationConfirmation';
import { NextActionCard } from './NextActionCard';
import LocalHandoffRegister from './LocalHandoffRegister';
import { handoffPhase } from '../data/handoffRegister';
import { backupOfficers, createCollectionDemo, collectionTransition, collectionTask, validCollectionDemo, type CollectionCommand } from '../data/collectionReadiness';
export { pickupError } from '../data/collectionReadiness';

export default function PitchCollectionDemo() {
  const [record, setRecord, recoveryWarning] = useDemoCheckpoint('sadu:pitch:collection:v2', createCollectionDemo, validCollectionDemo);
  const [error, setError] = useState('');
  const [communicationOpen, setCommunicationOpen] = useDemoCheckpoint('sadu:pitch:message-open:v2', () => false, v => typeof v === 'boolean');
  const [run, setRun] = useDemoCheckpoint('sadu:pitch:message-run:v2', () => 0, v => Number.isInteger(v));
  const task = collectionTask(record);
  const stage = record.stage;
  function act(type: CollectionCommand['type'], fields: Partial<CollectionCommand> = {}) {
    try { setRecord(collectionTransition(record, { type, actor: task.owner, version: record.version, at: new Date().toISOString(), ...fields })); setError(''); }
    catch (e) { setError(e instanceof Error ? e.message : 'Please review the current task.'); }
  }
  const evidence = record.packing ? { source: record.packing.evidence || record.packing.costReference || record.packing.technicalReference || 'Synthetic packing proposal', sender: 'Not independently verified; synthetic evidence reference', receivedAt: 'Not recorded; these are simulated entries', revision: `Collection task v${record.version}`, recordedBy: record.packing.evidence ? record.owner : record.packing.costReference ? 'Demo Finance' : record.packing.technicalReference ? 'Demo Technical' : record.owner, confirmation: record.packing.evidence ? 'Completion check recorded in demo; no independent verification' : record.packing.costReference ? 'Simulated cost authorization only; packing completion pending' : record.packing.technicalReference ? 'Technical clearance recorded; cost approval pending' : 'Proposed packing plan; technical review pending' } : { source: 'DEMO-001 · prepared collection sheet', sender: 'Synthetic gallery representative', receivedAt: 'Prepared fixture; no actual message received', revision: 'Collection details v1', recordedBy: 'Demo Logistics A', confirmation: 'Address confirmed in fixture; packaging explicitly missing. No institutional approval.' };
  return <section id="experience" className="sadu-experience">
    <p className="sadu-boundary">Separate English practice case · This has its own saved record. Your guided presentation remains saved; its progress is not transferred here.</p>
    <div className="sadu-section-heading"><div><p className="sadu-eyebrow">THE DEMONSTRATION / YOUR TURN</p><h2>Make this collection ready.<br/><em>Resolve one handoff at a time.</em></h2></div><p>The address is confirmed. Start by marking the owner unavailable, then follow the next action through backup acceptance, date validation and packing evidence. All records are synthetic; nothing is sent, booked or paid.</p></div>
    <div className="sadu-demo-toolbar"><p>Simulated desk: <strong>{task.owner}</strong> · Task revision {record.version}</p><button onClick={() => { setRecord(createCollectionDemo()); setError(''); setCommunicationOpen(false); setRun(n => n + 1); }}>Reset demonstration</button></div>
    <div className="sadu-live-example"><div className="sadu-example-context"><small>DEMO-001 · SYNTHETIC COLLECTION</small><h3>Study in Blue</h3><p>Artist: Demo Artist 01<br/>Collection: 12 Example Lane, Paris, France<br/>Available: 1–31 October 2026<br/>Closed: 10–15 October · Europe/Paris</p><p className="sadu-boundary">Fixed rehearsal dates, not a live shipping calendar.</p><p>Pickup: {record.date || 'Not planned'}<br/>Packing: {record.packing?.evidence ? 'Completion evidence recorded' : 'Not ready'}<br/>Transport: Not booked<br/>Physical collection: Not recorded</p>{record.packing && <details><summary>Packing plan</summary><p>{record.packing.specification}<br/>Owner: {record.packing.owner}<br/>Proposed cost: AED {record.packing.amount}<br/>Technical clearance: {record.packing.technicalReference || 'Pending'}<br/>Finance reference: {record.packing.costReference || 'Pending'}<br/>Completion: {record.packing.evidence || 'Pending'}</p></details>}</div>
    <div className="sadu-example-result"><NextActionCard title={task.title} owner={task.owner} blocker={task.blocker} evidence={evidence}>
      {stage === 'confirmed' && <button className="sadu-cta" onClick={() => act('ABSENT')}>Mark owner unavailable</button>}
      {stage === 'unavailable' && <form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); act('ASSIGN', { value: String(f.get('backup')), reason: String(f.get('reason')) }); }}><label htmlFor="collection-backup">Backup Logistics officer</label><select id="collection-backup" name="backup" required defaultValue=""><option value="">Choose a backup</option>{backupOfficers.map(name => <option key={name}>{name}</option>)}</select><label htmlFor="collection-reason">Reason for the handoff</label><input id="collection-reason" name="reason" required maxLength={160}/><button className="sadu-cta">Assign backup</button></form>}
      {stage === 'acceptance' && <><button className="sadu-cta" onClick={() => act('ACCEPT')}>Accept responsibility as {record.owner}</button><details><summary>Backup also unavailable?</summary><button onClick={() => act('ASSIGN', { actor: 'Coordinator', value: record.owner === 'Logistics B' ? 'Logistics C' : 'Logistics B', reason: 'Original backup unavailable before acceptance (synthetic).' })}>Coordinator: assign the other backup</button></details></>}
      {stage === 'pickup' && !communicationOpen && <button onClick={() => setCommunicationOpen(true)}>Resolve an incoming date discrepancy</button>}
      {stage === 'pickup' && !communicationOpen && <form noValidate onSubmit={e => { e.preventDefault(); act('DATE', { value: String(new FormData(e.currentTarget).get('date')) }); }}><label htmlFor="collection-date">Pickup date · Europe/Paris</label><input id="collection-date" name="date" type="date" defaultValue="2026-10-12" aria-describedby="collection-date-help collection-error" aria-invalid={Boolean(error)}/><p id="collection-date-help">Try 12 October: the gallery is closed. December is outside the window and will not be silently corrected.</p><button className="sadu-cta">Validate & save pickup plan</button></form>}
      {stage === 'packing' && <form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); act('PACK', { value: String(f.get('spec')), packingOwner: String(f.get('owner')), amount: Number(f.get('amount')), requiresTechnical: true }); }}><label htmlFor="packing-spec">Packing specification · synthetic proposal</label><input id="packing-spec" name="spec" required maxLength={300} defaultValue="Custom crate and protective supports, subject to specialist review"/><label htmlFor="packing-owner">Packing task owner</label><input id="packing-owner" name="owner" required maxLength={100} defaultValue="Demo packing contractor"/><label htmlFor="packing-amount">Proposed packing cost · AED</label><input id="packing-amount" name="amount" required type="number" min="0" step="0.01" defaultValue="1200"/><button className="sadu-cta">Submit packing plan for technical review</button></form>}
      {stage === 'technical-review' && <form onSubmit={e => { e.preventDefault(); act('TECHNICAL', { value: String(new FormData(e.currentTarget).get('ref')) }); }}><p>The assigned specialist checks the packing specification. This clearance does not authorize expenditure.</p><label htmlFor="packing-technical">Technical clearance reference</label><input id="packing-technical" name="ref" required maxLength={160} placeholder="DEMO-TECH-01"/><button className="sadu-cta">Record technical clearance</button></form>}
      {stage === 'cost-review' && <form onSubmit={e => { e.preventDefault(); act('COST', { value: String(new FormData(e.currentTarget).get('ref')) }); }}><p>Finance simulation: AED {record.packing?.amount}. Record a sample authorization reference. This does not issue a payment or certify packing safety.</p><label htmlFor="packing-cost">Sample cost approval reference</label><input id="packing-cost" name="ref" required maxLength={160} placeholder="DEMO-COST-01"/><button className="sadu-cta">Record simulated cost approval</button></form>}
      {stage === 'pack-evidence' && <form onSubmit={e => { e.preventDefault(); act('EVIDENCE', { value: String(new FormData(e.currentTarget).get('ref')) }); }}><p>{record.owner} checks the completed packing against the plan. Use a synthetic completion record reference.</p><label htmlFor="packing-evidence">Packing completion evidence reference</label><input id="packing-evidence" name="ref" required maxLength={160} placeholder="DEMO-PACKING-CHECK-01"/><button className="sadu-cta">Confirm packing readiness</button></form>}
      {stage === 'ready' && <><p className="sadu-demo-feedback">The backup accepted, the date is valid and packing completion is recorded. Ready for booking review; no freight is booked and no asset is collected.</p><a className="sadu-text-link" href="#presentation">What this proves—and what we propose next →</a><details><summary>Packing changed?</summary><form onSubmit={e => { e.preventDefault(); act('REOPEN', { value: String(new FormData(e.currentTarget).get('reason')) }); }}><label htmlFor="packing-change">Reason for reopening</label><input id="packing-change" name="reason" required maxLength={160}/><button>Reopen packing checks</button></form></details></>}
      {recoveryWarning && <p role="alert">{recoveryWarning}</p>}<p id="collection-error" role="alert" className="sadu-demo-error">{error}</p>
    </NextActionCard>
    {communicationOpen && <CommunicationConfirmation key={run} checkpointKey={`sadu:pitch:message:v2:${run}`} onApply={(date, source) => {
      const next = collectionTransition(record, { type: 'DATE', actor: record.owner, version: record.version, at: new Date().toISOString(), value: date, reason: `Confirmed response ${source}; original SYNTHETIC-VOICE-01 says 3 December 2026 and is preserved.` });
      setRecord(next); setError('');
    }}/>}</div></div>
    <details className="sadu-demo-history"><summary>What this record remembers ({record.history.length})</summary><ol><li>Prepared fixture: address confirmed; packaging missing.</li>{record.history.map((e, i) => <li key={i}>{e.actor} · {e.action} · task v{e.version} · {new Date(e.at).toLocaleString('en-GB', { timeZone: 'Asia/Dubai' })} Dubai</li>)}</ol></details>
    <p className="sadu-example-foot">Synthetic tab checkpoint · Saved steps resume after refresh or unlock · Reset starts a fresh example · No external action.</p>
    {(import.meta.env.DEV || import.meta.env.VITE_LOCAL_SOURCE_REGISTER === 'true') && <LocalHandoffRegister phase={handoffPhase(stage)}/>}
  </section>;
}
