import { useState } from 'react';
import { useDemoCheckpoint } from '../lib/useDemoCheckpoint';
import { NextActionCard } from './NextActionCard';
import { createCuratorialHandoff, curatorialOwner, curatorialTransition, recommendedProposal, type CuratorialCommand } from '../data/curatorialHandoff';
export default function PitchCuratorialDemo() {
  const [record, setRecord, recoveryWarning] = useDemoCheckpoint('sadu:pitch:curatorial:v3', createCuratorialHandoff, (v: any) => Array.isArray(v?.history) && typeof v?.proposal?.title === 'string' && typeof v?.alternative?.title === 'string' && [null, 'A', 'B', 'NONE'].includes(v.selectedCandidate) && Number.isInteger(v.version));
  const [error, setError] = useState('');
  const owner = curatorialOwner(record);
  const selected = recommendedProposal(record);
  const names = { Coordinator: 'Coordinator / المنسقة', Specialist: 'Assigned specialist / المراجع المختص', Committee: 'Preparatory Committee / اللجنة التحضيرية', Director: 'Director / مدير الملتقى' };
  const tasks = { proposal: 'Prepare a proposal', completeness: 'Check completeness and identify concerns', specialist: 'Resolve the specialist review', committee: 'Compare proposals and record a recommendation', executive: 'Record the executive decision', approved: 'Prepare the invitation from the approved revision', invitation: 'Invitation prepared; external dispatch paused', returned: 'Address the review findings', 'not-recommended': 'Prepare a revised comparison' };
  function act(type: CuratorialCommand['type'], data: Partial<CuratorialCommand> = {}) {
    try { setRecord(curatorialTransition(record, { type, actor: owner, version: record.version, at: new Date().toISOString(), ...data })); setError(''); }
    catch (e) { setError(e instanceof Error ? e.message : 'Not saved. Review the current task.'); }
  }
  return <section id="curatorial-handoff" className="sadu-experience"><div className="sadu-section-heading"><div><p className="sadu-eyebrow">CURATORIAL HANDOFF / مسار الاختيار</p><h2>A recommendation.<br/><em>Then a distinct decision.</em></h2></div><p>Synthetic programme brief: existing calligraphic works for one sample wall. Review completeness, route specialist concerns, compare proposals and preserve the authorized revision.</p></div><details><summary>Try the proposal-to-invitation journey</summary><div className="sadu-print-desk">
    <div className="sadu-demo-toolbar"><p>Proposal revision {record.revision} · Simulated desk: {names[owner]}</p><button onClick={() => { setRecord(createCuratorialHandoff()); setError(''); }}>Reset curatorial demonstration</button></div>
    <NextActionCard title={tasks[record.stage]} owner={names[owner]} blocker={record.stage === 'executive' ? 'The Committee recommendation is not executive approval.' : record.stage === 'invitation' ? 'No invitation has been sent and no agreement is executed.' : record.stage === 'committee' ? 'Both candidates have reached comparison; no candidate has been selected.' : record.stage === 'not-recommended' ? 'Neither candidate has a recommendation to advance.' : 'This revision needs the named owner’s review before it can advance.'}/>
    <p>Candidate B: {record.alternative.title} — {record.alternative.rationale}</p><p><strong>Candidate A: {record.proposal.title}</strong> · {record.proposal.rationale}</p>
    {record.stage === 'proposal' && <form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); act('SUBMIT', { title: String(f.get('title')), rationale: String(f.get('rationale')), alternativeTitle: String(f.get('alternativeTitle')), alternativeRationale: String(f.get('alternativeRationale')) }); }}><label>Proposal title<input name="title" required maxLength={160} defaultValue={record.proposal.title}/></label><label>Thematic rationale<textarea name="rationale" required maxLength={1000} defaultValue={record.proposal.rationale}/></label><label>Candidate B title<input name="alternativeTitle" required maxLength={160} defaultValue={record.alternative.title}/></label><label>Candidate B thematic rationale<textarea name="alternativeRationale" required maxLength={1000} defaultValue={record.alternative.rationale}/></label><button>Submit both candidates for completeness review</button></form>}
    {record.stage === 'completeness' && <form onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); act('CHECK', { note: String(f.get('note')), requiresSpecialist: f.get('specialist') === 'yes' }); }}><label>Completeness findings and concerns for both candidates<textarea name="note" required maxLength={1000}/></label><label>Specialist review required?<select name="specialist" required defaultValue=""><option value="">Choose based on the evidence</option><option value="yes">Yes — refer the specific concern</option><option value="no">No — record why in the findings</option></select></label><button>Record completeness check</button></form>}
    {record.stage === 'committee' && <div><h3>Comparison against the same brief</h3><p>Candidate A: {record.proposal.title} · ink on paper · 100 × 70 cm · proposed cost AED 2,000.</p><p>Candidate B: {record.alternative.title} · ink on paper · 120 × 80 cm · proposed cost AED 2,500.</p><p>Both are synthetic alternatives. Recommend either candidate, recommend neither, or return the comparison for correction. Cost alone does not establish artistic merit.</p></div>}
    {(['specialist', 'committee', 'executive'] as string[]).includes(record.stage) && <form key={record.stage} onSubmit={e => { e.preventDefault(); act(record.stage === 'specialist' ? 'SPECIALIST' : record.stage === 'committee' ? 'RECOMMEND' : 'APPROVE', { note: String(new FormData(e.currentTarget).get('note')), candidate: new FormData(e.currentTarget).get('candidate') as CuratorialCommand['candidate'] }); }}>{record.stage === 'committee' && <label>Committee recommendation<select name="candidate" required defaultValue=""><option value="">Choose an outcome</option><option value="A">Candidate A — {record.proposal.title}</option><option value="B">Candidate B — {record.alternative.title}</option><option value="NONE">Neither candidate</option></select></label>}<label>{record.stage === 'specialist' ? 'Specialist finding and source reference for both candidates' : record.stage === 'committee' ? 'Comparison rationale and recommendation minute' : 'Executive decision reason'}<textarea name="note" required maxLength={1000}/></label><button>{record.stage === 'specialist' ? 'Record specialist review completed' : record.stage === 'committee' ? 'Record recommendation — not approval' : 'Approve this proposal revision'}</button></form>}
    {record.stage === 'approved' && <button onClick={() => act('PREPARE')}>Prepare invitation preview</button>}
    {record.stage === 'invitation' && <article><h3>Unsent invitation preview · revision {record.revision}</h3><p>Dear Demo Artist {record.selectedCandidate === 'B' ? '02' : '01'}, you are invited to submit the existing calligraphic work “{selected?.title}” within the sample wall brief.</p><p>No secure link, email, contract or financial commitment is generated by this demonstration.</p><a className="sadu-text-link" href="#experience">Explore collection readiness →</a></article>}
    {record.recommendation && <p>Committee minute ({record.selectedCandidate === 'NONE' ? 'neither candidate' : selected?.title}): {record.recommendation}</p>}{record.decision && <p>Executive decision: {record.decision}</p>}
    {record.stage !== 'proposal' && <details><summary>{['approved', 'invitation', 'returned', 'not-recommended'].includes(record.stage) ? 'Amend this proposal' : 'Return this item for correction'}</summary><form onSubmit={e => { e.preventDefault(); act(['approved', 'invitation', 'returned', 'not-recommended'].includes(record.stage) ? 'REVISE' : 'RETURN', { note: String(new FormData(e.currentTarget).get('reason')) }); }}><label>Reason for return or amendment<textarea name="reason" required maxLength={1000}/></label><button>Record reason and return to owner</button></form></details>}
    {record.stage === 'returned' && <p role="status">Reason: {record.note}</p>}{record.stage === 'not-recommended' && <p role="status">Neither candidate advances. Revise the comparison before seeking a new recommendation.</p>}<p role="alert">{error || recoveryWarning}</p>
    <details><summary>Revision and decision history ({record.history.length})</summary><ol>{record.history.map((e, i) => <li key={i}>v{e.revision} · {e.action} · {e.actor} · {e.note} · {e.at}</li>)}</ol></details>
  </div></details></section>;
}
