import { useEffect, useRef, useState } from 'react';
import { Printer, MonitorPlay, Wrench } from 'lucide-react';
import type { ArtworkLabel, ArtworkRoster } from '../data/artworkRoster';
import { pdfHasSignature } from '../data/visaIntake';
import { useSessionDraft } from '../context/SessionDrafts';
const field='mt-2 block w-full rounded border bg-white ps-3 pe-3 py-2';
export function ProductionSpecsInput({item,onEdit,isAr}:{item:ArtworkLabel;onEdit:(patch:Partial<ArtworkLabel>)=>void;isAr:boolean}){
 const [error,setError]=useState('');const serial=useRef(0);
 useEffect(()=>()=>{serial.current++;},[]);
 return <section className="space-y-3 rounded border bg-[#F7F1E6] ps-4 pe-4 py-4 text-start"><label className="flex items-center gap-2"><input type="checkbox" checked={Boolean(item.productionEnabled)} onChange={e=>{serial.current++;setError('');onEdit({productionEnabled:e.target.checked,technicalPDF:undefined,technicalPDFVerified:false});}}/><Wrench aria-hidden="true"/>مواصفات الإنتاج والعرض / Production &amp; Display Specs</label>{item.productionEnabled&&<><label className="block"><Printer aria-hidden="true"/>{isAr?'الطباعة والتأطير — نوع الورق، مقطع الإطار، الأبعاد':'Printing & Framing — paper type, frame profile, dimensions'}<textarea rows={3} maxLength={4000} className={field} value={item.printingFraming??''} onChange={e=>onEdit({printingFraming:e.target.value})}/></label><label className="block"><MonitorPlay aria-hidden="true"/>{isAr?'متطلبات العرض — حجم الشاشة، الإسقاط، إعدادات الصوت':'AV Requirements — screen size, projection, audio loop settings'}<textarea rows={3} maxLength={4000} className={field} value={item.avRequirements??''} onChange={e=>onEdit({avRequirements:e.target.value})}/></label><p className="text-sm">{isAr?'أدخل مواصفات الطباعة أو العرض أو كليهما.':'Provide printing/framing or AV requirements, or both.'}</p><label className="block border-2 border-dashed ps-4 pe-4 py-4">الملفات التقنية / Technical Sheets &amp; Schematics — PDF only, max 10 MB<input type="file" accept=".pdf,application/pdf" onChange={async e=>{const file=e.target.files?.[0],token=++serial.current;setError('');onEdit({technicalPDF:file,technicalPDFVerified:false});if(!file)return;try{const valid=await pdfHasSignature(file);if(token!==serial.current)return;if(!valid){setError('Choose a valid PDF up to 10 MB.');return;}onEdit({technicalPDF:file,technicalPDFVerified:true});}catch{if(token===serial.current)setError('Unable to read PDF. Please select another file.');}}}/></label>{item.technicalPDF&&<p>{item.technicalPDF.name} · {item.technicalPDFVerified?'PDF format checked':'Not validated — submission blocked'}</p>}{error&&<p role="alert" className="text-red-800">{error}</p>}</>}</section>;
}
function TechnicalDownload({file}:{file:File}){const [url,setUrl]=useState('');useEffect(()=>{const u=URL.createObjectURL(file);setUrl(u);return()=>URL.revokeObjectURL(u);},[file]);return <a href={url||undefined} download={file.name} className="break-all underline">{file.name}</a>;}
export function ProductionSpecsLedger({artistId,contractId,isAr}:{artistId:string;contractId:string;isAr:boolean}){
 const [all]=useSessionDraft<Record<string,ArtworkRoster>>('artwork-rosters:v1',{});
 const roster=all[artistId],latest=roster?.history.at(-1);
 return <section className="my-5 space-y-4 rounded border border-[#D9CEBA] bg-[#F7F1E6] ps-5 pe-5 py-5 text-start"><h2 className="flex items-center gap-2 text-xl font-semibold"><Wrench aria-hidden="true"/>{isAr?'سجل مواصفات الإنتاج والعرض':'Production & AV Specs Ledger'}</h2><p>Installation ticket: {contractId} · Artist: {artistId}</p><p className="text-sm">Submitted artist instructions — not engineering approval. Session-only sample files.</p>{!latest?<p>No submitted artwork specifications yet.</p>:<><p>Submitted revision {latest.revision} · {latest.at}</p>{roster.status!=='LOCKED_PENDING_REVIEW'&&<p role="status" className="text-amber-900">Amendment in progress — prior submitted instructions shown. Reconfirm before execution.</p>}{latest.items.map(item=><details key={item.id} className="rounded border bg-white ps-4 pe-4 py-3"><summary className="cursor-pointer font-semibold">{item.titleAr} / {item.titleEn}</summary><p>Artwork dimensions: {item.height} × {item.width} × {item.depth} cm</p>{item.productionEnabled?<><h3 className="mt-3 flex items-center gap-2"><Printer aria-hidden="true"/>Printing &amp; Framing</h3><p className="whitespace-pre-wrap break-words">{item.printingFraming?.trim()||'Not specified'}</p><h3 className="mt-3 flex items-center gap-2"><MonitorPlay aria-hidden="true"/>AV Requirements</h3><p className="whitespace-pre-wrap break-words">{item.avRequirements?.trim()||'Not specified'}</p>{item.technicalPDF&&item.technicalPDFVerified?<TechnicalDownload file={item.technicalPDF}/>:<p>No technical PDF submitted.</p>}</>:<p>No production specifications declared.</p>}</details>)}</>}</section>;
}
