import {completeLabelGroups,type CatalogArtwork} from '../data/catalogFreight';
import {useEffect,useRef,useState} from 'react';
import {BookOpen,CheckCircle,Clock,Download,Globe} from 'lucide-react';
import {pilotSupabase as client} from '../lib/pilotSupabase';
import {useOperationalRows} from '../lib/useOperationalRows';
import type {ExhibitionTitle} from './ExhibitionTitleGate';
const panel='space-y-3 rounded border bg-[#F7F1E6] ps-4 pe-4 py-4 text-start';
const button='rounded border ps-3 pe-3 py-2 disabled:opacity-50';
export function ExhibitionTitleHeader({scenarioId}:{scenarioId?:string}){
 const q=useOperationalRows<ExhibitionTitle>('sadu_exhibition_titles',scenarioId?{column:'scenario_id',value:scenarioId}:undefined);
 return <header className={panel}><h2 className="flex gap-2 text-xl"><BookOpen aria-hidden="true"/>Exhibition identity / هوية المعرض</h2>{q.rows.map(r=><div key={r.scenario_id}><h3><bdi>{r.title_ar}</bdi> / <bdi>{r.title_en}</bdi></h3><p>{r.status==='LOCKED'?'Curator approved / معتمد':'Pending curator review / بانتظار الاعتماد'} · {r.scenario_id}</p></div>)}{!q.rows.length&&<p>{q.notice||'Loading exhibition title…'}</p>}</header>;
}
type Media={scenario_id:string;object_name:string;file_name:string;category:string;received:boolean;received_at:string|null;reviewed_at:string|null};
type Publication={scenario_id:string;status:string;approved_at:string;delivered_at:string|null;sync_status?:string;last_error?:string|null};
export function PublicationHandoff({scenarioId,editorial=false}:{scenarioId?:string;editorial?:boolean}){
 const filter=scenarioId?{column:'scenario_id',value:scenarioId}:undefined;
 const files=useOperationalRows<Media>('sadu_media_inventory',filter),publications=useOperationalRows<Publication>('sadu_publication_queue',filter);
 const titles=useOperationalRows<ExhibitionTitle>('sadu_exhibition_titles',filter),labels=useOperationalRows<CatalogArtwork>('sadu_artwork_checklist',filter),scopes=useOperationalRows<{scenario_id:string;expected_count:number}>('sadu_asset_scope',filter);
 const complete=completeLabelGroups(labels.rows,scopes.rows);
 const ready=(id:string)=>titles.rows.some(t=>t.scenario_id===id&&t.status==='LOCKED')&&complete.some(a=>a.scenario_id===id)&&complete.filter(a=>a.scenario_id===id).every(a=>files.rows.some(f=>f.object_name===a.media_object_name&&f.received&&f.reviewed_at));
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[inspected,setInspected]=useState<Record<string,boolean>>({});const epoch=useRef(0),running=useRef(false);
 useEffect(()=>{const auth=client?.auth.onAuthStateChange(()=>{epoch.current++;setInspected({});setMessage('');setBusy(false);});return()=>{epoch.current++;auth?.data.subscription.unsubscribe();};},[]);
 async function action(work:()=>Promise<void>,notice='Action recorded. Website publication remains pending.'){if(running.current)return;running.current=true;setBusy(true);const gen=epoch.current;try{await work();if(gen!==epoch.current)return;await Promise.all([files.refresh(),publications.refresh()]);if(gen===epoch.current)setMessage(notice);}catch{if(gen===epoch.current)setMessage('Not completed. Check complete text/title approval, media reviews, account permissions and the database connection.');}finally{running.current=false;if(gen===epoch.current)setBusy(false);}}
 async function open(f:Media){if(!client)return;const gen=epoch.current;const r=await client.storage.from('logistics-secure').createSignedUrl(f.object_name,60,{download:f.file_name});if(r.error)throw r.error;if(gen!==epoch.current)return;const a=document.createElement('a');a.href=r.data.signedUrl;a.rel='noopener';a.click();}
 const ids=Array.from(new Set(files.rows.map(f=>f.scenario_id)));
 return <section className={panel}><h2 className="flex gap-2 text-xl"><Globe aria-hidden="true"/>Asset receipts & website publication / استلام الأصول والنشر</h2><p>Upload receipt, Editorial media approval and website delivery are separate. Private files are not made public by this queue.</p>{files.rows.map(f=><article key={f.object_name} className="space-y-2 rounded border bg-[#FFFDF7] ps-3 pe-3 py-3"><p className="break-all">{f.category} · {f.file_name}</p><p>{f.received?'File received / تم استلام الملف':'Upload incomplete or unavailable / الملف غير مكتمل'} · <bdi>{f.received_at?new Date(f.received_at).toLocaleString():'No receipt'}</bdi></p><p className={f.received&&f.reviewed_at?'text-green-800':'text-amber-900'}>{f.received&&f.reviewed_at?<CheckCircle className="inline size-4" aria-hidden="true"/>:<Clock className="inline size-4" aria-hidden="true"/>} {f.received&&f.reviewed_at?'Editorial media approved / اعتمد التحرير الملف':'Not approved for publication / لم يعتمد للنشر'} <bdi>{f.reviewed_at?new Date(f.reviewed_at).toLocaleString():''}</bdi></p><button className={button} disabled={busy||!f.received} onClick={()=>void action(()=>open(f),'Private download requested; no approval was recorded.')}><Download className="inline size-4" aria-hidden="true"/>Inspect private file / عرض الملف</button>{editorial&&f.category!=='BLUEPRINT'&&!f.reviewed_at&&<><label className="flex gap-2"><input type="checkbox" disabled={busy||!f.received} checked={Boolean(inspected[f.object_name])} onChange={e=>setInspected({...inspected,[f.object_name]:e.target.checked})}/>I reviewed this exact file and approve it for public use / راجعت الملف وأعتمد استخدامه للنشر</label><button className={button} disabled={busy||!f.received||!inspected[f.object_name]} onClick={()=>void action(async()=>{if(!client)throw new Error();const r=await client.from('sadu_media_reviews').insert({object_name:f.object_name});if(r.error)throw r.error;})}>Approve media / اعتماد الملف</button></>}</article>)}{editorial&&ids.map(id=><div key={id}><ExhibitionTitleHeader scenarioId={id}/><button className={button} disabled={busy||!ready(id)||publications.rows.some(p=>p.scenario_id===id)} onClick={()=>void action(async()=>{if(!client)throw new Error();const r=await client.from('sadu_publication_queue').insert({scenario_id:id});if(r.error)throw r.error;})}>Ready for Public — queue approved snapshot / جاهز للنشر</button>{!ready(id)&&<p>Locked: complete curator title, bilingual text and individual media approvals first.</p>}</div>)}{publications.rows.map(p=><p key={p.scenario_id}>{p.scenario_id}: {p.sync_status??p.status}{p.last_error?' · '+p.last_error:''} · Approved {p.approved_at}{p.delivered_at?' · Delivered '+p.delivered_at:' · Not published to website'}</p>)}<p role="status">{message||files.notice||publications.notice}</p><p>Server sync requires an approved CMS endpoint and running worker. Pending_Sync is not live publication.</p></section>;
}
