import { useState } from 'react';
import { Globe, MapPin, Users } from 'lucide-react';
import { COORDINATORS } from '../data/participation2026';
import { artistRegion, REGIONS, type Region } from '../data/regionalDelegation';
import type { NominatedArtistDossier } from './ArtistNominationForm';
export interface RegionalDelegationProps {dossiers:NominatedArtistDossier[];isAr:boolean;canDelegate?:boolean;lockedIds?:string[];onDelegate?:(region:Region,target:string)=>void;notice?:string}
export function RegionalDelegation({dossiers,isAr,canDelegate=false,lockedIds=[],onDelegate,notice}:RegionalDelegationProps) {
 const [filter,setFilter]=useState<Region|''>(''),[region,setRegion]=useState<Region>('GCC'),[target,setTarget]=useState(''),[grouped,setGrouped]=useState(true);
 const t=(ar:string,en:string)=>isAr?ar:en;
 const visible=dossiers.filter(d=>!filter||artistRegion(d)===filter);
 const candidates=dossiers.filter(d=>artistRegion(d)===region&&d.assignedCoordinatorId!==target);
 const blocked=candidates.some(d=>lockedIds.includes(d.id)||d.amendments?.some(a=>a.status==='PENDING'));
 const groups=grouped?(Object.keys(REGIONS) as Region[]).map(r=>({title:REGIONS[r][isAr?'ar':'en'],rows:visible.filter(d=>artistRegion(d)===r)})).filter(g=>g.rows.length):[{title:t('الفنانون','Artists'),rows:visible}];
 const select='mt-1 block w-full rounded border border-[#D9CEBA] bg-white ps-3 pe-3 py-2';
 return <section className="space-y-4 rounded-lg border border-[#D9CEBA] bg-[#F7F1E6] ps-5 pe-5 py-5 text-start"><h2 className="flex items-center gap-2 text-xl font-semibold"><Globe aria-hidden="true"/>{t('التفويض والتجميع الإقليمي','Regional Handoff & Grouping')}</h2>
 <p className="text-sm text-[#736357]">{t('توزيع تشغيلي للمحاكاة؛ ليس معيار تدقيق أو صلاحيات دخول. بلد المنشأ غير المطابق يبقى غير مصنف.','Operational rehearsal routing; not a vetting criterion or authentication. Unrecognized or ambiguous origins remain unclassified.')}</p>
 {canDelegate&&onDelegate&&<fieldset className="space-y-3 rounded border border-[#D9CEBA] bg-white ps-4 pe-4 py-4"><legend className="flex items-center gap-2 font-semibold"><Users aria-hidden="true" className="size-4"/>{t('تفويض حسب المنطقة — المنسق العام','Delegate by Region — General Coordinator')}</legend><div className="grid gap-3 sm:grid-cols-2"><label>{t('المنطقة','Region')}<select className={select} value={region} onChange={e=>setRegion(e.target.value as Region)}>{(Object.keys(REGIONS) as Region[]).filter(r=>r!=='UNCLASSIFIED').map(r=><option key={r} value={r}>{REGIONS[r][isAr?'ar':'en']}</option>)}</select></label><label>{t('المنسقة المستلمة','Receiving coordinator')}<select className={select} value={target} onChange={e=>setTarget(e.target.value)}><option value="">{t('اختر المنسقة','Select coordinator')}</option>{COORDINATORS.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><p>{candidates.length} {t('ملفات ستنقل','dossiers will transfer')}</p>{blocked&&<p role="status" className="text-amber-900">{t('التفويض مقفل: تتضمن المجموعة عقداً أو حجز قاعة أو مراجعة نطاق معلقة.','Handoff blocked: the group includes an agreement, room claim, or pending scope review.')}</p>}<button type="button" disabled={!target||!candidates.length||blocked} className="rounded bg-[#8B261E] ps-4 pe-4 py-2 text-white disabled:opacity-50 disabled:cursor-not-allowed" onClick={()=>onDelegate(region,target)}>{t('تفويض المجموعة','Delegate group')}</button></fieldset>}
 {notice&&<p role="status">{notice}</p>}
 <div className="flex flex-wrap items-end gap-4"><label>{t('تصفية المنطقة','Filter region')}<select className={select} value={filter} onChange={e=>setFilter(e.target.value as Region|'')}><option value="">{t('كل المناطق','All regions')}</option>{(Object.keys(REGIONS) as Region[]).map(r=><option key={r} value={r}>{REGIONS[r][isAr?'ar':'en']}</option>)}</select></label><label className="flex items-center gap-2"><input type="checkbox" checked={grouped} onChange={e=>setGrouped(e.target.checked)}/>{t('تجميع حسب المنطقة','Group by region')}</label></div>
 {!visible.length&&<p>{t('لا توجد ملفات ضمن الاختيار.','No dossiers in this selection.')}</p>}
 {groups.map(g=><section key={g.title} className="space-y-3"><h3 className="font-semibold">{g.title} · {g.rows.length}</h3><div className="grid gap-3 md:grid-cols-2">{g.rows.map(d=><article key={d.id} className="space-y-2 rounded border border-[#D9CEBA] bg-white ps-4 pe-4 py-4"><h4 className="font-semibold">{d.artistName}</h4><span className="inline-flex items-center gap-2 rounded bg-stone-100 ps-2 pe-2 py-1 text-sm"><MapPin aria-hidden="true" className="size-4"/>{REGIONS[artistRegion(d)][isAr?'ar':'en']}</span><p>{d.nationality} · {d.medium}</p><p className="text-sm">{COORDINATORS.find(c=>c.id===d.assignedCoordinatorId)?.name??t('غير مكلّف','Unassigned')}</p>{d.delegationHistory?.length ? <p className="text-xs text-[#736357]">{t('آخر إحالة','Last handoff')}: {new Date(d.delegationHistory.at(-1)!.at).toLocaleString(isAr?'ar-AE':'en-AE')}</p>:null}</article>)}</div></section>)}
 </section>;
}
