import React, { useEffect, useRef, useState } from 'react';
import { useSandbox } from './SandboxProvider';
import { applyTheme, emptyTheme, reasons, restoreTheme, type Essay, type Proposal, type ThemeEvent } from '../lib/themeWorkflow';

const KEY = 'sadu-theme-journal-v1';
const blankProposal = (): Proposal => ({ en: '', ar: '', rationale: '', feasibility: '', translation: '' });
const blankEssay = (): Essay => ({ introduction: { en: '', ar: '' }, context: { en: '', ar: '' }, checkedEn: false, checkedAr: false });
const input = 'mt-2 w-full rounded-lg border border-[#8C8173] bg-white p-3 text-sm focus-visible:outline-2 focus-visible:outline-[#8B261E]';
const button = 'rounded-lg bg-[#8B261E] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#8B261E]';
const secondary = 'rounded-lg border border-[#DED5C4] px-4 py-2.5 text-sm focus-visible:outline-2 focus-visible:outline-[#8B261E]';
export default function ThemeWorkspace() {
  const { role } = useSandbox();
  const [loaded] = useState(() => { try { return { state: restoreTheme(sessionStorage.getItem(KEY)), error: '' }; } catch { return { state: emptyTheme(), error: 'The saved theme journal cannot be read. Actions are locked to preserve it. Open a fresh tab to start another simulation.' }; } });
  const [state, setState] = useState(loaded.state);
  const latest = useRef(state);
  const [tab, setTab] = useState<'Proposal' | 'Bilingual essay' | 'Decisions'>('Proposal');
  const [proposals, setProposals] = useState<Proposal[]>(state.proposals.length ? state.proposals : [blankProposal(), blankProposal(), blankProposal()]);
  const [essay, setEssay] = useState<Essay>(state.essay || blankEssay());
  const [selection, setSelection] = useState<number | undefined>(state.selected);
  const [reason, setReason] = useState(reasons[0]);
  const [notes, setNotes] = useState('');
  const [anchor, setAnchor] = useState('Whole record');
  const [message, setMessage] = useState('');
  const [error, setError] = useState(loaded.error);
  const [hash, setHash] = useState('');
  const [preflight, setPreflight] = useState('');
  const dirty = (role === 'Committee' && state.phase === 'Proposal draft' && JSON.stringify(proposals) !== JSON.stringify(state.proposals.length ? state.proposals : [blankProposal(), blankProposal(), blankProposal()])) || (role === 'Editorial' && state.phase === 'Editorial draft' && JSON.stringify(essay) !== JSON.stringify(state.essay || blankEssay())) || !!notes.trim();
  useEffect(() => { if (!dirty) return; const warn = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ''; }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty]);
  const [language, setLanguage] = useState<'en' | 'ar'>('en');
  const [resolutionDrafts, setResolutionDrafts] = useState<Record<number, { resolution: string; explanation: string }>>({});
  const proposalEditable = role === 'Committee' && state.phase === 'Proposal draft';
  const essayEditable = role === 'Editorial' && state.phase === 'Editorial draft';
  const reviewing = (role === 'Director' && state.phase === 'Director review') || (role === 'Chairman' && ['Chairman review','Final review'].includes(state.phase));
  const run = (action: ThemeEvent['action'], fields: Partial<ThemeEvent> = {}) => {
    try {
      if (loaded.error) throw new Error(loaded.error);
      if (latest.current.events.length >= 1000) throw new Error('This demonstration journal is full. Start a new tab.');
      const next = applyTheme(latest.current, { ...fields, action, role, at: new Date().toISOString(), expected: latest.current.revision });
      sessionStorage.setItem(KEY, JSON.stringify({ version: 1, events: next.events }));
      latest.current = next; setState(next); setError(''); setHash(''); setMessage('Saved on this device. ' + next.phase + '.');
      if (action === 'SELECT' || action === 'SUBMIT_ESSAY') setTab('Bilingual essay');
      if (action === 'NEW_VERSION') { setEssay(blankEssay()); setSelection(undefined); setTab('Proposal'); }
      if (action === 'RETURN') { setNotes(''); setTab('Decisions'); }
    } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save. Your inputs remain available.'); }
  };
  const owner = state.phase === 'Director review' && !state.preflight ? 'Editorial' : { 'Proposal draft': 'Preparatory Committee', 'Director review': 'Director', 'Chairman review': 'Chairman', 'Editorial draft': 'Editorial', 'Final review': 'Chairman', Published: 'All departments' }[state.phase];
  const previousProposal = state.snapshots.filter(x => x.kind === 'SUBMIT_PROPOSAL').at(-2)?.proposals;
  const previousEssay = state.snapshots.filter(x => x.kind === 'SUBMIT_ESSAY').at(-2)?.essay;
  const visibleProposals = proposalEditable ? proposals : state.proposals;
  return <section aria-label="Theme and Editorial workspace" className="space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm uppercase tracking-widest text-[#8B261E]">Exhibition foundations</p><h1 className="mt-2 text-3xl font-serif">Theme &amp; Editorial</h1><p className="mt-2 text-sm text-[#655D50]">One shared record, from the first proposal to the approved bilingual essay.</p></div><span className="rounded-full border border-[#DED5C4] px-3 py-1 text-sm">{state.phase}</span></div>
    <div className="border-s-2 border-[#8B261E] ps-4 text-sm"><strong>Next owner: {owner}</strong><p className="mt-1 text-[#655D50]">{state.phase === 'Published' ? 'The approved record is available to every department below.' : `Choose ${owner} in the sandbox role selector to continue.`}</p></div>
    {role === 'Director' && state.events.some(e => e.role === 'Chairman' && e.action === 'RETURN') && <p className="text-sm text-[#655D50]">Chairman feedback has been routed directly to the responsible team. Open Decisions to review their responses.</p>}
    {state.selected !== undefined && role === 'General_Exhibition_Coordinator' && <p className="rounded-lg bg-[#EDE5D8] p-4 text-sm">Theme approved for planning. Begin feasibility and scheduling. Publication text remains {state.phase === 'Published' ? 'approved' : 'under Editorial review'}. This does not authorize expenditure, bookings or external outreach.</p>}
    {state.published && <details className="rounded-xl border border-[#DED5C4] bg-[#FFFDF9] p-5"><summary className="cursor-pointer font-semibold">Shared approved record · revision {state.published.revision}</summary><p className="mt-3 text-sm text-[#655D50]">Available to Director, Committee and General Coordinator. New drafts do not replace this approved snapshot.</p><h2 className="mt-4 font-serif text-xl">{state.published.proposals[state.published.selected].en}</h2><p lang="ar" dir="rtl" className="mt-2 font-serif text-xl">{state.published.proposals[state.published.selected].ar}</p>{(['introduction','context'] as const).map(section => <div key={section} className="mt-4 grid gap-5 md:grid-cols-2"><p className="whitespace-pre-wrap" lang="en" dir="ltr">{state.published!.essay[section].en}</p><p className="whitespace-pre-wrap" lang="ar" dir="rtl">{state.published!.essay[section].ar}</p></div>)}</details>}
    <nav aria-label="Theme workspace sections" className="flex flex-wrap gap-2 border-b border-[#DED5C4] pb-3">{(['Proposal','Bilingual essay','Decisions'] as const).map(t => <button key={t} aria-pressed={tab === t} onClick={() => setTab(t)} className={tab === t ? button : secondary}>{t}{t === 'Decisions' && state.notes.length > 0 ? ` (${state.notes.length})` : ''}</button>)}</nav>
    <div className={`grid gap-6 ${reviewing ? 'lg:grid-cols-[minmax(0,1fr)_280px]' : ''}`}>
      <div className="min-w-0 rounded-xl border border-[#DED5C4] bg-[#FFFDF9] p-5 md:p-7">
        {tab === 'Proposal' && <div className="space-y-6"><div><h2 className="text-xl font-serif">Three directions. One considered choice.</h2><p className="mt-2 text-sm text-[#655D50]">The Director endorses the shortlist. The Chairman selects one theme. Include early translation concerns before either review.</p></div>
          {!visibleProposals.length && <p className="text-sm">The Committee has not submitted a proposal yet.</p>}
          <div className={`grid gap-4 ${reviewing ? '' : 'lg:grid-cols-3'}`}>{visibleProposals.map((p, i) => <fieldset key={i} className="min-w-0 rounded-lg border border-[#DED5C4] p-4"><legend className="px-2 text-sm font-semibold">Proposal {i + 1}{state.selected === i ? ' · Selected' : ''}</legend>
            {previousProposal && JSON.stringify(previousProposal[i]) !== JSON.stringify(p) && <p className="mb-3 text-xs text-[#8B261E]">Changed since last review</p>}
            {proposalEditable ? <div className="space-y-4">{(['en','ar','rationale','feasibility','translation'] as const).map(key => <label key={key} className="block text-sm">{({ en: 'English title', ar: 'Arabic title', rationale: 'Rationale', feasibility: 'Feasibility & scope', translation: 'Early translation concerns' })[key]}<textarea aria-label={`Proposal ${i + 1}: ${key}`} value={p[key]} rows={key === 'en' || key === 'ar' ? 2 : 3} maxLength={12000} dir={key === 'ar' ? 'rtl' : 'ltr'} lang={key === 'ar' ? 'ar' : 'en'} className={input} onChange={e => setProposals(old => old.map((x,j) => j === i ? { ...x, [key]: e.target.value } : x))}/></label>)}</div> : <><h3 className="font-serif text-xl break-words">{p.en}</h3><p lang="ar" dir="rtl" className="mt-3 font-serif text-xl break-words">{p.ar}</p><p className="mt-4 whitespace-pre-wrap text-sm leading-6 break-words">{p.rationale}</p><details className="mt-4 border-t border-[#DED5C4] pt-3"><summary className="cursor-pointer text-sm">Scope & translation notes</summary><dl className="mt-3 space-y-3 text-sm"><div><dt className="font-semibold">Feasibility</dt><dd className="mt-1 whitespace-pre-wrap break-words">{p.feasibility}</dd></div><div><dt className="font-semibold">Translation concerns</dt><dd className="mt-1 whitespace-pre-wrap break-words">{p.translation}</dd></div></dl></details></>}
          </fieldset>)}</div>
          {state.preflight && <p className="text-sm"><strong>Editorial preflight:</strong> {state.preflight}</p>}
          {role === 'Editorial' && state.phase === 'Director review' && <div className="border-t border-[#DED5C4] pt-4"><label className="block text-sm">Early bilingual preflight findings<textarea className={input} rows={3} value={preflight} onChange={e => setPreflight(e.target.value)}/></label><p className="my-3 text-xs text-[#655D50]">Check the three bilingual directions now. Record concerns for the Director before endorsement.</p><button className={button} onClick={() => run('PREFLIGHT', { preflight })}>Record Editorial preflight</button></div>}
          {proposalEditable && <button className={button} disabled={!!loaded.error} onClick={() => run('SUBMIT_PROPOSAL', { proposals })}>Submit shortlist to Director</button>}
          {role === 'Committee' && state.phase === 'Published' && <button className={secondary} onClick={() => run('NEW_VERSION')}>Start a successor revision</button>}
        </div>}
        {tab === 'Bilingual essay' && <div className="space-y-6"><h2 className="text-xl font-serif">One essay, two reviewed languages</h2><p className="text-sm text-[#655D50]">Language direction is enforced. Cultural equivalence requires human Editorial review.</p>{state.selected !== undefined ? <p className="text-sm font-semibold">Selected theme: {state.proposals[state.selected].en}</p> : <p className="text-sm">The Chairman must select a theme before Editorial can submit.</p>}
          <div className="flex gap-2 md:hidden" aria-label="Editor language">{(['en','ar'] as const).map(l => <button key={l} aria-pressed={language === l} onClick={() => setLanguage(l)} className={language === l ? button : secondary}>{l === 'en' ? 'English' : 'Arabic'}</button>)}</div>
          {(['introduction','context'] as const).map(section => <fieldset key={section}><legend className="mb-2 capitalize font-semibold">{section}{state.phase === 'Final review' && (!previousEssay || JSON.stringify(previousEssay[section]) !== JSON.stringify(state.essay?.[section])) ? (previousEssay ? ' · Changed since last review' : ' · First submitted revision') : ''}</legend><div className="grid gap-5 md:grid-cols-2">{(['en','ar'] as const).map(l => <label key={l} className={`${language === l ? 'block' : 'hidden'} md:block text-sm`}>{l === 'en' ? 'English · LTR' : 'Arabic · RTL'}<textarea aria-label={`${section} ${l}`} lang={l} dir={l === 'ar' ? 'rtl' : 'ltr'} rows={9} maxLength={12000} readOnly={!essayEditable} value={(essayEditable ? essay : state.essay || essay)[section][l]} className={input} onChange={e => setEssay(old => ({ ...old, [section]: { ...old[section], [l]: e.target.value }, checkedEn: false, checkedAr: false }))}/></label>)}</div></fieldset>)}
          {essayEditable && <><div className="space-y-3">{(['checkedEn','checkedAr'] as const).map(k => <label key={k} className="flex items-center gap-3 text-sm"><input type="checkbox" checked={essay[k]} onChange={e => setEssay(old => ({ ...old, [k]: e.target.checked }))}/>{k === 'checkedEn' ? 'English reviewed by Editorial' : 'Arabic reviewed by Editorial'}</label>)}</div><button className={button} disabled={!!loaded.error} onClick={() => run('SUBMIT_ESSAY', { essay })}>Send paired revision to Chairman</button></>}
        </div>}
        {tab === 'Decisions' && <div className="space-y-5"><h2 className="text-xl font-serif">Review notes &amp; resolutions</h2><p className="text-sm text-[#655D50]">Chairman notes go directly to the responsible team. The Director can review every note and response here.</p>{!state.notes.length && <p className="text-sm">No changes have been requested.</p>}{state.notes.map(n => { const d = resolutionDrafts[n.id] || { resolution: 'Addressed', explanation: '' }; const canResolve = n.area === 'proposal' ? proposalEditable : essayEditable; return <article key={n.id} className="border-t border-[#DED5C4] pt-4"><h3 className="font-semibold">{n.reason}</h3><p className="mt-1 text-xs text-[#655D50]">{n.area} · {n.anchor}</p><p className="mt-3 whitespace-pre-wrap text-sm">{n.text}</p><p className="mt-2 text-sm">{n.resolution || 'Awaiting response'}{n.explanation ? ` — ${n.explanation}` : ''}</p>{canResolve && <div className="mt-3 space-y-3"><label className="block text-sm">Resolution<select className={input} value={d.resolution} onChange={e => setResolutionDrafts(old => ({ ...old, [n.id]: { ...d, resolution: e.target.value } }))}>{['Addressed','Clarification needed','Not adopted'].map(x => <option key={x}>{x}</option>)}</select></label><label className="block text-sm">Explanation<textarea className={input} rows={2} value={d.explanation} onChange={e => setResolutionDrafts(old => ({ ...old, [n.id]: { ...d, explanation: e.target.value } }))}/></label><button className={secondary} onClick={() => run('RESOLVE', { noteId: n.id, ...d })}>Save resolution</button></div>}</article>; })}
          <details className="border-t border-[#DED5C4] pt-4"><summary className="cursor-pointer text-sm">Decision history &amp; revision integrity</summary><ol className="mt-3 space-y-3 text-sm">{state.events.map((e,i) => <li key={i}>{i + 1}. {e.action.replaceAll('_',' ')} · {e.role.replaceAll('_',' ')} · {new Date(e.at).toLocaleString('en-GB')}</li>)}</ol><p className="mt-4 text-xs text-[#655D50]">Local simulation journal. SHA-256 is a content fingerprint, not a signature or proof against browser tampering.</p><button className={`${secondary} mt-3`} onClick={() => { void crypto.subtle.digest('SHA-256', new TextEncoder().encode(JSON.stringify(state.snapshots))).then(result => setHash(Array.from(new Uint8Array(result), b => b.toString(16).padStart(2,'0')).join(''))).catch(() => setError('Fingerprint generation is unavailable.')); }}>Show snapshot fingerprint</button>{hash && <p className="mt-3 break-all font-mono text-xs">{hash}</p>}<details className="mt-4"><summary className="cursor-pointer text-sm">Retained revision snapshots ({state.snapshots.length})</summary><pre className="mt-2 whitespace-pre-wrap break-all text-xs">{JSON.stringify(state.snapshots,null,2)}</pre></details></details>
        </div>}
      </div>
      {reviewing && <aside className="h-fit rounded-xl border border-[#DED5C4] bg-[#FFFDF9] p-5 space-y-4" aria-label="Review actions"><h2 className="font-serif text-xl">Review this revision</h2><p className="text-sm text-[#655D50]">Approval applies to the submitted text displayed here. {state.phase === 'Director review' && !state.preflight ? 'Editorial preflight is required before endorsement.' : state.phase === 'Final review' ? 'Open Bilingual essay to authorize the paired text.' : 'Open Proposal to review the shortlist.'}</p>{state.phase === 'Director review' && <button className={button} disabled={!state.preflight || tab !== 'Proposal'} onClick={() => run('ENDORSE')}>Endorse shortlist</button>}{state.phase === 'Chairman review' && <><label className="block text-sm">Select one theme<select className={input} value={selection ?? ''} onChange={e => setSelection(e.target.value === '' ? undefined : Number(e.target.value))}><option value="">Choose a theme</option>{state.proposals.map((p,i) => <option key={i} value={i}>{p.en}</option>)}</select></label><button className={button} disabled={selection === undefined || tab !== 'Proposal'} onClick={() => run('SELECT', { selected: selection })}>Approve selected theme</button></>}{state.phase === 'Final review' && <button className={button} disabled={tab !== 'Bilingual essay'} onClick={() => run('PUBLISH')}>Authorize publication</button>}<div className="border-t border-[#DED5C4] pt-4 space-y-3"><label className="block text-sm">Reason for changes<select className={input} value={reason} onChange={e => setReason(e.target.value)}>{reasons.map(r => <option key={r}>{r}</option>)}</select></label><label className="block text-sm">Section or paragraph<input className={input} value={anchor} onChange={e => setAnchor(e.target.value)}/></label><label className="block text-sm">Specific notes<textarea className={input} rows={4} value={notes} onChange={e => setNotes(e.target.value)}/></label><button className={secondary} disabled={!notes.trim()} onClick={() => run('RETURN', { note: { reason, text: notes, anchor } })}>Request changes</button></div></aside>}
    </div>
    {error && <p role="alert" className="text-sm text-[#8B261E]">{error}</p>}{message && <p role="status" className="text-sm">{message}</p>}
    <p className="text-xs text-[#655D50]">Sandbox workflow · Saved in this browser tab · No external publication or notifications</p>
  </section>;
}

