import {validatePassport,validatePersonalPhoto,INVALID_PR_FORMAT} from '../data/prFileValidation';
import { useEffect, useRef, useState } from 'react';
import { FileCheck, Users, AlertTriangle } from 'lucide-react';
import { pdfHasSignature, validPassportPDF, validVisaIntake, type VisaIntake } from '../data/visaIntake';
const panel='space-y-4 rounded border border-[#D9CEBA] bg-[#F7F1E6] ps-5 pe-5 py-5 text-start';
const input='mt-2 block w-full rounded border bg-white ps-3 pe-3 py-2';
export function VisaIntakeForm({contractId,isAr,onSubmit}:{contractId:string;isAr:boolean;onSubmit:(v:VisaIntake)=>void}) {
 const [number,setNumber]=useState(''),[expiry,setExpiry]=useState(''),[mother,setMother]=useState(''),[nationality,setNationality]=useState(''),[passport,setPassport]=useState<File>();
 const [companion,setCompanion]=useState(false),[name,setName]=useState(''),[companionPassport,setCompanionPassport]=useState<File>(),[agree,setAgree]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [personalPhoto,setPersonalPhoto]=useState<File>(),[photoDimensions,setPhotoDimensions]=useState<{width:number;height:number}>();
 const selections=useRef<Record<string,number>>({});
 const submitting=useRef(false);
 const [submitted,setSubmitted]=useState(false);
 const t=(ar:string,en:string)=>isAr?ar:en;
 async function pick(file:File|undefined,set:(f:File|undefined)=>void,key:string){set(undefined);const sequence=(selections.current[key]??0)+1;selections.current[key]=sequence;if(!file)return;try{await validatePassport(file);if(selections.current[key]===sequence){set(file);setNotice('');}}catch{if(selections.current[key]===sequence)setNotice(INVALID_PR_FORMAT);}}
 async function pickPhoto(file?:File){const sequence=(selections.current.photo??0)+1;selections.current.photo=sequence;setPersonalPhoto(undefined);setPhotoDimensions(undefined);if(!file)return;try{const dimensions=await validatePersonalPhoto(file);if(selections.current.photo===sequence){setPersonalPhoto(file);setPhotoDimensions(dimensions);setNotice('');}}catch(error){if(selections.current.photo===sequence)setNotice(error instanceof Error?error.message:INVALID_PR_FORMAT);}}

 return <form className={panel} onChange={()=>{setSubmitted(false);}} onSubmit={async e=>{e.preventDefault();if(submitting.current||submitted)return;submitting.current=true;setBusy(true);try{if(!passport||!await pdfHasSignature(passport)||companion&&(!companionPassport||!await pdfHasSignature(companionPassport)||!agree))throw new Error('invalid');if(!personalPhoto)throw new Error('photo');const checkedDimensions=await validatePersonalPhoto(personalPhoto);const intake:VisaIntake={id:crypto.randomUUID(),contractId,passportNumber:number.trim(),expiryDate:expiry,motherName:mother.trim(),nationality:nationality.trim(),passport,personalPhoto,photoDimensions:checkedDimensions,submittedAt:new Date().toISOString(),...(companion?{companion:{name:name.trim(),passport:companionPassport!,liabilityAcknowledged:true as const}}:{})};if(!validVisaIntake(intake))throw new Error('invalid');onSubmit(intake);setSubmitted(true);setNotice(t('أرسلت البيانات لمراجعة العلاقات العامة.','Submitted for PR review.'));}catch{setNotice(t('تحقق من البيانات وتاريخ الصلاحية وملفات PDF والإقرار.','Check required fields, expiry, PDF contents and companion acknowledgement.'));}finally{submitting.current=false;setBusy(false);}}}>
 <h3 className="flex items-center gap-2 text-xl font-semibold"><FileCheck aria-hidden="true"/>بيانات التأشيرة والجواز / Visa &amp; Passport Intake</h3><p className="text-sm">{t('محاكاة فقط — استخدم بيانات وملفات خيالية. تحفظ في ذاكرة الجلسة فقط.','Rehearsal only — use fictional details and sample documents. Stored in session memory only.')}</p>
 <fieldset disabled={busy} className="space-y-4"><label className="block">{t('رقم الجواز','Passport Number')}<input required maxLength={50} autoComplete="off" className={input} value={number} onChange={e=>setNumber(e.target.value)}/></label><label className="block">{t('تاريخ انتهاء الجواز','Expiry Date')}<input required type="date" className={input} value={expiry} onChange={e=>setExpiry(e.target.value)}/></label><label className="block">{t('اسم الأم','Mother’s Name')}<input required maxLength={200} autoComplete="off" className={input} value={mother} onChange={e=>setMother(e.target.value)}/></label><label className="block">{t('الجنسية الحالية','Current Nationality')}<input required maxLength={100} className={input} value={nationality} onChange={e=>setNationality(e.target.value)}/></label>
 <p className="flex items-start gap-2 rounded border border-red-300 bg-red-50 ps-4 pe-4 py-4 text-red-900"><AlertTriangle aria-hidden="true" className="size-5 shrink-0"/>Attention: UAE Immigration requires a clear, flat PDF scan of your passport. Photographs taken via mobile phone will be automatically rejected by PR &amp; Protocol.</p><p className="text-xs">{t('تعليمات العرض: يفحص النظام الصيغة فقط؛ وضوح المسح ومصدره يحتاجان مراجعة بشرية.','Rehearsal instruction: format checks cannot determine scan quality or whether a phone was used; PR must inspect the document.')}</p>
 <label className="block rounded border-2 border-dashed ps-4 pe-4 py-4">{t('نسخة الجواز — PDF فقط','Passport scan — PDF only')}<input required type="file" accept=".pdf,application/pdf" className="mt-2 block w-full" onChange={e=>void pick(e.target.files?.[0],setPassport,'primary')}/></label>
 <label className="block rounded border-2 border-dashed ps-4 pe-4 py-4">Personal Photo / الصورة الشخصية — JPEG/PNG, at least 1200 × 1200 pixels<input required type="file" accept=".jpg,.jpeg,.png,image/jpeg,image/png" className="block w-full" onChange={e=>void pickPhoto(e.target.files?.[0])}/></label><p className="text-sm">Pixel dimensions and file contents are checked. This prototype threshold does not certify clarity, capture source, or immigration acceptance; PR review is still required.</p>
 <label className="flex items-center gap-2"><Users aria-hidden="true" className="size-5"/><input type="checkbox" checked={companion} onChange={e=>{setCompanion(e.target.checked);setAgree(false);}}/>مرافق سفر / Add Travel Companion (Spouse/Assistant)</label>
 {companion&&<section className="space-y-3 rounded border bg-white ps-4 pe-4 py-4"><p>The Sharjah Calligraphy Biennial covers travel and accommodation for the invited artist only. By adding a companion, you request that PR book them on the same flight and hotel, but you acknowledge full financial responsibility for their expenses.</p><label className="block">{t('اسم المرافق','Companion name')}<input required maxLength={200} className={input} value={name} onChange={e=>{setName(e.target.value);setAgree(false);}}/></label><label className="block">{t('جواز المرافق — PDF فقط','Companion passport — PDF only')}<input required type="file" accept=".pdf,application/pdf" className="mt-2 block w-full" onChange={e=>{setAgree(false);void pick(e.target.files?.[0],setCompanionPassport,'companion');}}/></label><label className="flex items-center gap-2"><input required type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)}/>I agree to cover all companion expenses.</label></section>}
 <button disabled={busy||submitted||!passport||!personalPhoto||!photoDimensions||companion&&(!agree||!companionPassport)} className="rounded bg-[#8B261E] ps-4 pe-4 py-3 text-white disabled:opacity-50">{t('إرسال إلى العلاقات العامة','Submit to PR')}</button></fieldset><p role="status">{notice}</p></form>;
}
function PassportDownload({file}:{file:File}){const [url,setUrl]=useState('');useEffect(()=>{const u=URL.createObjectURL(file);setUrl(u);return()=>URL.revokeObjectURL(u);},[file]);return <a href={url||undefined} download={file.name} className="break-all underline">{file.name}</a>;}
export function VisaIntakeReview({intake,isAr}:{intake:VisaIntake;isAr:boolean}) {
 return <section className={panel}><h2 className="text-xl font-semibold">{isAr?'بيانات التأشيرة والجواز':'Visa & Passport Intake'}</h2><dl className="space-y-2">{[['Passport number',intake.passportNumber],['Expiry date',intake.expiryDate],["Mother’s name",intake.motherName],['Current nationality',intake.nationality]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><PassportDownload file={intake.passport}/>{intake.personalPhoto&&<PassportDownload file={intake.personalPhoto}/>}{intake.companion&&<section className="space-y-3 border-t pt-4"><h3 className="flex items-center gap-2 font-semibold"><Users aria-hidden="true"/>{intake.companion.name}</h3><PassportDownload file={intake.companion.passport}/>{intake.companion.liabilityAcknowledged&&<p className="rounded bg-emerald-50 ps-3 pe-3 py-2 text-emerald-800">Financial Liability Acknowledged by Artist</p>}<p className="text-xs">{isAr?'إقرار مسجل للمحاكاة، ليس اعتماداً قانونياً أو حجزاً مؤكداً.':'Recorded rehearsal acknowledgement; not legal certification or a confirmed booking.'}</p></section>}<p>{intake.submittedAt}</p></section>;
}
