import {useEffect,useRef,useState} from 'react';
import {ShieldAlert,FileCheck} from 'lucide-react';
import {pilotSupabase as client} from '../lib/pilotSupabase';
import {useOperationalRows} from '../lib/useOperationalRows';
import type {GuestTravelRow} from '../data/guestTravel';
type Notice={contract_id:string;visa_status:'REJECTED_BY_AUTHORITY';delivery_status:'TEMPLATE_APPROVAL_REQUIRED'|'PENDING_DELIVERY';recorded_at:string;body_ar:string|null;body_en:string|null};
type Template={version:string;body_ar:string;body_en:string;approved_at:string|null};
export function VisaAuthorityPanel({guests,review}:{guests:GuestTravelRow[];review:boolean}){
 const queue=useOperationalRows<Notice>('sadu_visa_notifications'),templates=useOperationalRows<Template>('sadu_visa_notice_templates');
 const [intake,setIntake]=useState(''),[reference,setReference]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const running=useRef(false),epoch=useRef(0);
 useEffect(()=>{const sub=client?.auth.onAuthStateChange(()=>{epoch.current++;setBusy(false);setIntake('');setReference('');setConfirmed(false);setMessage('');});return()=>{epoch.current++;sub?.data.subscription.unsubscribe();};},[]);
 const guest=guests.find(g=>g.id===intake&&g.finalized_at),recorded=queue.rows.some(n=>n.contract_id===guest?.contract_id);
 async function record(){if(!client||running.current||!review||!guest||recorded||!confirmed||reference.trim().length<3)return;running.current=true;setBusy(true);const version=epoch.current;
 try{const result=await client.rpc('sadu_record_visa_refusal',{p_intake:guest.id,p_reference:reference.trim()});if(version!==epoch.current)return;if(result.error)throw new Error();await queue.refresh();if(version!==epoch.current)return;setMessage('Authority decision recorded. See notification status below; no email delivery is claimed.');setReference('');setConfirmed(false);}catch{if(version===epoch.current)setMessage('Recording blocked. Check PR authority, current finalized packet and the decision reference.');}finally{running.current=false;if(version===epoch.current)setBusy(false);}}
 return <section className="space-y-3 rounded border border-[#D9CEBA] bg-[#F7F1E6] ps-4 pe-4 py-4 text-start"><h3 className="flex gap-2 text-xl"><ShieldAlert aria-hidden="true"/>Visa Authority Decision / قرار جهة التأشيرات</h3>
 <p>Only PR records the external authority’s decision. No security reasons are requested or inferred. / يسجل قسم التشريفات قرار الجهة المختصة دون تفسير أسباب الرفض.</p>
 {review&&<><fieldset disabled={busy} className="space-y-3"><label className="block">Finalized guest packet / ملف الضيف<select className="block w-full rounded border ps-3 pe-3 py-2" value={intake} onChange={e=>{setIntake(e.target.value);setReference('');setConfirmed(false);}}><option value="">Select guest</option>{guests.filter(g=>g.finalized_at).map(g=><option value={g.id} key={g.id}>{g.artist_name}</option>)}</select></label><label className="block">Authority decision reference — no reasons or passport details / مرجع القرار<input maxLength={200} className="block w-full rounded border ps-3 pe-3 py-2" value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="flex gap-2"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified the authority’s refusal for this guest. / تحققت من قرار الرفض للضيف المحدد.</label><button type="button" disabled={!guest||recorded||!confirmed||reference.trim().length<3} onClick={()=>void record()} className="rounded bg-red-800 text-white ps-4 pe-4 py-2 disabled:opacity-50">Record REJECTED_BY_AUTHORITY / تسجيل رفض الجهة</button></fieldset>
 <details><summary>Notification template preview — approval status / معاينة الإشعار</summary>{templates.rows.map(t=><article key={t.version} className="space-y-2 border-s-4 ps-3"><b>{t.approved_at?'Approval recorded':'DRAFT — institutional approval required'} · {t.version}</b><p dir="rtl" lang="ar">{t.body_ar}</p><p lang="en">{t.body_en}</p></article>)}</details></>}
 <p aria-live="polite">{message}</p><p>{queue.notice}</p>
 {queue.rows.map(n=><article key={n.contract_id} className="space-y-2 rounded border border-red-200 bg-[#FFFDF7] ps-3 pe-3 py-3"><h4><FileCheck className="inline size-4" aria-hidden="true"/> {guests.find(g=>g.contract_id===n.contract_id)?.artist_name??'Guest record'} · {n.visa_status}</h4><p>{new Date(n.recorded_at).toLocaleString()}</p><p>{n.delivery_status==='TEMPLATE_APPROVAL_REQUIRED'?'Official notification awaiting institutional template approval. / الإشعار الرسمي بانتظار اعتماد الصياغة.':'Approved notification queued — not emailed. / الإشعار المعتمد في قائمة الإرسال ولم يُرسل بالبريد.'}</p>{n.body_ar&&<p dir="rtl" lang="ar">{n.body_ar}</p>}{n.body_en&&<p lang="en">{n.body_en}</p>}</article>)}
 <p>Email transport is not configured. Coordinators do not receive refusal details or compose these notices.</p></section>;
}
